### ISSUE TITLE
Plugin? Or entire app?

### ISSUE THREAD

**Issue by trusktr** [reactioncommerce/reaction#1032]
Can reaction be added to existing Meteor apps? Or is it a full-site-from-the-get-go type of thing?

**Comment by jshimko** [comment]
Technically, anything is possible if you have the development skills.  But yeah, Reaction is kind of intended to be a separate app.  

My personal recommendation for combining it with another Meteor app is to [use Meteor's DDP protocol to remotely interface with the app](http://docs.meteor.com/api/connections.html#DDP-connect).  Pretty much everything Reaction does can be accessed with Meteor methods, publications, collections, etc.  

So from your external app, you could do something like:

```js
// establish a remote DDP connection
const Reaction = DDP.connect('https://my-reaction-site.com/');

// Now you can...

// Methods
Reaction.call('anyReactionMethod', methodArgs, callback);

// Pub/Sub
Reaction.subscribe('anyReactionPublication');

// Collections
const MyCollection = new Mongo.Collection('my-collection', {
  connection: Reaction
});
```

**Comment by trusktr** [comment]
Thanks for the tips! I will dive in. The reason I ask is because we'd like to design our own product pages, and or other parts of the site that can contain thumbs to products, etc. I'm thinking maybe we can move the whole store to a sub route, that way other routes can be non-store related, but with ability to place thumbnails, etc (for example, a blog, or some fancy product showcase, etc).

**Comment by trusktr** [comment]
I'm also thinking maybe the whole store itself can be a template, and can be placed anywhere (so it can be wrapped with an outter, higher-level nav, for example).

What's going on [here](https://github.com/reactioncommerce/reaction/blob/b6a320a589542c229274872f6dc694c9832db52a/packages/reaction-core-theme/lib/bootstrap/docs/_layouts/home.html)? Is reaction using a bootstrap alternate to Blaze?

**Comment by trusktr** [comment]
Can you briefly describe (or link to) the architecture of the stack?

**Comment by aaronjudd** [comment]
See docs here (use the development dropdown to get the the latest):

https://docs.reactioncommerce.com/reaction-docs/development/tutorial

**Comment by jshimko** [comment]
@trusktr Well, app structure happens to be a slightly complicated question to answer right now because we're working on a huge restructure of the app (see the `[module-structure](https://github.com/reactioncommerce/reaction/tree/module-structure)` branch).  As Meteor transitions to being more in line with the greater Javascript/NPM ecosystem, they (and we) are transitioning away from Meteor packages in favor of logical modules within the app and NPM packages.  It's a fairly large shift from the way Meteor has been doing things for the last few years, but it's a lot more in line with the structure of most other Node based apps.  If nothing else, it allows developers that are already familiar with JS/Node to jump right in and not need to learn as much of the magic that Meteor brings to the table.

We hope to be releasing the new structure (and related documentation) fairly soon.  Until then, you can follow along on the branch above and see the section of the [Meteor Guide](http://guide.meteor.com/) on application structure (we don't use the `imports` folder, but the rest of the Meteor app structure, NPM usage, and module import/export stuff is relevant).  

And finally, as I mentioned in another issue, our [forum](http://discourse.reactioncommerce.com/) is probably a better place to have conversations like this.  Mostly because this isn't an actual "issue", but also because others can potentially benefit from reading it in the future (since most people probably wouldn't search closed Github issues for a topic like this).  

Thanks!
