### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by PolGuixe** [reactioncommerce/reaction#1067]
Hi guys, 

I would like to contribute, but it looks like that right now is not the best moment, as you are doing a major refactor to move everything to modules -great choice-.

I would like to start creating my modules, but honestly, I don't know where to start. Any recommendations?

**Comment by jshimko** [comment]
There isn't a good example of the new way of doing things to point to yet (because we're still working that out), but one of the tasks on my to-do list for this week is write up an example module/package that shows how to get started with customizing Reaction.  Keep an eye out for that.  Once it's ready, we'll post something on the forum and add more details to the docs.

**Comment by aaronjudd** [comment]
we've update all the general docs, and we're updating the customization guide in #1114.   I'd say it's now safe to jump in and start contributing on the `development` branch.
