### ISSUE TITLE
[Marketplace] Add support for sub-vendors in BrainTree

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1118]
_Migrated from Braintree Repo_

BrainTree allows you to have "Sub-Vendors" so that a marketplace site could allow disbursements directly to vendors who have signed up.

From a comment on the ticket

"Hey take a look at my package it completely wraps the Braintree API including sub merchant accounts and it uses meteor async so it waits for the response before moving forward (which makes transactions much easier) https://atmospherejs.com/patrickml/braintree"

**Comment by spencern** [comment]
Hey, we're going to leave the tag Pull Requests Encouraged and `needs-more-detail` on here, but we're going to close this issue because the requirements need to be defined better. If this is an issue that you would like to pursue, please create a new issue with more detail and more specific requirements and link to this old issue.
