### ISSUE TITLE
Reaction not starting after installation on Windows

### ISSUE THREAD

**Issue by agnesv2** [reactioncommerce/reaction#1264]
### Expected behavior

Reaction starting correctly.
### Actual Behavior

After installing reaction for the first time and doing **reaction run** I get the following error:

![error](https://cloud.githubusercontent.com/assets/20892219/17465107/281680aa-5cf7-11e6-9120-914bc141a68d.png)

For reference, **reaction -v** gives:

![v](https://cloud.githubusercontent.com/assets/20892219/17465119/72e4bed0-5cf7-11e6-9f12-f30b7b401a97.png)
### Steps to Reproduce the Behavior

Install reaction on win10 following the requirements and installation guides at Reaction docs.

**Comment by jshimko** [comment]
What happens if you run `meteor npm i` and then try again?

**Comment by agnesv2** [comment]
`meteor npm i` produced the following results: 
![postinstall](https://cloud.githubusercontent.com/assets/20892219/17469226/a03ff282-5d38-11e6-9f44-86a421efd59a.png)

`reaction run` behaved the same as before.

**Comment by jshimko** [comment]
Ah.  Once again, it's because Windows won't run bash scripts.  Specifically, it's [this bash script](https://github.com/reactioncommerce/reaction/blob/master/.reaction/scripts/postinstall.sh) that gets called from [the npm post-install hook](https://github.com/reactioncommerce/reaction/blob/master/package.json#L22). 

Try removing [line 22 from that package.json](https://github.com/reactioncommerce/reaction/blob/master/package.json#L22) and run the commands again (`meteor npm i && reaction`).  Removing that will cause another issue, but it should at least let the app finish building.  Let me know if that fixes it and I'll start working on the necessary fixes.

**Comment by agnesv2** [comment]
After removing line 22 from package.json running `meteor npm i` works fine (i.e. gives no errors). However, `reaction run` still produces the exact same error as in the beginning.

**Comment by jshimko** [comment]
Do you have the [Microsoft Build Tools](https://www.microsoft.com/en-us/download/details.aspx?id=48159) installed?

**Comment by jshimko** [comment]
And everything else here...
https://docs.reactioncommerce.com/reaction-docs/development/requirements#windows

**Comment by agnesv2** [comment]
I have Microsoft Build Tools installed. I have also installed Node.js with npm, Win32 OpenSSL, Git+msysgit and Imagemagick.

**Comment by hrath2015** [comment]
I had same problem on new windows 10 while setting it up all new.  This is what solved for me.   comment `oauth-encryption@1.1.13` in packages file in .meteor directory. 
 **reaction run**.  App should start without any issue.  
Stop the app ^c. 
Uncomment the entry in  packages file and save. Open another cmd window and run reaction again.  I am running the cmd window as admin.  Should not see the error message.

**Comment by agnesv2** [comment]
Thank you very much, this fixed it!

**Comment by jshimko** [comment]
I'm going to reopen this issue because just manually removing things from the `.meteor/packages` file or `package.json` isn't an ideal/recommended fix for Windows build issues.  That surely will just cause another issue for you at some point in the future when something doesn't work anymore.  I don't personally know why `oauth-encryption` was originally added (probably for accounts stuff), but it was presumably for a good reason at some point.  I'd like to investigate this further before giving the blessing to remove it completely.

**Comment by hrath2015** [comment]
This issue is not with everybody. May be very few might have faced it.   It  need to be done only 1st time.
if you have noticed,  changes are undone before the next restart.  After this it is BAU.  Even future new  **reaction init** will not have any issue. 
Not sure why this behavior but windows is always full of  mysteries.   As u suggested ideal would be to remove package if no impact. I can tell for sure it is not breaking anything functionally. I was not using it on  my windows install for last 1 year. Not sure about encryption layer stuff though.

**Comment by jshimko** [comment]
Oh, interesting.  Thanks for the helpful details.  I'll let you know what I come up with.

Thanks!

**Comment by jshimko** [comment]
Since we haven't heard of this being a problem for anyone in the last 10 months, I'm going to close this for now.  Feel free to reopen if you believe this is still a problem.

**Comment by SuhailHassan** [comment]
![image](https://user-images.githubusercontent.com/38312046/38662387-bc54c8d4-3e51-11e8-90c2-6292b97019cf.png)

Reaction  not running
