### ISSUE TITLE
[UI] edit icon in safari

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1291]
Edit icon is not centered correctly.  Safari Only. Looks ok in FF, Chrome.

![example-product_and_reactioncommerce_reaction__reaction_commerce_and_logout_and_login_inline_page_behavior_ _issue__1122_ _reactioncommerce_reaction_and_reactioncommerce_reaction](https://cloud.githubusercontent.com/assets/439959/17649831/b6a32940-61f2-11e6-937c-16b3fa290c7c.png)

**Comment by kieckhafer** [comment]
Cannot replicate, this issue seems to be fixed.

<img width="888" alt="screen shot 2016-12-14 at 7 04 04 pm" src="https://cloud.githubusercontent.com/assets/4482263/21210464/2aaf3d36-c230-11e6-9cca-b5a85f544e9e.png">

<img width="617" alt="screen shot 2016-12-14 at 7 04 55 pm" src="https://cloud.githubusercontent.com/assets/4482263/21210478/3eaf1d06-c230-11e6-845a-37adb840a7fa.png">

<img width="613" alt="screen shot 2016-12-14 at 7 05 02 pm" src="https://cloud.githubusercontent.com/assets/4482263/21210479/40455374-c230-11e6-8c54-17b450af16a7.png">

**Comment by aaronjudd** [comment]
Seems to be resolved.
