### ISSUE TITLE
Adding a custom tax rate for a state applies to any state

### ISSUE THREAD

**Issue by ivanbportugal** [reactioncommerce/reaction#1352]
### Expected behavior
For my business, I only have one location in Texas. So, if I ship to a Texas address I should charge a 8.25% tax rate. However, if someone from a different state places an order, I should _not_ charge any tax at all. I would expect a custom tax rate to apply to either the state or the zip code I enter (whichever is more specific).
### Actual Behavior
If I try to place an order from "Florida" (a non-Texas state) the same 8.25% rate is applied. To mitigate this problem I tried to enter a second rate of `0` that applies to just the United States (no particular state). But, reaction just honors the order not the more specific setting.
### Steps to Reproduce the Behavior
See screenshots below to reproduce:
Config screenshot:
<img width="460" alt="screen shot 2016-09-05 at 6 06 28 pm" src="https://cloud.githubusercontent.com/assets/1224284/18258110/38d12b20-7395-11e6-867a-8cfb4938c7e8.png">
Cart (ordering from Florida not Texas). Notice the tax amount - it should be ZERO:
<img width="1181" alt="screen shot 2016-09-05 at 6 08 47 pm" src="https://cloud.githubusercontent.com/assets/1224284/18258112/40662e8a-7395-11e6-985f-3bd0dd37f742.png">

### Other interesting tax info:
I tried connecting to Avalara and TaxCloud and neither follow this simple tax rule. Avalara simply says "where are you shipping to? oh ok, here's the tax rate" <- wrong-o! TaxCloud is even worse, it assumes that you collect tax from "the following states". WTF???

**Comment by ivanbportugal** [comment]
This is most likely where the logic would have to be implemented:

https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/taxes/server/methods/methods.js#L114

Snippet for your convenience:
```javascript
          const addressTaxData = Taxes.find(
            {
              $and: [{
                $or: [{
                  postal: shippingAddress.postal
                }, {
                  postal: { $exists: false },
                  region: shippingAddress.region,
                  country: shippingAddress.country
                }, {
                  postal: { $exists: false },
                  region: { $exists: false },
                  country: shippingAddress.country
                }]
              }, {
                shopId: shopId
              }]
            }, {sort: { postal: -1 } }
          ).fetch();
```

**Comment by aaronjudd** [comment]
@ivanbportugal thanks for this info. This was the first pass on the Taxes, we'll be iteratively updating over the next few releases to give the functionality, so great to get some early feedback. 
The way you describe your desired Flat Rates is the way I was expecting it work,  I'll test out your updates.  Working on getting some tests written around this as well ;-)

**Comment by aaronjudd** [comment]
I've been unable to replicate the scenario described above (Florida getting Texas rates). 

![cart_checkout_and_key_west_bars__restaurants___nightlife___duval_street_key_west](https://cloud.githubusercontent.com/assets/439959/18407034/4eb10806-76bb-11e6-851b-89206ae8246a.png)
![cart_checkout_and_dashboard](https://cloud.githubusercontent.com/assets/439959/18407037/63e4f2c8-76bb-11e6-974b-19867f25a20d.png)


_I believed_ with TaxCloud you would need to configure your tax States and your Location in their system, but I was just testing and strangely - where it should return California (it does) and not Florida (it doesn't), but then it IS returning texas rates... 

![cart_checkout_and_taxcloud__merchant_account](https://cloud.githubusercontent.com/assets/439959/18407118/f7abe45c-76bc-11e6-87f6-892b268e1857.png)

so as you put it.. wtf.. apparently, there's more to this story, so digging into this as well.. I guess it would be easy to limit on our end rather than rely on their configurations

**Comment by ivanbportugal** [comment]
@aaronjudd thanks for looking into this, I will retest on my environment to see if something is going on. As for TaxCloud, the annoying thing is: they offer a free plan that is completely useless to... anyone? Perhaps they should just say that their base price is $10 or something because that's the only way you can configure the states.

As for the custom tax rates on reaction, I hope that it is just my fault. I'll let you know as soon as I test this out one more time.

Thanks again!

**Comment by ivanbportugal** [comment]
I don't flipping' understand... I cannot reproduce the bug I just filed. Let's close this issue... Unless you wanted to work on something else related to this.
