### ISSUE TITLE
resolve deprecated to-iso-string warning

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1395]
Resolve npm warnings introduced by (I think) by `wdio-mocha-framework` (which is a devDependency).  I believe this was introduced in #1315

```
Reinstalling node_modules...
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

```

Might be just needing updated packages, or might need more (PR to projects?)...

**Comment by Capt-Slow** [comment]
After doing some serious digging this is what I found.

`wdio-mocha-framework` is using an older version of mocha `2.3.3`. I found the following when going through mocha issues.

https://github.com/mochajs/mocha/issues/2200

"`npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade`

....
We cannot upgrade to `pug` atm as this would cause old versions of npm to fail. For now we support Node.js v0.8.x out of the box. Support will be dropped @ next major." --mocha dev

https://github.com/mochajs/mocha/pull/2350

They released `mocha v3.0.0` which contains the dependency fixes.

So I forked `wdio-mocha-framework` and changed mocha version to 3. This eliminated the warnings we get at startup. I found that I was unable to use the standard fork. So I installed all npm modules for `wdio-mocha-framework` and pushed it to my fork. This almost worked, but I found there are further mocha version dependencies in the code. Not an easy fix from what I'm able to gather. 

So I reached out to the `webdriverio` devs...

![screen shot 2016-09-16 at 3 47 22 pm](https://cloud.githubusercontent.com/assets/321416/18603472/ab82fe84-7c26-11e6-8b81-163972187ef0.png)


So there's that. I was told if it doesn't cause any conflicts to just ignore - for now.

I looked at `nightwatchjs` out of curiosity and it appears they have the same issues.

https://github.com/nightwatchjs/nightwatch/issues/996

Everyone appears to be ignoring these. The reason this hasn't been fixed is due to backwards compatibility with earlier versions of `npm`.

**Comment by kieckhafer** [comment]
This seems to no longer be an issue.

**Comment by zenweasel** [comment]
I am still seeing `npm WARN deprecated node-uuid@1.4.7: use uuid module instead` when doing a `reaction reset` and deleting node modules

**Comment by kieckhafer** [comment]
Yes, i'm seeing that too. I'll update that and make a PR, this issue is related to an older warning we were seeing though that I don't see anymore.

**Comment by kieckhafer** [comment]
Looks like three of our `npm` packages use node-uuid, I'm submitting PR request to bump versions where I can.
