### ISSUE TITLE
elevate current default logging levels

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1398]
I suggest that we replace the current use of logging _info_ levels with _debug_ , and update _debug_ to use _trace_. 

```
Logger.info -> Logger.debug
Logger.debug -> Logger.trace
```

Our current use of info is just too noisy, and is mostly suited for development information.  The cases where we actually use debug are really worst case issues, so I think it make sense to just bump up the levels used, and use info for just the absolute "info" type messages (ie: a system process that doesn't occur very often -> not debugging or event logging).

This would likely mean a giant search and replace, as well as a update to the debug log level configuration. (both implying a potential conflict heavy branch, ideally timed right before a release I think). This is also related to #808 and could be an ideal time to make some of those updates.

**Comment by impactmass** [comment]
`.debug -> .trace` - affects ~60 files
`.info -> .debug` - affects 9 files.

With the current default log level set as "INFO" (except if overridden by env var), a bunch of logs which are moving to debug and trace won't show up. So.. we need to look at those that we really want to show.

Question: This issue is titled "elevate current default logging levels", but going from "info" to "debug" and "debug" to "trace" is actually demoting the log level. Is that the plan? cc @aaronjudd

**Comment by aaronjudd** [comment]
I feel as though we've largely done this, in the way we've been determining the levels since this issue was created.   Now a wholesale search and replace might not be advisable, as it could be a lot of instance we're the level is/will be appropriate ( maybe a manual walkthrough, but this might require a good sense of what should be logged for info ).  Perhaps adding the debug log level as a prettify console, and trace as the raw json debug would be appropriate as a first step.

**Comment by impactmass** [comment]
@aaronjudd I've added the first step you mentioned of using raw json when trace is enabled [here](https://github.com/reactioncommerce/reaction/pull/1997).
Any other modifications to be made under this task before I open the PR for review?

One side effect here: When `trace` log format is set as "json", debug logs (since they're are a level above trace) also appear as json, except if defined otherwise. I think it's fine, or would you want this defined?

**Comment by hrath2015** [comment]
Time in logs is shown in UTC.  Is there a way to override it to use Timezone of choice(or at least local time) 
While you are at it, can this be addressed. Sorry if it is not a right place to ask or suggest.

**Comment by jshimko** [comment]
@hrath2015 As things are right now, you would have to make your own custom logger and format the output stream, but that wouldn't solve it for logger instances that already exist in Reaction.  It's pretty standard to use UTC for server logs (so that they're universal and timestamps aren't dependent on where you view them).  

I suppose we could discuss making that customizable though.  We're really only talking about stdout and that's only intended for humans to read anyway.  It wouldn't be my preference to alter that, but I can understand why someone might want to.  

Take a look at the formatter we use to see how the stdout output is generated.

https://github.com/thlorenz/bunyan-format/blob/master/lib/format-record.js#L178-L187

We'd essentially need a custom formatter based on that and then add an env var in there that allows you to optionally convert the date string (or something like that).

**Comment by hrath2015** [comment]
Thanks  a lot for clarification.  @jshimko

**Comment by aaronjudd** [comment]
Resolved in #1997
