### ISSUE TITLE
Options / OpenExchange settings organization

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1403]
Some updated dashboard organization for the `Core->Settings->Options` to consider:
- [ ]  Move openExchange rate settings into the Catalog card settings. 
- [ ]  provide link to OpEx 
- [ ] Use heading of "Exchange Rates" and add enable/disable options. 
- [ ] Add JobControl options
- [ ] Give the "Google Settings" it's own subsection in the Core->Settings (or propose a better place for this.  It's a little confusing what this is actually for).
- [ ]  update docs, I think these need some more depth in the docs

**Comment by aaronjudd** [comment]
Also moving `Allow Guest Checkout` to Catalog would make sense to me.

**Comment by zenweasel** [comment]
I keep thinking that what we need is a search for settings. This was one of my favorite features when I started using IntelliJ, to be able to hotkey search to go directly to a setting without worrying about the taxonomy. And since all settings keys are stored in the db seems like it wouldn't be too hard?

That doesn't negate the previous suggestions, just while we are talking about settings Taxonomy.

**Comment by rymorgan** [comment]
@zenweasel We've started to explore a search option for the dashboard

**Comment by aldeed** [comment]
Open exchange feature has been removed for now. Closing
