### ISSUE TITLE
Title gets truncated in FF

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1508]
### Expected behavior

Entire Product Title should display
### Actual Behavior

Product title is truncated when it extends past the length of the image
<img width="419" alt="reaction" src="https://cloud.githubusercontent.com/assets/72819/19507427/6209058e-9605-11e6-89cc-975a55d8fd9a.png">
### Steps to Reproduce the Behavior
1. Change the title to something longer (Basic Reaction Super Rad Product Today)
2. Load site in Firefox
3. Observe truncated title.

**Comment by kieckhafer** [comment]
Can also reproduce in Chrome and Safari.

I don't know if this is so much a UI issue as a decision that we need to make about how much text we want to shown. If we turn off the CSS property `white-space: nowrap;`, the text wraps to the second line instead of being truncated:

![reaction](https://cloud.githubusercontent.com/assets/4482263/21947700/5709d8dc-d99b-11e6-8b8c-cfdea78bf5dd.png)

Do we want to wrap to a second line. Do we want to show and ellipses on the first line if the title is too long?

@rymorgan, thoughts?
