### ISSUE TITLE
Order Processing - handling multiple orders through the checkout flow

### ISSUE THREAD

**Issue by reduxdj** [reactioncommerce/reaction#154]
Is there a plan to support this use-case?

**Comment by boboci9** [comment]
Hi all, 
I was considering and prototyping out a second solution for multi vendor solutions, one where there is a parent order created from multiple shops and in the same time several suborders for the individual shops containing only the items from their shops, and the shipping selected for their shop, this way each seller can view their orders having access only to the suborders (which have the same schema in the same collection only an additional field parentOrderId is set, while the parent order has a flag suborders true). There would be a super admin which would have access to the parent orders containing data form multiple shops while each shops admin having access to only their data. 
This way the multi vendor setting could flawlessly work together with the current reaction core version. What do you think?

**Comment by aaronjudd** [comment]
In https://github.com/reactioncommerce/reaction/issues/287 I was thinking that you'd need to be able to give the user in checkout the functionality to edit qty, group shipping methods, edit shipping , etc in a more detailed checkout review stage. This would be easier if the cart document was intact during checkout.  But I can see a lot of advantages to breaking the order up like this when we copyCartToOrder,  but I'd probably create the "suborders" as subdocuments of the order, rather than a copy, to maintain the order integrity.  Is that what you're doing?   Gladly take a pr.

**Comment by boboci9** [comment]
Righ now I keep the original order untouched so that it contains all the information and I have the suborders as standalone orders just to be sure that every seller will have access only to those orders which have their shopId, while the super admin of the main shop would have access to all orders. Do you consider any drawbacks for having these suborders as standalone documents?

**Comment by aaronjudd** [comment]
Closing for #798
