### ISSUE TITLE
Unlimited Quantity Option

### ISSUE THREAD

**Issue by faiizow** [reactioncommerce/reaction#161]
There are certain items that don't need a quantity value, i.e. digital products and maybe food.

**Comment by rymorgan** [comment]
We could also show a '∞' regardless I don't think this issue needs a design phase, moving it out of the design project.

**Comment by spencern** [comment]
Hey, we're going to leave the tag Pull Requests Encouraged and `needs-more-detail` on here, but we're going to close this issue because the requirements need to be defined better. If this is an issue that you would like to pursue, please create a new issue with more detail and more specific requirements and link to this old issue.
