### ISSUE TITLE
Heroku Deployment Issues

### ISSUE THREAD

**Issue by ch-luke** [reactioncommerce/reaction#1613]
### Background ###
- Using the latest vanilla app
- Only change made was to force the NPM moment package version to ("moment": "2.14.1")
- Using "heroku buildpacks:set https://github.com/swrdfish/meteor-buildpack-horse.git"
- Issues below only exist post deployment - things work fine on localhost install

### Issues ###
- Changing the language e.g. from English to German isn't responsive and you need to log out / page refresh etc to get it working properly
- Lang / data files don't all seem to import properly (e.g. adding an item to the cart displays "productDetail.addedToCart")

**Comment by zenweasel** [comment]
@chluke123 Which branch were you using? Could you retry this using the `development` branch?

**Comment by chluke123** [comment]
@zenweasel 0.17.1. Quickly also tried with 0.18.0 but the deploy process was throwing a ton of errors. Unfortunately due to lack of time I'm not able to do more checks.

**Comment by chluke123** [comment]
Referring back to 0.17.1. Another error - the Aldeed product / variant forms seem to be having lots of issues.

<img width="1238" alt="screen shot 2016-12-19 at 2 28 38 pm" src="https://cloud.githubusercontent.com/assets/20023331/21304726/be6a9328-c5f9-11e6-8972-54cbdaceb0ad.png">

**Comment by chluke123** [comment]
Been testing with the dev / 0.18 branch as well. Still getting the same issues. Also been running into this with some of my docker/digitalocean test deployments.

I don't know the root cause, but believe this is to do with mongo DB not properly being initialised on the first run. 

If I restore a mongo DB from one that I know works (e.g. previously created local meteor DB) to Mlab; then both Heroku and Digitialocean deployments work fine. Can only assume the DB was incomplete or corrupt some how which was causing issues.

Is would be nice if were built-in data sanity checks to help with this sort of thing.

**Comment by zenweasel** [comment]
We no longer support (and haven't for a while) deployment to Heroku. We just don't have the bandwidth to test/support it properly. If you have other issues not related to Heroku deployment please open them separately. Thanks!
