### ISSUE TITLE
Flickering images when mousing over secondary images

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1615]
### Expected behavior
Whatever image you mouse-over should be shown in the "hero" spot.

### Actual Behavior
Images flicker in and out of hero spot.

### Steps to Reproduce the Behavior
1. Add more than one image to a variant or option with irregular sizes (one tall and one wide)
1. Mouseover the secondary image
1. Observe that when the image is swapped in, your mouse is no longer over the image so then the image is swapped back, where it is now over the image and so on...

This gif doesn't quite capture it as it happens too fast but you can sort of see it.

![mouseover_image](https://cloud.githubusercontent.com/assets/72819/21085644/32039cae-c04f-11e6-9502-5d86268c85c8.gif)

**Comment by kieckhafer** [comment]
Related to #1444. Closing 1444 in favor of 1615 as there is a pictured example here.

From @EpifaniaCollection in 1444:

For bugs, please fill out the three following sections completely
### Expected behavior

When an product option has multiple images (e.g. 4), the small pictures should not change positions when clicked on them. In this case, all 4 thumbnails should should be shown, (not only 3), and when clicking on one of them it gets shown in the bigger view, without changing its position in the list of thumbnails.
### Actual Behavior

Out of 4 images, only 3 out of all 4 have thumbnails listed at any given time. Should one click a thumbnail of the 3 under the main view, the positions of the thumbnails is changed, making the user very confused: which picture did he see, and which not.
Moreover, when the mouse is moved, the pictures are swapped, adding to the confusion.
### Steps to Reproduce the Behavior

Add 4+ images to an option, try to view them.
