### ISSUE TITLE
Add audience permissions to package registry

### ISSUE THREAD

**Issue by lcampanis** [reactioncommerce/reaction#1622]
Add an additional `audience` permission check to the package registry, so that registry `provides` like `shortcut`, `userAccountDrodown`, etc are based on audience permissions. 

This will fix problems in a marketplace setup where menus can display different things depending on the loggedIn user role. See https://github.com/reactioncommerce/reaction/pull/1591#issuecomment-266615759

In the updated [Packages publication line 20](https://github.com/reactioncommerce/reaction/blob/release-0.18.0/server/publications/collections/packages.js#L20), should be checking doc.name (package name) permissions exist, seems like that needs to extended to look at the registry permissions object as well...

**Comment by lcampanis** [comment]
PR submitted for review: #1639 

- Added audience permissions to registry schema
- Reaction.Apps now checks audience permissions against loggedIn user roles and registry item audience (if any)
- Registry items can now use audience: ["guest","seller"] permissions, which are safely passed on the client for the UI to adjust based on any user/audience role
- Safely ignores audience permissions for owner

To test it easily just add `audience: ["guest"]` to any registry item containing a `provides: "shortcut"` and see the shortcut item in the menu for a guest user

**Comment by impactmass** [comment]
Hi @lcampanis

I started working on a permissions issue (#1651) which is related to your work on this issue.   

* The first part of the issue #1651 was that non-owner accounts get access to everything that can be managed in the admin dashboard (once they are given access to the dashboard)
* My work on the issue builds on what you've done in #1639, to ensure that an admin is able to selectively show items in settings/accounts section of the admin dashboard for non-admins.
* I currently have a WIP PR #2145 open to resolve this. If you can, please take a look.

PS: Is this issue still active? or should be closed since your PR #1639 has been merged?

**Comment by aaronjudd** [comment]
@impactmass as soon as your PR gets accepted into `development`, @spencern we'll update into `marketplace` so if you guys want to close this and move the work to #1651 that'd make sense to me.

**Comment by spencern** [comment]
Closing this in favor of group / audience based permission issues #2184 and #2185
