### ISSUE TITLE
Sidebar behavior fixes

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#1654]
What happens when you transition to a new page? Does the sidebar stay open, close, or show relevant information.

**Comment by mikemurray** [comment]
### Stay Open

If the sidebar stays open, then there needs to be at least some default view when it would be blank. Otherwise, every page needs to have some kind of sidebar panel.

### Close on route change

Sidebar closes when navigating away from the current page. 

e.g. 

- **Grid -> PDP**: closes, manually reopen if you want to see details for product
- **Grid -> Dashboard**: closes, manually reopen to view settings panel
- etc.

**Comment by rymorgan** [comment]
@aaronjudd and I discussed this last night in design review and the current thought is: The sidebar should stay open on page switch and show something (TBD) because that aligns with future goals for Reaction. In the near term, we'll come up with some default analytics to fall back to when the page has no relevant sidebar actions/settings. We'd also want to add a feature where you could pin a panel you are working on which keeps the current bug/feature where you can view panel information you are using now.

**Comment by kieckhafer** [comment]
PR #1706 is a first step in taming the behavior of the sidebar. #1706 makes changes to how the sidebar functions in the product grid view by saving selected products to the user preferences, and re-displaying selected products when returning to the grid view. If no products are selected, the sidebar will hide when the product grid view is accessed.
