### ISSUE TITLE
Tiered/Group Pricing + Media

### ISSUE THREAD

**Issue by dguedry** [reactioncommerce/reaction#1715]
Working on a Magento import plugin (https://github.com/dguedry/reaction-magento-import).  Are there any plans to implement tiered/group pricing?  We use this in our Magento stores for retail vs wholesale.  

I'd like to go ahead and start developing a "Group Price" plugin if it's not already slated.

Thanks!

Donnie

**Comment by aaronjudd** [comment]
In Reaction, variants, options, etc are all product documents, and all your images can be associated at any level, (so at the product) and as many as you want.  The association is in the image meta data, and right now the default view is just the first image is determined by the priority value in the meta data.  If you do associate to both products and variants, you'll need the ancestor array from the variants so that can retrieve all associated images from the Media collection.

**Comment by aaronjudd** [comment]
Regarding pricing, this can be done via the "Discounts" collection (which is likely to be renamed "Pricing" in the future, because that's the true intent).  We'll be adding conditionals soon, but what I think you are looking for is to return a price/rate as a conditional audience result, and that's what we're implementing there..

**Comment by dguedry** [comment]
The product grid picks the correct image if the image's metadata only contains productId (and variantId == null); however, the productImageGallery.js helper for media selects by variantId only.  So, if the product's variantId is not set, all images that have a variantId of null are returned to the product page (even though they don't have the correct productdId).

**Comment by kieckhafer** [comment]
I'm working through an issue (#1303) right now that seems to have a tie-in to this discussion. On the product grid, we only subscribe to Top Level products, no variants, meaning we can't use our `getVariants` method to find the ancestor ID's. In your case, for media, in my case, for Product Inventory numbers, which are determined by the Variants.

I'm currently working to add the Variants info into the grid page data, so ancestor info will be available.

I'm finishing up PR #1736 with this new data included.

**Comment by aaronjudd** [comment]
Feature request that requires more definition to meet our current issue guidelines.
