### ISSUE TITLE
Ghost accounts popping up

### ISSUE THREAD

**Issue by chluke123** [reactioncommerce/reaction#1814]
Need to brainstorm the following with you guys.

With regards to the accounts & user collections; I've noticed a lot of dummy accounts popping up (e.g. have no email or profile details). At first I thought it was connected to the "anonymous" checkout functionality, but I disabled that. Also all the forms have validation rules, so don't quite know how these are being created. 

Starting to wonder if this is some type of no-sql injection using postman etc.

Any ideas or suggestions?

Example entry below - 

/* 228 */
{
    "_id" : "4Rtsukk65Jwue7RWt",
    "createdAt" : ISODate("2017-02-08T14:29:33.867Z"),
    "emails" : [],
    "profile" : {},
    "userId" : "4Rtsukk65Jwue7RWt",
    "shopId" : "J8Bhq3uTtdgwZx3rz",
    "acceptsMarketing" : false,
    "state" : "new"
}

**Comment by jshimko** [comment]
Disabling guest checkout doesn't stop an anonymous account from being created when a new user hits your site.  Before a user is created in the UI, a user account is created under the hood so that anything they do before signing up can be tied to a specific user ID.  For example, when they add stuff to their cart before they go to checkout.  Since a cart requires a user, that's how this is accomplished before they've officially registered.  Once they register, the cart is tied to that new user.

**Comment by aaronjudd** [comment]
All visitors get an account, it's the roles that determine what that account views. There is not really any difference between a guest and registered user, other than their roles.

**Comment by aaronjudd** [comment]
Strangely, this is documented in [the cart workflow](https://docs.reactioncommerce.com/reaction-docs/master/reaction-cart) and not the more obvious accounts documentation.

**Comment by chluke123** [comment]
@jshimko cheers for the explanation.
