### ISSUE TITLE
Add media handling and storage options

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1815]
- Add settings to collectionFS to stream/store to S3. (and cdn)
- Update Media publication to return URL's instead of blobs, so the Media (all) subscription is more performant.
- Review default aspect ratios, and allow these to be changed in admin UI.
- perhaps review lambda service for generating responsive images

**Comment by mikemurray** [comment]
I think the Media publication is already returning the file metadata, and not a blob, as per the CFS documentation.

https://github.com/CollectionFS/Meteor-CollectionFS#security

> For a normal Meteor collection, "read" access is defined through pub/sub, but we don't want to send large amounts of binary file data to each client just because they subscribe to the file record. **Thus with CFS, pub/sub will get you the file's metadata on the client whereas an HTTP request to the GET URL is required to view or download the file itself.**

And considering the following asset url. Tested in a new browser / incognito, it still seems to work even when the Media subscription disabled.

```
http://localhost:3000/assets/files/Media/vuB8vReYpyYJvPnrh/pinkflamingo-side.jpg?token=eyJhdXRoVG9rZW4iOiJFVmtMdG9HYk1OZ0Vqdk5LOHJYQjdHRF9fRWNhNXhBSWg2b2NWMWMtbkVmIn0%3D&store=large
```

---

So then, is subscribing to and then loading lots of media through HTTP causing the slowdown itself and not the actual subscription?

Maybe allowing the assets to be stored on S3/CDN would ease this burden.

And still, subscribing to what could be thousands of file records, even if it's just metadata, could still be slow.

**Comment by loanlaux** [comment]
+1, would love to be able to store media on S3!

**Comment by curranabell** [comment]
@spencern @aaronjudd I was working on a plugin that would replace collectionFS with meteor slingshot but got pretty distracted with other projects and wanted to wait until the replace component api was finished. Meteor slingshot is nice because it sends it directly to S3 or other cloud storage without going through the server and putting an unnecessary load on it. https://atmospherejs.com/edgee/slingshot

**Comment by jshimko** [comment]
There are npm packages that do the same thing and aren't Meteor-specific.  And I'm not sure that Slingshot is even still maintained.  I absolutely agree that we need more flexible options, but we may need to write our own (or pull someone else's code in) because we definitely don't want to replace one abandoned package with another.

**Comment by jshimko** [comment]
This is Meteor-specific, but it's actively maintained.  https://github.com/VeliovGroup/Meteor-Files

The biggest complaint I have there is that it's a mess of Meteor-style globals and comes with few other dependencies we don't want/need (coffeescript, etc).  But it's possibly a good starting point for putting together our own solution that isn't dependent on the the database for binary file storage.

**Comment by curranabell** [comment]
Ahh very very true. Maybe we could just pull some of the code from Meteor slingshot because it still works great with react and react dropzone then package it up in our own plugin. @jshimko

**Comment by curranabell** [comment]
Meteor files seems like it is forsure the way to go. Solid. I already got the front end of a media uploader plugin built that allows the user to choose his s3 storage location, bucket name, input api key, and secret key just didn't get any backend stuff going as I wasn't sure what direction you all were thinking of going with the media uploader.

https://github.com/curranabell/reaction-slingshot/blob/slingshot/client/components/mediaCloudSettings.js

**Comment by aaronjudd** [comment]
`dependent on the the database for binary file storage.` and works ephemerally out of the box without signing up for a 3rd party solution?

That has been one of my primary requirements, and I'm not sure how you can get that without DB based file storage (which in a really high traffic situation could be on their own shard). -> I think that this should be at least available as a backup option (configuration option maybe).  Doesn't mean images can't be synced and served to an alternate source (and they should be), but from experience -> those services also fail.
I also would strongly object to adding any new Meteor packages at this point but would be open to a strategy that involved porting such an existing package to an npm package. We are on a mission to remove all Meteor dependencies long term.

**Comment by jshimko** [comment]
Oh yeah, I definitely didn't mean that I think we shouldn't have the DB option.  That's extremely useful/convenient.  Requiring people to use a non-free third party destination for images would obviously not be better.  I just meant that we need it to not be the _only_ option.  Which is essentially the same thing you said... default storage comes for free with the DB as always and then the same API can be used for higher performance options like storage services, CDN's, etc.

And yeah, definitely no Meteor.  There's nothing inherently useful about an image management solution that only works as a Meteor package.  I think the only reason any of those are packaged up as Meteor-only packages is because they all try to include prebuilt UI stuff as well.  I don't think an image storage plugin needs to make assumptions about UI implementations.  At the very least, any client functionality should be in its own package so that it's optional.

**Comment by aaronjudd** [comment]
@spencern and I were just discussing, and we've all settled that ripping out CFS is the way to go..

replacement should:

- can upload to file system rather than gridfs
- should optionally sync to S3, if credentials are supplied
- should retain compatibility, by re-using the Media collection
- can use the Sharp library for image resizing
- should retain current helpers, or provide upgrade path

**Comment by loanlaux** [comment]
Great decision! I'm glad you guys made this choice.

**Comment by aldeed** [comment]
I did some looking at the current state of uploads and reminding myself about how CFS works. While I agree that we should move off of the CFS Meteor packages, you are pretty much going to rebuild several of the CFS packages to do this. So rather than "ripping it out" per se, I'd recommend basically a copy-paste of CFS into new NPM packages, passing in the Meteor dependencies as necessary. This could be some open source CFS replacement if you want, or just a plugin specific to Reaction.

Having worked on CFS for awhile, I know there are a lot of tricky things already figured out there, so it's better to start from there rather than from scratch.

- CFS already has a filesystem upload storage adapter you can grab
- CFS has an S3 storage adapter and a partially finished S3-client adapter you can grab. The client adapter would be best. The idea there is that the Reaction server will generate one-time upload or download URLs, and then the client can upload directly to S3, greatly reducing the strain on the Reaction server. I don't remember if we ever had that working perfectly, but it shouldn't take much to get it done.
- `gm` is not a dependency of CFS, so you could switch to using Sharp in your file workers right now, even before getting rid of CFS

I don't think the gm -> sharp task (#3482) is blocked by this or blocks this. The image manipulation code would be the same even if it eventually gets moved around.

I can work on this or provide guidance to whomever does.

**Comment by aldeed** [comment]
Closing this. I will track all of this as part of https://github.com/reactioncommerce/reaction/issues/1221 and create followup tickets for the remaining needed enhancements after the initial port of the current behavior is done.
