### ISSUE TITLE
Product Title is required error on new products.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1887]
Warning on PDP. 
![ugpjenviupkdjk8uv](https://cloud.githubusercontent.com/assets/439959/23243257/8b8fbcfa-f932-11e6-8193-00f6a36f61d6.png)

Perhaps related to #1605.  Doesn't however seem to cause the product to be un-editable.

To replicate, add new product, click to edit, view console. 

```
Error invoking Method 'products/updateProductField': Product Title is required [400]
```

**Comment by impactmass** [comment]
Hi @aaronjudd 

To confirm what needs to happen with the issue mentioned here: 

Is this the preferred behavior: 
* When editing a product, and the title is empty, on clicking "publish" an error message should be shown and the edit not saved?
[that's what happens when trying to create a new product without a title]

**Comment by aaronjudd** [comment]
@mikemurray says this is fixed in his branch.

**Comment by kieckhafer** [comment]
Related to #1648
