### ISSUE TITLE
Required human resources?

### ISSUE THREAD

**Issue by danielgindi** [reactioncommerce/reaction#189]
Hello friends!

I was wondering if anyone has a "big plan" of what is going to be done next, what needs to be done, and what kind of people we need for it.
I lately discussed Reaction with some friends, and there seems to be interest in it by different people, not all of them are programmers. Take for example a UX guy, or someone with *huge* experience with Google Analytics.
If we could use them - they will be happy to join in.

Is anyone able to outline what/who we need?
This could be a great starting point for anyone else looking to give a hand.

**Comment by aaronjudd** [comment]
Here's the plan:

For a visual representation in kanban style: https://waffle.io/reactioncommerce/reaction

I've organized milestones into "Development Tracks". https://github.com/reactioncommerce/reaction/milestones/

I've changed the default branch for reaction, reaction-core to `development`.  We'll now accept all pull requests directly into the development branch, while we work on specific feature branches separately.

We can also start liberally creating issues for every feature/task, rather than just 'community' issues. This will be much noisier but ensure we're publicly capturing all the tasks. I've been bad about creating issues for things that I'm working on, so this should help everyone have insight to what's really going on.

I've created a "help wanted" label, to call out issues that prioritize where community member contributions would be relatively easy.  Of course, all contributions are welcome. 

The "ready" label indicates items that can be worked on.  Self assign and move to "in progress" label when the item is actually being worked on.

We'll start merging and releasing development into master whenever an item is marked done, and a PR has been submitted to `development`. @aldeed We can start continuous deployment (so version numbers will start escalating quickly, if we start properly using semver).  There will be a minor pause for testing, but hopefully we get tests written for everything over the next couple of releases and can automate somewhat. (that should get better over time).  I'll tag specific releases, so master won't always be a 'tagged' release (just that master=stable).

I'm going to close this issue, but feel free to keep commenting (or reopen if this is all wrong!)

**Comment by danielgindi** [comment]
That's actually great and beautifully arranged!

נשלח מה-iPhone שלי

‫ב-19 בינו׳ 2015, בשעה 21:20, ‏‏Aaron Judd ‏<notifications@github.com> כתב/ה:‬

**Comment by aldeed** [comment]
@aaronjudd, I like the plan. Maybe you can put a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) file in each package repo that has the same text as your post?

**Comment by aaronjudd** [comment]
Good idea. I did edit the "guidelines.md", but it's probably appropriate to have a specific contributing.md
