### ISSUE TITLE
Need environment variable option for Reaction Registry import

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/reaction#1917]
We need a way to import Reaction Registry settings (`reaction.json`) in environment variable form.  The current thinking is that it would function similarly to Meteor settings (`METEOR_SETTINGS`) so you can either use the `reaction.json` file or simply set the `REACTION_REGISTRY` variable (or whatever we call it).  

This obviously would allow code bases to remain stateless and not rely on the `reaction.json` file.  A Docker instance could then be completely configured via variables instead of requiring a `reaction.json` to be built in.  This will also likely be tied to `reaction-cli`.

Discussion, go...

**Comment by aaronjudd** [comment]
If we just accepted reaction.json as an env variable, similar to Meteor settings, I think that'd be ideal, but to take it a step further, move this from /private/data/ into .reaction/config at an app/environment level could also make a lot of sense and would be easier to work with I think, so that when you did 'reaction deploy' it'd push the appropriate settings as well.
