### ISSUE TITLE
Pagination for orders

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1921]
Goal should be that orders should perform faster, if pagination (and optional, filters) for orders implemented. Pagination and limit order for order publishing. 

The orders subscribe to accounts as well, not sure if this is done client, if so, move/re-arch to server, normalize the order in the publication.

**Comment by kieckhafer** [comment]
Possibly able to use Griddle 1.0 #1894

**Comment by zenweasel** [comment]
According to @kieckhafer we shouldn't convert to the new griddle yet as it's not ready for prime time, so let's move forward without it.

**Comment by mikemurray** [comment]
Since Griddle 1.0 is not ready for use because of missing documentation, lets skip that for now.

For now, do the pagination the old fashioned way; using the Orders publication, and setting page / num items and filtering by the tab its on.  Most of that code is on the client side in the orders template. You could probably move that to the server-side in the publication.

Also. The counts for each order tab will need to use meteor publish counts. ( we should already have it installed, and being use )
https://github.com/percolatestudio/publish-counts

the counts need to be redone because not the Orders publication fetches all orders to do the counts, but if you do pagination, those counts will not reflect the actual totals.

---

**Summary**

- Don't worry about griddle for now
- Do the pagination / filtering with `Orders` publication
- Pagination can be as simple as a (Show More) button that just expands the range of Orders found
- Use `Counts.publish` to get correct numbers for the Orders tabs

**Comment by kieha** [comment]
On this task, there are two segments of code that have this logic; there's a react components and there's Blaze templates, and they more or less do the same thing. Which one should I edit/use?

**Comment by zenweasel** [comment]
We should always take every opportunity to deprecate Blaze templates and replace with React where we can.

**Comment by kieha** [comment]
In implementing this ticket, I've decided to go the `show more` button way. My question on this would be, if I initially display 100 records and have the show more button, when the button is clicked, would it bring the rest of the records from the database? Or is it the next 100 records, and the button persists?

**Comment by aaronjudd** [comment]
Why not auto pagination (infinite scroll?)

**Comment by aaronjudd** [comment]
why do you need a button? ;-)

**Comment by mikemurray** [comment]
Infinite scroll gives me anxiety :) "Is this list ever going to end, whats going on?" - lol

**Comment by kieha** [comment]
@aaronjudd I thought about infinite scroll, but I thought that it would be a bit annoying for the user not to actually know if the records are over.

**Comment by kieha** [comment]
Looking at the `publish-counts` package, the description is that it should be used for a relatively small number of documents. And seeing as we still need to subscribe to the orders publication on the client side, I think it kind of beats the whole purpose of increasing performance by not subscribing to all the orders at once.

**Comment by kieha** [comment]
Fixed by #2036
