### ISSUE TITLE
Spiderable / SEO installation on Docker

### ISSUE THREAD

**Issue by mateomorrison** [reactioncommerce/reaction#1965]
Is there any way to modify the Index like in HTML to add meta tags. Since I see Reaction Commerce is not SEO Friendly.

When I google my website it looks like this:
![screen shot 2017-03-12 at 2 37 12 pm](https://cloud.githubusercontent.com/assets/24979743/23834724/8c295bf0-0731-11e7-9dd8-f3962dbae103.png)

- No title
- No description

# Spiderable

How to install `spiderable` on a Docker Container? (Where I'm running my Reaction Commerce)

**Comment by zenweasel** [comment]
This is really a Docker question rather than an RC question, but I believe `docker exec` is what you would want to execute the `meteor add` command on your container. Or just modify your `packages` file in the `.meteor` directory and restart.

In additional to Spiderable you may also want to look into [prerender.io](https://docs.reactioncommerce.com/reaction-docs/master/prerender)
