### ISSUE TITLE
Problem with scrolls.

### ISSUE THREAD

**Issue by dshitik** [reactioncommerce/reaction#2000]
When moving between routes, the status of the scroll bar is maintained.
For example, go to the main page, scroll down, and then go to the profile page.
Do you need a more detailed explanation?

**Comment by zenweasel** [comment]
Yes, a more detailed explanation would be helpful. In the future it would be great if you could fill out the issue template. It helps us understand your issue much better and faster without having to go back and forth with a lot of questions. In this particular case I need to understand the difference between what you expected to happen and what actually happened. Thanks!

### Expected behavior

### Actual Behavior

### Steps to Reproduce the Behavior

**Comment by aaronjudd** [comment]
Needs some more details..  (what about sidebar behaviour,etc)..  this sounds like a side affect of being a single page app, but we can control those positions..
