### ISSUE TITLE
Price shows as $0.00 in product grid when adding a product with just one option

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2026]
### Expected behavior
If you add one option with a price of $12, the price in the product grid should be $12

### Actual Behavior
Price shows as $0.00

### Steps to Reproduce the Behavior
1. Change branch to `master`
1. `reaction reset`
1. Login as admin
1. Create a new product, fill in description etc
1. Add one option
1. Publish
1. Observe price displays as $0.00 in the product grid

![dumb_product](https://cloud.githubusercontent.com/assets/72819/24189356/9636a904-0f1f-11e7-94f8-c1f9c623d349.png)

![reaction](https://cloud.githubusercontent.com/assets/72819/24189367/a16b0d38-0f1f-11e7-8489-8002365bd2f0.png)

**Comment by hrath2015** [comment]
This is happening because  Product Revision is not available on server.  This API is supposed to work on client where expected Revision is embeded in Published data. 
https://github.com/reactioncommerce/reaction/blob/development/server/methods/catalog.js#L185
https://github.com/reactioncommerce/reaction/blob/development/server/methods/catalog.js#L187
https://github.com/reactioncommerce/reaction/blob/development/server/methods/catalog.js#L207

What we are doing in here:
https://github.com/reactioncommerce/reaction/blob/development/imports/plugins/core/revisions/server/hooks.js#L21
 needs to be done in `denormalize()` method.

If nobody is working on it please let me know, I have already made some changes to fix it. Will send it for review.
