### ISSUE TITLE
English disappears from language selector

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2083]
### Expected behavior
When English is enabled it should always appear in dropdown

### Actual Behavior
English disappears from dropdown

### Steps to Reproduce the Behavior
1. Login as admin
1. Select "All off" under Languages (English remains enabled)
1. Enable a few other languages
1. View dropdown and observe that English is missing
![reaction](https://cloud.githubusercontent.com/assets/72819/24699421/8406caf4-1a26-11e7-9f59-d10f0a4d536c.png)

**Comment by hrath2015** [comment]
I tested it and not able to reproduce.  After following the steps clicked on dropdown and english is available as last option to select:
![image](https://cloud.githubusercontent.com/assets/14071646/24712835/99bd933a-1a41-11e7-85d1-cc5744fae3ab.png)

However, if you change it to anything else it will disappear because shop currency is changed.

**Comment by zenweasel** [comment]
@hrath2015 That's the wrong dropdown. I mean the language dropdown on the customer side.

**Comment by hrath2015** [comment]
@zenweasel  sorry. completely missed that you were referring to header dropdown.

**Comment by zenweasel** [comment]
No worries, the screenshot is a little confusing now that I look at it.

**Comment by kieckhafer** [comment]
Seems like it's not specifically English that isn't showing up, it's whatever the shop's default language is.

**Comment by zenweasel** [comment]
Closed via #2148
