### ISSUE TITLE
[Avalara] Allow addresses that don't validate

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2104]
Customers should be warned but not blocked from entering addresses that don't completely validate.

Waiting for clarification on whether this means City/State/Zip don't validate or entire address.

**Comment by zenweasel** [comment]
So Avalara may still throw an error if City/State/Zip don't validate when we do the "Estimate Cart" call (which will happen after a shipping method is applied(). So we need to handle that error if throw and push the customer back to the address workflow.

**Comment by zenweasel** [comment]
I have it allowing the user to pass through validation after receiving the first set of corrections/warnings. And it's throwing the user back to the `addressBook` when their is an address error from the API but it's not in edit mode and there are no messages that will tell the user what is wrong with their address (the Avalara API also does a terrible job of providing meaningful feedback in their address validation API).

Also debating on whether I want to dig myself a deeper hole by trying to build out a better UI for address validation. I already built code to parse out the data given to me by Avalara into meaningful messages but not currently using it.

Not to mention this needs to get converted to React and currently it's just basically a single line of Autoform. So you know, 😢

**Comment by zenweasel** [comment]
I have a basic "review validated address" flow built although the form is still super ugly. It's essentially a "resolve diffs" for address because I have no imagination.

![address_review](https://cloud.githubusercontent.com/assets/72819/25268204/682ab15c-26aa-11e7-8bab-98e31bf723f4.gif)

**Comment by zenweasel** [comment]
@rymorgan Could you take a look at this and give me your thoughts? The thing that concerns me is that for customers that have Avalara enabled this will come up quite a bit because your address only has to differ in spelling or punctuation and it's going to kick it back. I _think_ this works but maybe there is a better way. 

I've cleaned up the styling a little bit, but the flow is still basically the same as the above.

**Comment by zenweasel** [comment]
pinging @rymorgan again. If you could just take a second I would appreciate it.

**Comment by rymorgan** [comment]
![validation](https://cloud.githubusercontent.com/assets/20409254/26020842/aa0be534-3738-11e7-85ba-9a2f63dcb512.png)

My thinking is we add a notification at the top letting them know what is going on (aka fields should be validated.) 

1. All fields needing to be validated are highlighted with the faded danger color
2. When you roll it fades indicated you can take an action
3. onClick the field is corrected and you get a validated check and the bg color turns the faded green. 
4. Or since you don't have to validated you can ignore which will just return the BG to white. 
5. For now, you can use ugly notification colors we have now and we'll correct those globally.

**Comment by rymorgan** [comment]
@zenweasel Is this done? I'd love to see the execution.

**Comment by zenweasel** [comment]
Closed via #2162
