### ISSUE TITLE
[development] Configured payment methods not displaying

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2231]
In 1.2 `development` I am seeing that payments are not visible to guest although methods are configured.

![basic_reaction_product_and_cart_checkout_and_reactioncommerce_reaction](https://cloud.githubusercontent.com/assets/439959/25870673/c90ecb4e-34b9-11e7-9988-2984b7f50451.png)

Possibly related to #2145 @impactmass investigating.

**Comment by hrath2015** [comment]
This is caused  due to mismatch in permissions, which was added  here
https://github.com/reactioncommerce/reaction/blob/development/server/publications/collections/packages.js#L39-L42
Permissions are now part of registry published for a shop.   
When a Guest User checking out... empty array is returned by 
`const apps = Reaction.Apps({
    provides: "paymentMethod",
    enabled: true
  }) `

Published permissions doesnot contain any roles from 
"defaultVisitorRole": [
    "anonymous",
    "guest",
    "product",
    "tag",
    "index",
    "cart/checkout",
    "cart/completed"
  ]
Hope this helps

**Comment by impactmass** [comment]
thanks @hrath2015 ...
when a guest user is going through checkout, an empty array is returned as you said, and that's because of the audience field explicitly set here
https://github.com/reactioncommerce/reaction/blob/development/client/modules/core/helpers/apps.js#L65

I'm currently testing the solution in the WIP PR referenced above. That should resolve it..... testing to ensure that's the case

**Comment by zenweasel** [comment]
Closed via #2235
