### ISSUE TITLE
Document, test, and identify issues that happen when shipping methods change while checking out

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2232]
When shipping methods change, the current active cart should reload.  This is likely to be the shop admin/owner configuring the site. This should probably only be the current users cart, as methods that would update global the carts probably require a more complex solution, and I'm not sure that's really needed.

**Comment by aldeed** [comment]
As of 2.0, I do not believe this is necessary. Order creation loads the latest shipping methods, and if they have changed in a way that affects price or have become disabled / unavailable for that order, I believe order creation will fail. This can then cause the client to refresh its data.

I will leave this open, though, because we should document the proper behavior here, as well as ensuring that the storefront UI is handling such errors in a smart way.
