### ISSUE TITLE
No shipping methods are configured. Configure now.

### ISSUE THREAD

**Issue by vanloc0301** [reactioncommerce/reaction#2265]
I using Reaction. When I tried to at step check out Product.

I can't complete at step: `Select Shipping Option`.
![screenshot_2017-05-15_18-21-25](https://cloud.githubusercontent.com/assets/4168981/26055530/8519e266-399b-11e7-8bbe-23ebe4f2c095.png)

I enabled `Fat Rate` optional.

**Comment by zenweasel** [comment]
If you edit and save, or delete and readd the address, the shipping methods will show and show for all further checkouts.

**Comment by vanloc0301** [comment]
Thanks. It's working.
Can you explain why do this the shipping option is enabled?

**Comment by zenweasel** [comment]
The shipping address is not reactive to the shipping configuration being changed. This only affects the very first checkout for an admin when configuring the shipping methods. You only have to do this once. There is already issue #2232 to change it to be reactive.

**Comment by aaronjudd** [comment]
Re-opening this issue as it's reproducible, almost always on the second purchase in the same session, but after a completed order. All current branches.
```
Node: 6.11.1
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 2.0.0
Reaction branch: npm-manifests
Docker: 17.06.0-ce
```

**Comment by aaronjudd** [comment]
![cart_checkout](https://user-images.githubusercontent.com/439959/29094702-1ce5c18e-7c43-11e7-9c87-7d72f69a162a.png)

I have placed an order previously, successfully, but cannot with this user.

**Comment by zenweasel** [comment]
I can't replicate this on `development` using the following steps:

1. Login as admin
1. Place something in the cart and go to checkout
1. Enter address
1. Get "No shipping methods configured"
1. Enable one flat rate method (and enable payment, via Braintree for me)
1. Hit edit address and resave
1. Complete checkout
1. Place another item in cart
1. Checkout as normal and receive no errors

**Comment by zenweasel** [comment]
Can't replicate on `marketplace` either using steps above

**Comment by spencern** [comment]
@zenweasel Try checking out as anon in incognito window in place of step 2.

**Comment by zenweasel** [comment]
@spencern How does that work then? Do I login as admin after I hit the "No Shipping Methods" or?

**Comment by zenweasel** [comment]
Cannot replicate using anonymous user either

**Comment by spencern** [comment]
Hmm.. I just tried on marketplace as well and was unable to repro
(used Auth.net as payment gateway)

**Comment by zenweasel** [comment]
I 100% believe this bug is real, but it's just about narrowing in on exactly the settings. Or like @aaronjudd said, maybe related to a Shippo thing.

**Comment by zenweasel** [comment]
I just saw this now. Of course not in any way that I could give you steps to reproduce (was testing something else)

**Comment by zenweasel** [comment]
FWIW I did have Shippo enabled and I was switching payment processors

**Comment by foladipo** [comment]
I have also not been able to reproduce this bug. As @zenweasel said above, tried to repro while having Shippo enabled, but no luck. I also tried to checkout as an anonymous user in an incognito tab of Google Chrome, but that failed too.

@aaronjudd and @spencern Perhaps you could provide the complete steps that produce the bug on your own end?

**Comment by foladipo** [comment]
### Update
So the only error/bug that I've been able to get so far works occurs as follows:
1. Enable Shippo as the only shipping methods provider.
1.
    - Open Reaction in an incognito window as an anonymous/unregistered user.
    - Add an item to my cart.
    - Fill in an address at checkout and save it.
    - On saving the address, the shipping methods provided by Shippo show up correctly.
    - Complete the order.
1. Start another purchase as in step 2 above, but whenever I reach the checkout page, I need to 
quickly scroll to the shipping methods section. If fast enough, I do see this error:

<img width="527" alt="screen shot 2017-08-22 at 1 51 21 pm" src="https://user-images.githubusercontent.com/26963575/29566703-a37a1cb8-8742-11e7-96bf-c7957cfadd96.png">

 The problem is, the error is almost always momentary and eventually gets replaced by a correct list of shipping methods.

The error only ever stayed put *once*. On that occasion, I found the following in my terminal:
<img width="1261" alt="screen shot 2017-08-22 at 2 08 05 pm" src="https://user-images.githubusercontent.com/26963575/29566889-5ee71ece-8743-11e7-9bdf-d8f68ed51d0c.png">

That seems to me to be have occurred while RC was calling the Braintree API, which failed due to my internet connection at the time. And given the fact that other instances always get corrected, I think it was my connection.

So a solution that I can propose is that we add a `Loading... Please wait...` section to the shipping methods section.

cc @zenweasel @aaronjudd @spencern

**Comment by prosf** [comment]
I have seen this happening sometimes, too.
In our case the reason was that although the Shippo’s shipment.create-response had returned
object_status=“Success” and object_state=“valid” ,the corresponding Shippo's request to the(only available) Carrier api had Timed-out so the rates_list array
was empty and something like “Carrier’s Api Timed-out” was added in the messages array.

So maybe a retrying logic (e.g three times) should be implemented in ShippoApi.methods.createShipment (or the method that calls it).
Or simply check if the messages array is not empty. Just a thought.

**Comment by zenweasel** [comment]
@foladipo It's almost as if we should do this 🤔  https://github.com/reactioncommerce/reaction/issues/1872

**Comment by foladipo** [comment]
@zenweasel @prosf Thanks a lot, your comments have been helpful. So, how I'm going to handle the scenario above is as follows:

I'll add a spinner or "Loading... Please wait..." element to the shipping methods section that will be shown while Shippo's API is queried. If the query succeeds and returns a list of shipping methods, those methods will be displayed. If not, the query will be tried again once or twice. If these multiple queries all fail, then an error message will be displayed to the user (with a call to action to check their internet connection or some other appropriate action).

**Comment by spencern** [comment]
@foladipo @zenweasel Is this bug still present?

**Comment by foladipo** [comment]
Yes it does. If you want to reproduce it, you may follow the steps in the first post or the updated steps I posted.

**Comment by spencern** [comment]
@foladipo are you still working on solving it? Any updates?

**Comment by foladipo** [comment]
Yes I'm working on it. In fact, the PR I put up to solve it has been verified by @zenweasel  to work. All that's left is some final reviewing and general testing, which I'd like you to please help us do. The PR is [here](https://github.com/reactioncommerce/reaction/pull/2738).
