### ISSUE TITLE
Troubles opening side panel / PDP page on grid at some breakpoints as admin

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2270]
### Expected behavior

Double clicking on product grid item should open product, at any breakpoint, in admin edit mode.

### Actual Behavior

Double clicking on product grid item open panel and immediately closes on table width (949px) and less.

### Steps to Reproduce the Behavior

Double click on item in grid with a viewport smaller than `949px`.

### Versions

Node: 7.2.0
NPM: 4.0.5
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.1.1
Reaction branch: development
Docker: 17.03.1-ce

**Comment by rymorgan** [comment]
@abdulsemiu-atanda I'm not sure what design direction you want on this issue? If you multi-tap on an item on the product grid while in edit mode you should go directly to the product. 

It does bring up a related issue that we need a way for multiple select of items on the grid for mobile.

**Comment by abdulsemiu-atanda** [comment]
@rymorgan I was thinking disabling `Grid Settings` overlay in mobile might be breaking the design we already have but #2315 fixes the multi-tap situation.

**Comment by rymorgan** [comment]
@abdulsemiu-atanda We need to give this behavior more thought. Grab another issue while we figure out what the behavior should be between mobile and desktop.

**Comment by aaronjudd** [comment]
@abdulsemiu-atanda @rymorgan should remove @abdulsemiu-atanda from the assignee, or add @rymorgan (or whoever is answering the behavior questions) to the assignees.

**Comment by rymorgan** [comment]
After discussing this with @mikemurray and @kieckhafer -- I'm reclassifying this as part of thinking about the mobile experience instead of it being a bug. Double clicking isn't a normal mobile behavior for mobile. It does bring a up a few issues though with regards to mobile. As in, how do you select and edit multiple products on the grid? on mobile? Is there a way to get to the product detail page when you are in edit mode w/out clicking twice or is ok to have the user click twice on mobile?

**Comment by zenweasel** [comment]
@rymorgan If this is not a bug, are we acting on it? This seems like a straight-ahead bug that doesn't seem to have anything necessarily to do with mobile?

**Comment by aldeed** [comment]
Verified still an issue on 2.0.0-rc.1

**Comment by kieckhafer** [comment]
This is no longer relevant with Operator 2.0.
