### ISSUE TITLE
Format currency as currency in all components.

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2286]
### Expected behavior
All currency amounts should be formatted as currency

### Actual Behavior
For example here, "Price" is formatted as currency but MSRP is not. There may be others that I won't write separate issues for.
![dumb_product](https://cloud.githubusercontent.com/assets/72819/26132420/c47f8694-3ad2-11e7-8fe9-888ae2190ddf.png)

### Steps to Reproduce the Behavior
1. Create a product
1. For a variant enter a price and an MSRP
1. Observe the price is formatted as currency but the MSRP is not

### Versions
```
Node: 7.10.0
NPM: 4.2.0
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.2
Reaction: 1.2.0
Reaction branch: release-1.2.0
Docker: 17.03.1-ce
```

**Comment by Akarshit** [comment]
This issue still exists in `release-1.8.0` as can be seen in screenshot below(the "Price" field is not formatted).

<img width="405" alt="screen shot 2018-02-09 at 1 19 19 pm" src="https://user-images.githubusercontent.com/7762605/36017109-4f06edd8-0d9c-11e8-97cd-1fabd9cfc6c7.png">

**Comment by Akarshit** [comment]
@spencern
Making the `TextInput` currency formatted is not trivial. Basically the solution is that while displaying I have to `format` the `props.value` and while sending back the changed value, I have to `deformat` it. But it break when the user wants to enter something like 1.5, as soon as the user enters `1.` because of the `deformat` and `format` cycle it changes to `1` so user is not able to enter values with decimal.
Apart from this the UX is not good when the input is formatted as currency. Also this is for the admin side and on that side we always assume that the admin is aware of the units that's why we don't display units of anything anywhere. To be in sync of this, I have made a PR to remove the currency formatting from the placeholder value. 
Does this sound OK to you?

**Comment by spencern** [comment]
I don't love this solution as the placeholder text is one of the better indications that the user is inputting a currency amount. I do acknowledge your concerns that it's a poor UX when the input is formatted as currency. I think the goal here is that when the user is inputting, it's a number and when they are done inputting, the display is shown as currency (text field?). I can think of several ways to accomplish this, so I'd prefer to keep the currency formatting in the placeholder.

**Comment by zenweasel** [comment]
@Akarshit Since @spencern moved this into the Sprint, I am removing your assignment

**Comment by zenweasel** [comment]
@Akarshit Wait, nevermind
