### ISSUE TITLE
Shipments fulfilled via Shippo should subscribe to tracking webhook

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2318]
Shipments that have been fulfilled via Shippo integration should subscribe to tracking updates for that order.

Once a Shippo order has been created, we should programmatically subscribe to shipping notifications for that tracking number, or multiple tracking numbers in the case of an order with multiple shipments.

#### Resources
*   [Shippo tracking webhook docs](https://goshippo.com/docs/webhooks)

**Comment by prinzdezibel** [comment]
I've done some research on this topic which resulted in the following insights:

- Reaction does already track the order status for shippo carriers properly
- Albeit it's done through a polling approach via Job collection
- Shippo webhooks are difficult to verify, as they don't put a hash in the request headers
- To have some rudimentary way of ensuring the authenticity of the sender, I've been thinking of maintaining Shippo's IP address in the plugin's settings.
- Settings forms are done using deprecated Blaze / Autoform functionality, which I hesitated to use for my intentions, because I didn't want to add additional technical debt.


After talking to Brent we've decided to icebox it for now.

**Comment by zenweasel** [comment]
Won't fix. Shippo no longer part of core package.
