### ISSUE TITLE
Updating i18n translations in production db

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#237]
I don't understand how crearly to update i18n translations on production after some fixes in json i18n files. Locally I always can do 
```
meteor reset 
```
It's not really way I like to do this, but anyway I don't want to clear all my data on production only for reloading translations into db.
What is the reason to store translations in db? AFAIK json files can be accessed via HTTP by i18next library.

**Comment by aaronjudd** [comment]
You can just delete the translation collection and it will restore from the fixture data.  The fixtures.coffee file just checks if the collection exists and has records.  
The reason that the data is stored in the db is we'll be adding admin screens for editing and maintaining the entries in the future.

**Comment by ramusus** [comment]
Yep! I come to this solution while deep sleeping few hours ago :)
But it seems deploy is required after, so procedure now is:

development 

```
$ meteor mongo
> db.Translations.remove({});
```

production

```
$ meteor mongo XXX.meteor.com
> db.Translations.remove({});
$ meteor deploy XXX.meteor.com
```
May be add this recipe to i18n documentation? It tooks few hours for me to understand this background mechanic.

Why in admin interface we can not use translations files via HTTP ?

**Comment by aaronjudd** [comment]
It would be pretty easy to add the forms for editing, or a file upload as well (or a remote url).  I figured if I didn't add this functionality right away, we'd get more pull requests with language file updates - rather than folks just fixing their own site files.  However, I'd be happy to take a pull request for tools to manage the translations.  At the very least, I guess we could add a method to clear the collection and reload the translations files without  restarting meteor (which is what `meteor deploy` is doing). Our fixtures.coffee only runs on startup, so you just need a way to remove the collection records and retrigger the `loadI18n` from the client.

**Comment by ramusus** [comment]
Aaa, now I understood you mean admin interface for editing translations.. That make sense.

Yes, method or shell command for flushing translations on production would be very helpful. I think the best way to do it now hook this somehow and execute automatically after every deploy.

But in case of admin interface for translations, db will became superior over json files and mechanic should be different.

**Comment by aaronjudd** [comment]
`Meteor.call("flushTranslations");` when logged in as admin, can execute from browser console.
