### ISSUE TITLE
Error when updating the repo with "reaction pull": Unsupported platform for fsevents@1.1.1

### ISSUE THREAD

**Issue by kainio** [reactioncommerce/reaction#2456]
### Expected behavior
Update reaction commerce with reaction pull from version 1.2.0 to version 1.3.0-rc.1
### Actual Behavior
Error on installing node modules
### Steps to Reproduce the Behavior
in version 1.2.0 make a "reaction pull" in the repo
### Versions
(run `reaction -v` from your reaction directory)
Node: 7.4.0
NPM: 4.0.5
Meteor Node: 4.6.2
Meteor NPM: 3.10.9
Reaction CLI: 0.9.3
Reaction: 1.2.0
Reaction branch: master
OS: lubuntu 15.04 32bit

### Here is the error
Installing Node modules...
npm ERR! Linux 3.19.0-84-generic
npm ERR! argv "/home/soufiane/.meteor/packages/meteor-tool/.1.4.2_3.mea2r9++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node" "/home/soufiane/.meteor/packages/meteor-tool/.1.4.2_3.mea2r9++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: ia32

**Comment by jshimko** [comment]
You're already on the current latest stable release (1.2.0).  The version checker in `reaction-cli` has just been updated to ignore release candidates.  1.3.0 won't be the official stable release until it's merged into the master branch (which is why your `reaction pull` didn't work).  Once you update `reaction-cli` to v0.10.0+, the update notification should go away.  Sorry for the confusion.
