### ISSUE TITLE
How to update reaction?

### ISSUE THREAD

**Issue by vanloc0301** [reactioncommerce/reaction#2457]
I want to update reaction to latest version.

```A newer version of Reaction exists on Github.

Current version: 1.2.0
Available version: 1.3.0-rc.1

To update, run: reaction pull
```

I tried to run the command: `reaction pull` but `Reaction` still at version: 1.2.0.

**Comment by jshimko** [comment]
You're already on the current latest stable release (1.2.0).  The version checker in `reaction-cli` has just been updated to ignore release candidates.  1.3.0 won't be the official stable release until it's merged into the master branch (which is why your `reaction pull` didn't work).  Once you update `reaction-cli` to v0.10.0+, the update notification should go away.  Sorry for the confusion.
