### ISSUE TITLE
Payment type selector template for multiple providers

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#246]
When there are multiple payment packages enabled, instead of just looping through the payment packages, it would be good to have an alternate display, either an accordion style of selection, or a screen that display payment types/providers allowing the user to choose.

**Comment by aldeed** [comment]
To eventually support this accordion idea, paypal express and pro will have to be separated into two different checkout templates, and both will have to be registered. That's fine, but there is also the ability to enable/disable each one, so that would need the ability to register some function that core will call to see whether each should be included in the accordion. The simpler solution, since the APIs are different anyway, would be to have two separate paypal packages, paypal-pro and paypal-express, which can be enabled/disabled separately in the dashboard. Was this approach considered?

**Comment by aaronjudd** [comment]
we did talk about it a little.. in my mind the only factor that leans towards having one package with multiple methods is that we only have one package to maintain, and I think it's a better user experience to just see "paypal" and then pick their configuration from several paypal methods. - other than that you're right - but we could just layout it out within the package like it's multiple packages.  

with paypal it's also highly likely you would enable more than one method - I think it would be cleanest to just give each method it's own `provides="paymentMethod"` template - so it's the same format is as all other packages, and have this issue handle the presentation of the options (that said, it still `works` as a single template/paymentMethod).
