### ISSUE TITLE
Implement "registerComponent" in all React components

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2487]
All React components being created (and we should retrofit all current ones) should be modified so they use the `registerComponent` API that @mikemurray created. This is a great way to allow plug-in authors to override components at any level and would remove one of the big blockers for plugin authors.

**Comment by zenweasel** [comment]
@jshimko @aaronjudd Do we think this is ready to be closed? Seems like it's complete.

**Comment by jshimko** [comment]
Yeah, we might be able to close this.  We definitely haven't refactored/registered "all" React components yet, but the API is there and everyone should be chipping away at the remaining components any time they come across ones that still need to be registered.

I suppose the alternative is we could create a checklist of the remaining components and track them in this issue so that it actually gets done.  Otherwise, I suspect nobody will actually do it until it stands in the way of something else.

I'm fine with either scenario though.

**Comment by zenweasel** [comment]
Sort of related but I wonder if there is for the API to prevent us from overwriting our own components. I can see this being an issue at some point.

**Comment by spencern** [comment]
@zenweasel @jshimko Might be worth creating a punchlist of components that still need to be refactored and registered. I'm fine to either edit this issue description or someone can create a new one.

**Comment by zenweasel** [comment]
Is there an easy way to find components that aren't registered?

**Comment by zenweasel** [comment]
@jshimko @spencern Are there any components that we know that need to refactored/registered that we could open a ticket for? If we don't have anything specific to work on let's just close this as there is nothing actionable on it anymore.
