### ISSUE TITLE
IE11 Blank White Page in Development Branch

### ISSUE THREAD

**Issue by stevaras** [reactioncommerce/reaction#2535]
**Expected behavior:**
See the Reaction Homepage and everything.

**Actual Behavior:**
Get a blank white page and nothing happens. 
Many debugger errors in console but not sure which ones are the important ones.
( Can't post them now because I can't copy them from a Windows Virtual Machine )

**Steps to Reproduce the Behavior:**
Load Reaction Development Branch in IE11

**Versions**
Node: 7.1.0
NPM: 5.0.4
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.10.0
Reaction: 1.3.0
Reaction branch: development

**Comment by rhenshaw56** [comment]
@spencern this seems to be fixed by this [PR](https://github.com/reactioncommerce/reaction/pull/2545). However, i noticed it had to do with IE not recognizing some arrow-functions and ES6 syntax on the current version of `transliteration` currently in use on the app. Importing the bundled version seems to work.

**Comment by aaronjudd** [comment]
I'm thinking that might be needed for the client version (the lib/api) (that's how I had to deal with it elsewhere) but not the server side..?

**Comment by zenweasel** [comment]
This problem is fixed if you use the fork that includes the code in the PR referenced above. I'm using my fork of it at "github:zenweasel/transliteration" for testing, but you could also use the authors at https://github.com/callthem-online/transliteration

**Comment by spencern** [comment]
Fixed by #2553
