### ISSUE TITLE
How to set up reaciton with nginx on ubuntu 16.04?

### ISSUE THREAD

**Issue by kenpeter** [reactioncommerce/reaction#2589]
### Expected behavior

expect hit shopshop.space will load reaction commence.

### Actual Behavior

~~~~
502 bad gateway
~~~~

### Steps to Reproduce the Behavior

My nginx config:
~~~~
upstream shop {
  server 127.0.0.1:3000;
}

server {
  listen 80;
  listen [::]:80;
  server_name shopshop.space;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443;
  server_name shopshop.space;
  include snippets/ssl-shopshop.space.conf;
  include snippets/ssl-params.conf;

  root /var/www/html/test/testme/shop;

  location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarder-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_pass http://shop;
    proxy_redirect off;
  }

}

~~~~

~~~~
yarn global reaction-cli
cd reaction
reaction
~~~~

~~~~
Using settings file at settings/settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ /var/www/html/test/testme/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
12:53:37.646Z  INFO Reaction: Load default data from /private/data/
12:53:38.193Z  INFO Reaction: JobServer started
12:53:38.211Z  WARN Reaction: Skipped loading settings from reaction.json.
12:53:45.983Z  INFO Reaction: Reaction Version: 1.4.0
12:53:46.154Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
12:53:46.168Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
12:53:46.527Z  INFO Reaction: Reaction initialization finished.
=> Started your app.

=> App running at: http://localhost:3000/
~~~~

### Versions
(run `reaction -v` from your reaction directory)

````
Node: 8.1.4
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.0
Reaction branch: master
````

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by jshimko** [comment]
This isn't an issue with Reaction.  It's an issue with your proxy setup.  Aside from that, you're running the development version of Reaction by doing what you've outlined above.  That is not suitable for a production deployment for a long list of reasons.  It's only intended for local development.

I suggest you build a Docker container and deploy that instead.  It is the officially supported method of deploying Reaction in production.

```sh
docker build -t reaction .

docker run -d \
  -p 80:3000 \
  -e ROOT_URL="http://<your app url>" \
  -e MONGO_URL="mongodb://<your mongo url>" \
  -e REACTION_EMAIL="youradmin@yourdomain.com" \
  -e REACTION_USER="admin-username" \
  -e REACTION_AUTH="admin-password" \
  reaction
```

https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker

I'm going to close this issue because it's not a problem with Reaction.  Also, [our Gitter chat](https://gitter.im/reactioncommerce/home) would be a better place for questions like these.  I highly recommend you try the Docker recommendations above first though (because I'm just going to say the same thing in Gitter).

**Comment by jshimko** [comment]
or if you're not customizing Reaction, you can skip the build and just run the official image.

```sh
docker run -d \
  -p 80:3000 \
  -e ROOT_URL="http://<your app url>" \
  -e MONGO_URL="mongodb://<your mongo url>" \
  -e REACTION_EMAIL="youradmin@yourdomain.com" \
  -e REACTION_USER="admin-username" \
  -e REACTION_AUTH="admin-password" \
  reactioncommerce/reaction:latest
```
