### ISSUE TITLE
Add additional shipping rate options

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#259]
- [X] Flat rate charge -- Adds a specified amount to each order.
- [ ] Percentage -- Adds a percentage of the order amount (before or after tax).
- [ ] Rate Table -- A shipping table can be based on the order value (before or after tax), number of items, order weight, or number of shipments.
- [ ] Real-Time Rates -- Calculates shipping rates in real-time (via carrier/3rd-party integration)

**Comment by boboci9** [comment]
Hi, I was wondering if you have already decided on a method which will add the dynamic rates calculated by 3rd party shipping in the Cart. Our issue right now is that we are using several 3rd party apis for shipping but we are looking for a solution that all these packages insert their data in the cart.shipping so that they will be available at checkout.
Do you have any ideas on the issue?
Thanks

**Comment by aaronjudd** [comment]
We've talked to Shippo and really like the idea of an integration with them, as a way of handling multiple providers, and as a way to consolidate to a single API.  For each 3rd party providers rates, we'd normalize and insert each quote retrieved into the `Shipping` collection.  
 We still need to implement the "rules" in `getShippingRates`, but this method should insert your rates into the cart.shipping data.

We'd probably need to add some garbage collection for the `Shipping` collection as well (only use rate is saved in Shipping, or removal once selected in cart).

**Comment by boboci9** [comment]
I didn't see the pros in saving every shipping method in every cart but I can't say my mind is fully converted to NoSQL thinking, I worked many years with relational databases so I'm still closed minded when I see these solutions (but I will get used to it).
Regarding the extension of the rules in getShippingRates did you think of any general solution, if yes I would  implement it and add  it in a PR.
My idea would be to add the rates available trough any 3rd party provider in a session array say 
Session.Set("otherShippingMethods", thirdPartyShipping); and then in reaction core getShippingRates we attach these rates to the result as well.
We were considering Easypost instead of Shippo, it seams that both of them are in the top 5 shipping solution providers.
