### ISSUE TITLE
How to run reaction commence in background forever?

### ISSUE THREAD

**Issue by kenpeter** [reactioncommerce/reaction#2598]
Hi,
I am using reaction commerce https://github.com/reactioncommerce/reaction. 

I run from source code, as I did some customisation. I tried `reaction &`. It will eventually die.

How do I run reaction commence in background forever?

**Comment by aaronjudd** [comment]
running `reaction` runs in `development` mode.  It should stay running until you ctrl-c.  If it's dying, it's likely due to a need for [increased files limits](https://docs.reactioncommerce.com/reaction-docs/master/requirements), or memory that the development version needs(because it's always watching for changes).  

This is not how Reaction runs production, you compile (build) a node app that is deployed, and can use [forever](https://github.com/foreverjs/forever) or one of the other node tools to ensure that it runs forever.  You might be able to use this on your background as well... 
See:
https://guide.meteor.com/build-tool.html

**Comment by spencern** [comment]
Hi @kenpeter 

Short answer:
Running Reaction via the `reaction` command is meant entirely for development. It is not built for deployment should not be use in production.

Our [Deployment Docs](https://docs.reactioncommerce.com/reaction-docs/master/deploying) cover how to deploy Reaction in depth, and if you run into any trouble there, I'd recommend checking with our [gitter chat](gitter.im/reactioncommerce/reaction) as there are plenty of helpful people in our community..

Additionally I'd recommend reading through our [docs](https://docs.reactioncommerce.com).
