### ISSUE TITLE
Shipping costs : Charge what you get

### ISSUE THREAD

**Issue by arnaud-zg** [reactioncommerce/reaction#2628]
Shipping fee may not be the same and depend on many factors.
- Custom price per size or weight
- Custom price by location

**Comment by spencern** [comment]
Hey, we're going to leave the tag Pull Requests Encouraged and `needs-more-detail` on here, but we're going to close this issue because the requirements need to be defined better. If this is an issue that you would like to pursue, please create a new issue with more detail and more specific requirements and link to this old issue.
