### ISSUE TITLE
[Marketplace] PDP images not associated with variant/options

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2647]
### Expected behavior
When a variant is selected, and you upload an image, it should be attached to the selected option, and visible.

### Actual Behavior

Images are uploading and attached to the top level product and are not attached to the selected variant.  The only way to upload an image to the variant is through the dashboard, and this seems like it should be a behavior of the media gallery

![basic_reaction_product](https://user-images.githubusercontent.com/439959/29052091-7e93363e-7b9c-11e7-9630-670307d80e33.png)

### Steps to Reproduce the Behavior
Select test option, and upload image, correct behavior is that you should immediately see the image, and if you select another option, you should not (as images are displayed per variant/option)

### Versions
Node: 6.11.1
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce

**Comment by aaronjudd** [comment]
This issue also affects the product display in the grid when using the "variants view".


![shop](https://user-images.githubusercontent.com/439959/29094364-ecddcef6-7c41-11e7-92fc-168133437518.png)

I think this should be considered as a critical path bug, and submitted to the `development` branch.

**Comment by zenweasel** [comment]
Unless I am misunderstanding the behavior as it is now feels like the expected behavior. You can drag an image for an option to the sidebar, but if you drag it to the main product area it should upload for the main product. The old behavior was confusing and frustrating as it was almost impossible to upload an image for the main product once you had added an option.

Not that it couldn't be improved on, but the basic flow feels correct to me (just my opinion)

**Comment by aaronjudd** [comment]
The problem perhaps in the old version was how you selected the main product, and I still feel like is a pretty critical problem -> that area should all be selectable and open the contextual settings for each area.  

The behavior change comes as a surprise to myself (so it's a bug) -> and even if this behavior was correct, it's still not working.
