### ISSUE TITLE
Docker images should default to installing mongo

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2654]
A primary purpose (or at least, nice side role) of our docker images is that they are used for demo/testing initially by many people checking out Reaction.

Reaction images should, therefore, default to providing the Mongo instance, within the build, so they can be used as standalone instances.

Ideally, if the `MONGO_URL`env variable is supplied,  or MONGO=false is used, then we would not provide mongo. (normal production deployments would almost always have MONGO_URL provided).

This has been implemented and reverted before, and needs to be implemented and remain as a requirement (or some variation, perhaps another new image).

**Comment by aaronjudd** [comment]
See #1420

**Comment by saralouhicks** [comment]
I saw this error yesterday and today when trying to use Kitematic. 

<img width="1270" alt="kitematic-mongo-error" src="https://user-images.githubusercontent.com/5458670/29091442-d3e6ef4a-7c37-11e7-8176-ab77c33adb98.png">

**Comment by aaronjudd** [comment]
Merged into marketplace but still needs merging to other branches @jshimko

**Comment by jshimko** [comment]
What other branches do you want this in @aaronjudd?  Obviously we want it in master, but I wasn't sure what the status of development is at this point.

**Comment by jshimko** [comment]
@aaronjudd Cherry pick PR's created for development (#2677) and master (#2678).

**Comment by aaronjudd** [comment]
Should we close this? I'm not sure I want to pull #2678 into master, is it important to do so? if not let's close both.

**Comment by jshimko** [comment]
Assuming we don't want to merge those changes directly to master, yes, this is all set to close.  The only reason I created #2678 was because this issue was specifically about being able to launch a container straight from Docker Hub (or with tools like Kitematic) without needing to setup/provide an external database.  If that can wait until marketplace is merged, then we're good.  That just means `reactioncommerce/reaction:latest` currently does not have Mongo installed in it until that time.

Want to make the call on that @aaronjudd?

**Comment by zenweasel** [comment]
@aaronjudd @jshimko Can we close?

**Comment by jshimko** [comment]
Yes, this can be closed.

https://github.com/reactioncommerce/reaction/blob/master/.circleci/build.sh#L16
