### ISSUE TITLE
Set one or more physical presence(s) based on Zip Code

### ISSUE THREAD

**Issue by bstocks** [reactioncommerce/reaction#266]
For use in calculating which county/municipal/state taxes the shop is required to charge. There will also need to be tests written (depends on #241)

**Comment by spencern** [comment]
We will need the ability to turn on a 'physical presence' on a product-by-product basis. Currently we act as a third-party seller/renter for a number of affiliate shops and we have to collect taxes on their behalf for products of theirs that we offer in any locations that they have a physical presence. 

Our tax collection feels fairly complex in that we have different 'physical presence' for different products. Probably somewhat similar to the way a marketplace collects taxes, it would be nice to be able to define tax nexus within a particular product or vendor.

This may be solvable with #263's comments on toggling tax rates by tags, but I wanted to get it out in front.

**Comment by aaronjudd** [comment]
I don't think it's too unusual, most ecommerce shops should be taxing on a combination of:
 
- shipment origination
- physical company location
- destination

Since each product could be shipping from a different warehouse, that's a similar requirement to yours.

(and this doesn't even touch the new EU VAT rules).

**Comment by aaronjudd** [comment]
Closed in favor of #972
