### ISSUE TITLE
Error flag on every admin component

### ISSUE THREAD

**Issue by janat08** [reactioncommerce/reaction#2691]
### Expected behavior
There's no highlighting of errors for admin.

### Actual Behavior
product without title/sub/label being blocked from publish, yet is saved as draft.  https://github.com/reactioncommerce/reaction/issues/2690

### Steps to Reproduce the Behavior
spam create products, and go to shop front to publish all where things will get funny.

### Versions
Node: 6.11.2
NPM: 3.10.10
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.4.1
Reaction branch: master

### Changes
Flag a component as errored (or rather obj prop), on publish all walk through product object in minimongo that will single out product draft to let show those products, and then component responsible with highlighted CSS. If details become filterable than it will be helpful if there's schema in place (default detail fields) or what-not.

**Comment by zenweasel** [comment]
@janat08 This ticket is really hard to understand. Could you please provide more detail such as proper steps to reproduce, and where this ticket differs from the already existing tickets such as #2274?

In order to work on these tickets and understand them in the context of other issues we have, we really need all sections of the issue template filled out completely. The more complete and clear these are, the more likely we will be able to fix the bug/problem.

**Comment by janat08** [comment]
If you don't try and publish after every item creation, instead creating them continuously this error checking with toast will require you to then go through every single item, instead of highlighting items that prevent publish all.

**Comment by janat08** [comment]
#2690 is an issue description. I suppose this is issue for recommending against blocking publish all button (cursor turns into stop sign), since you'd want to use it for determining what is broken.

**Comment by zenweasel** [comment]
Ok, then maybe you can put your comments there on #2274 rather than creating another issue. Having duplicate/overlapping issues creates a lot of overhead for us.

This is a legitimate problem, I am just trying to keep out system clear so it makes it easy for us to fix things and know when they are fixed.
