### ISSUE TITLE
Needs a Serious Diet

### ISSUE THREAD

**Issue by zoshe** [reactioncommerce/reaction#2721]
I'm not talking about adding loading  tricks, but a real diet for obvious reasons. This can be achieved by using vanilla JavaScript to rid many NPM packages and building tools. For example is lodash really needed and what else could go possibly?
Something for issue thinkable enjoyment:
https://youtu.be/lKXe3HUG2l4

**Comment by jshimko** [comment]
I don't disagree with the sentiment, but I'm a little skeptical that lodash is the best example.  We already use [`babel-plugin-lodash`](https://github.com/lodash/babel-plugin-lodash) to bundle only the methods that are actually used.  It'd be tough to make the case that replacing every instance of a lodash method in Reaction with a vanilla JS function would actually be worth the time since we're not actually bundling any unused code.  Don't get me wrong, I 100% agree with your main point.  We absolutely could stand to strip out some fat that has been gained over the years, but I'm always super skeptical every time someone says replacing a handful of lodash methods is going to be worth the amount of developer hours it'd take do that (it's a fairly common target for this conversation).  

We do absolutely have a rule of never using lodash for anything that has an easy native solution (`Array.isArray()` or `Array.forEach()`), for example).  But there are plenty of instances where lodash solves real problems in a way that is clearly more efficient than having to manage a bunch of internal utility functions.

Anyway, I digress.  YES!  You're right.  But I think we need to analyze what the big offenders are before dumping too much time into code surgery for a few KB of size loss that potentially also brings along a gain of technical debt.  

A good example... Moment.js/Timezone come to mind as great candidates.  That accounts for 400k and is only used for a handful of fairly simple things.  There are much leaner options for that kind of utility library these days (like <https://date-fns.org>).  

See also https://github.com/reactioncommerce/reaction/issues/2635

**Comment by zoshe** [comment]
It's not only for saving size. It's about improving order and predictability too. A lack of order or predictability; will gradual decline into a mess of disorder. Does having more NPM packages and building tools create more order and predictability or less? 
This will  improve product insulation, maintainability, serviceability,  performance, security, error handling, debugging and etc. 
Everything should be consider, including lodash.

**Comment by jshimko** [comment]
Sounds so simple!  

As always, pull requests encouraged.

**Comment by zoshe** [comment]
It may not seem simple now but wait until later. Also, doesn't Reaction have VC backing to hire some extra help to fix this issue, because it would seem better suited for the core developers to fix it since it is a core issue. Anyway, I've peeped at some of the work being done here and it's really nice work, and you seem to have this issue being chip away at and/or planning too. That's very reassuring.

**Comment by aaronjudd** [comment]
Point taken. Closing. https://github.com/reactioncommerce/reaction/issues?q=is%3Aissue+is%3Aopen+label%3Aperformance
