### ISSUE TITLE
[PDP] Cross-sell, related products, upsell components

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2769]
This is a general task to define a few different up sell components for the PDP page, and begin the design tasks for this.  There are a few existing issues on this, we can gather the info/specs here.

**Comment by spencern** [comment]
@cindyfirestone can you add some more details to this issue?

**Comment by cindyfirestone** [comment]
A simple way to do this would be to pull items with 1 or more tags. We should limit how many related items should show, and this should be randomized so the same items don't always show up.

**Comment by Itsneilpatil** [comment]
For the simplest use cases, related product recommendations can either assist shoppers to see like products with similar facets/attributes (display other blue road bikes) and/or provide complementary recommendations (display bike lock(s) for bike that has been carted).  

The initial application of related products for finding "similar" products could be accomplished by matching all the tags of the PDP and/or specific carted item and then ranking the catalog items based on the total number of tag matches. For example, if a PDP contains tags Bike, Blue, Child.  Product A with tags Bike, Child would rank higher than Product B with tag Bike.    

For "complementary" product recommendations, in order to properly cross-sell other items, an additional tag would be needed to be inserted into the lookup  to properly surface truly complementary products. For example, for a bike that was carted, there would be a need to have a static setting to lookup products that are tagged as accessories, services, or other tags determined specific by each retailer.   The system would then retrieve & rank as it would normally - but with the additional tag inserted by the system. 

Other things to consider/futures:
- Ability to limit retrieved products within a specific price point +/- x% from currently viewed/carted product.  
-Further rank products based on current stock levels - i.e. recommend perishable products with the highest level of inventory, or display limited "last 1 left" products.
-Further rank products based on popularity - i.e. # sold in the past x days.  
-Further rank products based on past purchase combinations - i.e. Product A was most often purchased with Product B (carted product).

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #17](https://github.com/reactioncommerce/reaction-feature-requests/issues/17) via [**ZenHub**](https://www.zenhub.com/)
