### ISSUE TITLE
Refactor cart state machine into methods with hooks

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#278]
I'm not sure I like the current state machine implementation for workflows.  Although it controls valid workflow and will move an order through 'order states', I don't think it's flexible enough, it might be close, and just needs some additional functionality.  Here's some thoughts about what I think the loose requirements are (and example scenarios):

*  `events`.  Ability to trigger an workflow event, or also catch a workflow event to trigger your own code, when the event is triggered.
    - inform fulfillment system of order
    - send transactional emails
*  validate that the current state is valid for the event to be triggered
    - no shipping events without a shipping address
    - no payment events without a billing address
* result with error/success messages for client
*  easily be extend or override in packages
   - shipping or payment packages may have additional events
  -  fulfillment triggers
  - shipping label and status updates
*  workflow should be able to be handle different "scenarios".
   - downloadable product  may not need shipping event
   - 'guest' checkout may not require login
*  support partial workflows
    - 1 payment was made, but wasn't entire balance, stay in paymentPending state
    - partial shipments of order items before orderCompleted
    - orderCompleted, 1 item return
* log events to ReactionCore.Events
    - store event results,errors to easily track down workflow errors
* expiration / invalidation events
  - shipping quotes may expire
  - payment authorizations may expire
  - product quantity stock may change

**Comment by aaronjudd** [comment]
Potentially, we could quickly convert the state-machine workflow to events and use https://github.com/raix/Meteor-EventEmitter. @aldeed if you want, I can take this one back. It's percolating up on my mind with paypal and the testing stuff.. events will be easier to test, and maintain I think.

**Comment by aaronjudd** [comment]
@mikemurray @spencern

Here's my proposal, this should let us remove state machine, and also give before/after hooks to each server step, and free up the UI to be independent of cart state.

Define workflow for shop

    Shops.settings.workflows = [
    {'simple': ['login', 'address', 'shipping', 'review', 'payment']},
    {'download': ['login', 'review', 'payment', 'download']}
    ]


Add product type 

    Product.type = 'download' #by default


On checkout, review product.type (s) and merge matching workflows into single workflow (could also later be a grouped cart flow)

So if you had an `item.type = 'simple'` and `item.type = 'download'` you'd end up with checkout flow of:

   ['login', 'address', 'shipping', 'review', 'payment', 'download', 'download']



Where each workflow entry represents the appearance order and the template to load.


    checkState (state) -> 
      did the item in workflow before me already run, is true
      else return false


    Meteor.methods

      [cart/methodName]
      
      "cart/state": (state) ->
        if checkState(state)
          Cart.update state: state


(cart/state will let you forward or reverse to allow for step reversal)

This will require that each step to be independant process (where the templates don't have any dependency on each other or the checkout flow).

**Comment by spencern** [comment]
I'll look this over more tonight or tomorrow, but after a brief read through it looks good. I think managing workflow by product type is going to make a lot of potential edge cases way easier to implement.

**Comment by spencern** [comment]
While reviewing the current implementation / cart workflow state machine I realized that we don't currently have any way to process canceled orders, returns, partial returns, refunds, partial refunds, etc (Payment does have a way to refund, but not Products, Orders)

Not sure what the plan is for current implementation of these parts of the process, but we will need to have access to these hooks from packages as well.

On another note (and I hope this will become more clear when this workflow gets more fleshed out), it currently feels like we need a way to override Meteor.Methods or change the method called from core to package.

E.g. for products with inventory variants (rental or otherwise), we need to use a different `inventoryAdjust` method than is supplied with core as inventory is calculated differently. This will be fine if we can specify a method to call to adjust inventory, but not sure if a before/after hook will work as it will call the default method anyway I think.

See the [rental products inventoryAdjust method](https://github.com/getoutfitted/reaction-rental-products/blob/development/server/methods/orders.coffee) vs the [core inventoryAdjust method](https://github.com/reactioncommerce/reaction-core/blob/0b82287c770e7954978623f24494f785c25932f0/server/methods/cart.coffee#L153-L163)

It also seems like as we start adding packages that affect the cart/checkout workflow that the order in which they adjust the workflow will be important.
