### ISSUE TITLE
HTML product description should be displayed with mark-up

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2784]
### Expected behavior
HTML product description should be displayed with proper mark-up.

### Actual Behavior
HTML product description is displayed as plain text and HTML tags are displayed as plain text, too.

### Steps to Reproduce the Behavior
1. Write HTML content to the product description.
2. Save the product.
3. Switch to the product view mode.

### Versions
1.4.1

**Comment by andrew-mikhailov-videal** [comment]
We are going to implement this in the closest time. As it is a small feature which greatly breaks how the customer's shop looks like. Also for this thing we need an HTML editor for the product's description.

**Comment by aaronjudd** [comment]
We've discussed this before and discourage this as a practice.  The styling of content can be done via styling tools and when we want to stylize new data, we should add new data/content or add metafield/metadata, and add stylize dependent on particular data.  It's really not in our interest long term to pollute product data with markup. Feels like you could also build a component that separated the styling( into another data field), rather than in the data as well (post-css).
