### ISSUE TITLE
Need ability to have negative prices

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2786]
### Expected behavior
1. Assign a negative price to the product option.
2. Save the product.
3. Open this product in the view mode.
4. Choose an option with the negative price.
5. The product option price is subtracted from the main product price.

### Actual Behavior
The product will not be saved because the price can be only positive.

### Steps to Reproduce the Behavior
1. Assign a negative price to the product option.
2. The product will not be saved because the price can be only positive.

### Versions
1.4.1

**Comment by spencern** [comment]
Can you talk about the use case for having negative prices in a little more detail?

**Comment by cindyfirestone** [comment]
@spencern I think it's something like this use case 
<img width="1125" alt="customize_macbook_-_apple" src="https://user-images.githubusercontent.com/22083616/30188082-6fb1eb62-93e1-11e7-9f56-76f9fa1d857a.png">

**Comment by andrew-mikhailov-videal** [comment]
@cindyfirestone, Yes. Your screen shot for the use-case is correct. And we have several such products coming from customer's Magento shop.

**Comment by spencern** [comment]
I think you could do this with the UI.

To clear up any misunderstanding about how Prices work in Reaction let's make sure we're on the same page about the following:

Variant or Option prices in Reaction don't reflect a difference between a given option and another option, or an option and it's parent etc. Prices on variants or options reflect the exact price a customer will pay for that particular variant or option.

You should be able to achieve what you're looking for with some UI wizardry rather than trying to change how the price works at the core.

Our default UI doesn't support variants nested more than 2 levels deep, but the schema and core support unlimited nesting.

I've been writing a bit about how products work on our blog recently - https://blog.reactioncommerce.com/tag/engineering/ - specifically check out the first post on Products https://blog.reactioncommerce.com/product-part-1/ which gets into the nuances of how the Reaction Product schema is built and might help in regards to this topic.

**Comment by aaronjudd** [comment]
Each variant or option is a product, and this has a price.  It would be strictly a UI change to show the difference in pricing between any given option/variant.  ie; it's not `price: -100`, it's a difference of `-100`.
