### ISSUE TITLE
Duplicated products show archived variants

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2814]
## Expected behavior

When I duplicate a product from a product that has archived variants options, I shouldn't see the archived variant options on the duplicate. I should see the variant options with their duplicated option title and title. 

### Actual Behavior

When I duplicate a product it shows me the variant options that have been archived from the product I duplicated it from. Plus, the option title, title, and price are missing.  

### Steps to Reproduce the Behavior

1. Create a product
1. Add a variant option
1. Add a second variant option
1. Archive and publish the second variant option
1. Duplicate the top-level variant 
1. Observe that all the variant options (including the previously archived ones) show up and they don't  copy the option title, title, and price.

**Comment by efalayi** [comment]
@rymorgan I can't seem to reproduce the issue with the steps provided. Also I couldn't clone an archived variant.

<img width="1280" alt="archived-variant" src="https://user-images.githubusercontent.com/28438068/31121115-ddcd0706-a82e-11e7-9feb-fd31ea276449.png">

**Comment by aanchirinah** [comment]
@rymorgan , I also followed your steps and I am unable to clone an archived variant.

**Comment by rymorgan** [comment]
@aanchirinah @efalayi - I think my steps to reproduce weren't clear. I've updated the language to make more sense. It's happening when I make a variant with an option then archive the option, then duplicate the top level variant. I'm also seeing an issue where the duplicated option title, title, and price are not being duplicated.

**Comment by kieckhafer** [comment]
I'm able to reproduce.

@rymorgan is pointing out two different things here, however I think by fixing point #1 below, it will take care of fixing the second as well, as they seem related code-wise.

1. It seems that the data on the options - title, option title, price, etc (and probably archived status - see #2) - is not being transferred to the new cloned option. It looks like the new option is getting the info from the top-level variant instead. There is probably some mixed up code where we are using the `option`'s parents document, instead of the `option` document to get the data.

2. It seems that the archived status is not being transferred to the newly cloned`option`. So if i create 10 `option`'s and archive 5 of them, then 5 should be archived when I clone the `option` as well. What's happening is all 10 are cloned without the archive status being applied. Again, I believe this will be resolved when #1 is resolved, but test for this in addition to testing for #1.

**Comment by aanchirinah** [comment]
@rymorgan , I able to reproduce the bug now. Also @kieckhafer , thanks for adding more context.

**Comment by kieckhafer** [comment]
@rymorgan I believe this was fixed in `release-1-5-0`, can you please re-check?

**Comment by rymorgan** [comment]
Yep, this should have been closed. Closing.
