### ISSUE TITLE
Doubled up sidebar in some views. 

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/reaction#2839]
### Expected behavior
When I click through the Reaction, I shouldn't' get a double sidepanel

### Actual Behavior
I'm getting a doubled up side panel in some instances

### Steps to Reproduce the Behavior
With edit mode on
Click on orders
Click on order to open up order details panel
Close the whole panel
Click on a product in the grid
See doubled up panel

![double side panel](https://user-images.githubusercontent.com/20409254/30353267-bf569e14-97d9-11e7-9c57-e8f384d8c085.png)

### Versions
Node: 4.5.0
NPM: 5.4.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace

**Comment by zenweasel** [comment]
@rymorgan Are you testing this on the latest `marketplace` as of just a couple of hours ago?

**Comment by zenweasel** [comment]
@mikemurray Is this possibly the reason for the "index" check that we were talking about. Don't show then when you are on the product grid?

**Comment by rymorgan** [comment]
@zenweasel Yep, after we pulled in the other order panel fix. I was testing that fix and found this.

**Comment by foladipo** [comment]
@zenweasel @rymorgan I don't think this is due to that index check that we took out. Coz I checked that code again and saw that what it was doing was setting data for the actionView as long as we weren't on the index route.

Rather, what I think is that this happens when an `actionView` is opened immediately after an `actionViewDetail`. Coz I wrote a fix for this just now before realizing it repeats itself elsewhere.

For example, you can reproduce the above bug in a different place/route as follows:

- Log in as admin and navigate to the index route.
- Make sure you're in edit mode.
- Double click any product to edit it.
- Close the "Product Settings" panel that pops out by default.
- Open the orders panel, and open the details panel for any order. Then close the whole panel.
- Now click any of the product editing buttons that will open an `actionView` e.g edit a product variant. You'll observe that it's also doubled up now.

My first proposal is that anytime `showActionView` is called, it should be preceeded by `hideActionViewDetail`. But what do you think about that?

**Comment by rymorgan** [comment]
@mikemurray Can you provide some direction here?

**Comment by mikemurray** [comment]
@zenweasel I could have been that, but that logic was not ideal either way.

@foladipo I think that might work. When we do `showActionView` / `setActionView` we can close the `actionViewDetail`.

**Comment by rymorgan** [comment]
Fixed by #2861 PR
