### ISSUE TITLE
Marketplace Admin

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2869]
Placeholder ticket for discussion

We have often spoke about the idea of the "Marketplace Admin" and there are permissions that allow them to do things that store admins cannot.

But in terms of dealing with orders we are treating them just like another store admin. They can view and act upon their orders and trying to make the Orders panel work for this sort of "super admin" will require some work. (Maybe a separate Dashboard?)

**Comment by spencern** [comment]
Sticking the `needs-more-detail` tag on here for now as before anybody starts working on this it should be specced out in more detail. Added it to the design project as well @rymorgan as we'll need designs on this at some point.

I think there we need some product-focused thought and discussion into exactly what this idea means and how we are implementing the marketplace owner's view into merchant shop's activity.

Keep in mind that we should be implementing sensible defaults as each marketplace may have it's own requirements that can be implemented via plugin. 

**Some questions for anyone who's building or planning to build a marketplace:**

* What data is most important for marketplace managers?
* What actions are most important?
* Should there be anything within a merchant shop that's not permissible for the marketplace owner to view?
* Should a marketplace owner be able to switch between "marketplace view" and viewing as a certain shop or should they be scoped to the marketplace exclusively?


Here are some things that I think a `Marketplace Admin` might need. Some of the discussion will inevitably need to be around whether something should be core or a plugin
 - Easy communication with merchants/shop owners
 - Enable/Disable/Suspend/Ban Shops
 - Highlight/Feature and merchandise featured Products/Collections/Shops/Users
 - Insight into how shops are performing - over/under performing, top, bottom, etc.
 - Integrations managment (ads, marketing, shipping, payment, etc)

**Comment by rymorgan** [comment]
Yea, I need a lot more info to design anything :)

**Comment by JoeyLyman** [comment]
Data: How often an owner gets online, possibly.  This may be irrelevant if there are other ways to find unresponsive owners and ban them.  I don't know all of Stripe's options, but if there are any complaints about a shop owner not delivering paid-for-items, then they probably shouldn't get paid out immediately, or the marketplace owner should be able to refund the customer or hold onto the $ until both sides are happy. 

I also don't know if there is a need for seeing the marketplace from the view of a certain shop; I would imagine everyone would have access to the same views - whether that be to see how a new customer would come onto the site and see the entire marketplace, and also be able to look at all the options from an individual seller.  I think as an individual seller, these would be the views I would want to see as well.

All of the things, Spencer, that you mentioned as things a Marketplace Admin might need, seem great.  The ability for an Admin to directly add and edit Tags on seller items would be great, so that the Admin can organize pages, without having to ask sellers to do all follow a format and then rely on them to do so.  I would want to be able to have a main page show everyone, and then be able to make sure that all sellers that are selling "Fair Trade" have the right tag, so that the "Fair Trade" page shows all of those items, and if a seller typed in "Fair-Trade" as a tag, I could change it to "Fair Trade" to follow convention and make sure that it shows up on the "Fair Trade" products page.

**Comment by aaronjudd** [comment]
Issue moved to [reactioncommerce/reaction-feature-requests #20](https://github.com/reactioncommerce/reaction-feature-requests/issues/20) via [**ZenHub**](https://www.zenhub.com/)
