### ISSUE TITLE
Cart which cannot be purchased

### ISSUE THREAD

**Issue by andrew-mikhailov-videal** [reactioncommerce/reaction#2870]
There is a situation when a shop will get a cart which can not be purchased.

### Expected behavior
The user should be able to purchase products in his cart under any circumstances.

### Actual Behavior
It is possible to build a cart which will not be purchasable.

### Steps to Reproduce the Behavior
1. Install a fresh shop.
2. Do not configure any shipping methods.
3. Add some products to the cart.
4. Configure some shipping methods.
5. Try to purchase (checkout) the cart.
6. The shop will recommend adding shipping methods although they have already been added.

From this use case more use cases can be derived resulting in incorrect behavior.

### Versions
1.4.1

**Comment by aaronjudd** [comment]
Haven't tested yet, but did #2738 impact this issue at all?

**Comment by aaronjudd** [comment]
@foladipo  can you take a look and see if can reproduce in `marketplace`?

**Comment by foladipo** [comment]
Ok. I will try to reproduce it. Be back in a bit.

**Comment by foladipo** [comment]
@aaronjudd Yes, this bug can be reproduced in `marketplace`.  A modified version of @andrew-mikhailov-videal 's reproduction steps are as follows:

1. Log in as admin and turn on all shipping plugins. Then logout.
1. Register as a regular user, and then sign up to be a seller by going to `Dashboard > Your Profile > Become a seller`.
1. Create a product that belongs to the shop *from the previous step*.
1. Attempt to checkout with only that product in your cart.
1. You'll see that an error message is displayed instead of shipping methods.

**Comment by zenweasel** [comment]
I think is related to: https://github.com/reactioncommerce/reaction/issues/2836 which I am working on and hope to have a PR in for today.

**Comment by spencern** [comment]
@zenweasel do you have a PR that is ready for this? If not can you give an update?

**Comment by zenweasel** [comment]
@spencern No, no PR and I am not expecting to have one today. Still working through some issues with getting Shippo to work properly in a multi-shop environment. I hope to have this completed by the end of the week and will be my main focus after finishing Stripe.

**Comment by spencern** [comment]
Resolved by #2847
