### ISSUE TITLE
Order filtering by shipping status

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#2906]
Users with permissions to view orders dashboard should be able to quickly filter the list of orders by the shipping status.

From a dropdown, users should be able to filter orders by shipping status. 
Shipping statuses:
- Picked
- Packed
- Labeled
- Shipped
- Delivered

If users search while a filter is active, the search should take the filter into account.

Users should be able to clear all filters easily as well (#2358)

**Comment by rymorgan** [comment]
@spencern Can you confirm those are the correct status'

**Comment by joykare** [comment]
@spencern @rymorgan have this on the PR list: https://github.com/reactioncommerce/reaction/pull/2914
It doesn't have the marketplace tag on it but I think it should, seeing as it's part of the orders marketplace UI already.

**Comment by spencern** [comment]
@rymorgan these statuses look correct to me.

**Comment by rymorgan** [comment]
@spencern  Great! Glad these are the right statuses, to begin with.

**Comment by rymorgan** [comment]
@joykare If this can get into the markeplace release b/c the issue is complete, then that's great. I'll go check the PR now.

**Comment by kieckhafer** [comment]
@spencern should `New` be one of the statuses to filter by as well?

**Comment by rymorgan** [comment]
@spencern @kieckhafer I'm wondering if New for both status and shipping status is confusing. Maybe a status like "Not started' would make more sense. So when an order comes in it would have a status of new and a shipping status of not started.

**Comment by kieckhafer** [comment]
I think `New` makes sense for orders. It makes less sense for shipping, but I'd stick with being consistent between the two over changing just one.

**Comment by rymorgan** [comment]
@spencern What do you think? 

I wanted to give a little background on what I was thinking for these statuses. We have what we are calling status now which is new, approved, captured, processing, completed and canceled (I still think we should remove approved). These statuses are the overall status of the order. In my mind, the 'shipping status' really amounts to a fulfillment status. The fulfillment status is there for a few reasons - one, to give more specificity if needed on an order. Ok, the order has been captured, but  has it been pick/packed? Or a customer service person wants to quickly see if an order or a group of orders has been shipped to pass that along to a customer. I was working within the current flow we have where there's a separate card for both payment capturing steps and the fulfillment/shipping steps and these statuses mirror those. The fulfillment status will mirror the status here: https://zpl.io/VKG0xRX (which has yet to be built out for the detail view. When we can also complete the shipping/fulfillment part of the UI, I can see it all coming together and making more sense. The system I'm imagining is sort of related to how shopify does it, where they have both a payment status and a fulfillment status. There's is less detailed like, "not fulfilled, partially fulfilled, fulfilled". 

Also, these statuses are flexible. If a company does pick/packed as one status then they should easily be able to make that customization and the UI is flexible enough accommodate adding or removing of steps in a process. I think it's also flexible enough that if an organization doesn't need the extra detail they could remove that status entirely and just keep the global status.

**Comment by spencern** [comment]
@rymorgan @kieckhafer 

Good discussion topic. I have a lot of feelings on this, and agree that it's more nuanced and complicated than we've currently got it.

**Approved**
`approved` as a status and process needs to go away. If you've been waiting for an official pronouncement, this it it.

**Keeping marketplace in mind**
In the case of a multi-part marketplace order, I think that we should track this on a per shop basis, and bubble it up to the overall order, or consider not keep track of this on the overall order at all. If we don't keep it on the overall order for marketplace, we should do the same for single-shop, there should be no real difference between the two in terms of how orders are processed except who is doing the processing.

#### Order Statuses
  - New
  - Processing (Picked, Packed) 
  - Shipped (Labeled/Ready To Ship, In Transit, Exception, Delivered, <Returned?>)
  - Completed / Cancelled

**New** is a status that every part of an order should have upon creation. We can debate the exact terminology for a little while, but this is used both to indicate that a particular workflow has not been started yet, and also to be the initial starting point for that workflow. The order (if we keep an order status/workflow) should have this status, the shipment should have this status, the billing object(s) should have this status, and each item should have this status.

**Processing** is a workflow that exists at the order level, and happens at the item level.  

It is my current understanding that you can `capture` a charge when you begin to process an order, but it's possible that you're supposed to wait until the order is in a shipping state (e.g. label printed, and ready for pickup) @aaronjudd I'd be interested in your insight here.

Orders are not picked or packed, _items_ are picked and packed. Specifically each individual item should move through the picking / packing workflow while the order / shipment remains at a "processing" state.

The order/shipment is ready to move to the "Shipped" status once each item in that order/shipment have been packed. This is a form of QA for some warehouses as well, where you must verify that all items are present in the shipment before you can ship. This is also where the "bulk" actions comes in, as depending on the warehouse, you may have some teams that use barcode scanners to quickly move through this process, and others that do a visual inspection and check off each item as being present.

**Shipped** is a workflow that exists at the Shipment level. While the order lives at the "Shipped" status, each shipment will move through some form of this. For orders shipped without a complex integration, the last step of "shipped" will often be "In Transit" which maybe should actually be termed "Shipped" for simple integrations. 

For integrations that tie into a shipping vendor's API such as Shippo, or a third party resource such as AfterShip, these shipments should be automatically updated every time that shipment is updated by the shipping vendor, in this case, each _shipment_ will process through Labeled, In Transit (which could have many iterations with a location tag), Exception (an optional status that would indicate that a package has been delayed or some other non-normal activity has occurred), and Delivered. Let's not worry too much about the possibility of tracking returns for now, but keep them in mind for the future.

**Completed**
An order is "completed" once it's been fully resolved. In 90%+ of cases this will be due to an order being delivered or shipped. For simple shipping setups, when the UPS/FedEx/Carrier truck picks up the package, you'll mark the order as completed and be done unless the customer contacts you. For complex shipping setups, this can happen once the order has been confirmed to be delivered.

There can, and probably should be an entirely separate customer success workflow that starts once an order has shipped. I believe that should probably be operated independently of the order fulfillment workflow.

At GetOutfitted we had a concept of an Incomplete order as well, but used that primarily for orders that were never returned, lost in transit during return, or similar. I don't think that's a useful concept to have for the 80% use case.

I realize I just wrote a book on this. I think if we focus on these top level steps for the order, and then the sub-steps for each of the other workflows as we implement them, we should be putting ourselves in a good position to succeed now and also extend and build the necessary features to make this a good long-term solution.

I welcome any feedback on this as well.
