### ISSUE TITLE
List view for orders, products, customers

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#300]
list view `ordersListView` wired to fa-th-list) that list orders groupable by group, status, data. Sortable by all.  Color coded. Drag between stages. Dbl click to edit (ala shipping rate management).

**Comment by aaronjudd** [comment]
@mikemurray this is just a vague issue that was meant to cover creating both grid and list views for various admin tools. perhaps we should close in favor or more specific issue for each.? feel free to close.

**Comment by aaronjudd** [comment]
@rymorgan let's upload designs for this (next)...

**Comment by rymorgan** [comment]
Related to #1732

**Comment by cantuket** [comment]
Curious if anyone has started on sketches for this? Would love to see this implemented and happy to start on some designs or help out if someone is working on them already.

**Comment by rymorgan** [comment]
@cantuket List view for orders and account admin has been implemented and released with release 1.5+. Products is something on our roadmap for the next section of our roadmap - https://reactioncommerce.com/roadmap

Having said that, we welcome feedback and input. We're working on gathering requirements for bulk product management but if you want to give input I'd suggest this issue as the best place for the moment.  https://github.com/reactioncommerce/reaction/issues/1732

**Comment by rymorgan** [comment]
Closing this issue because of the following. 

- List view for orders has been implemented. 
- List view for accounts admin is covered here -  https://github.com/reactioncommerce/reaction/issues/2922
- And bulk product management is covered here - https://github.com/reactioncommerce/reaction/issues/1732

**Comment by rymorgan** [comment]
Closing this issue because of the following. 

- List view for orders has been implemented. 
- List view for accounts admin is covered here -  https://github.com/reactioncommerce/reaction/issues/2922
- And bulk product management is covered here - https://github.com/reactioncommerce/reaction/issues/1732

**Comment by cantuket** [comment]
@rymorgan Ah ok thanks, the Product list view is what I was looking for so makes sense now.
