### ISSUE TITLE
Add settings panel to define dimensions for default parcel to shipping dashboard

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#3019]
With #2992 we now automatically calculate the parcel size for cart items from whichever variant was added to the cart. 

We need to add a settings panel within the shipping dashboard that permits defining default parcel sizes for products and variants that don't have dimensions defined. 
We should add sensible defaults for the default parcel size so that it's never null which could cause Shippo or other shipment providers to fail to calculate shipping correctly.

![image](https://user-images.githubusercontent.com/1203639/31150232-10d8c754-a850-11e7-95f8-e9ec962718bd.png)

This section should permit setting the default parcel size with the fields: width, height, length, and weight. 
Other app-wide shipping settings can also live here.

**Comment by spencern** [comment]
This should default to a flat rate priority box dimensions and a weight of 1lb for all reaction.
This should also permit users to update the default.

**Comment by zenweasel** [comment]
@rymorgan Do we actually need design for a settings panel?

**Comment by rymorgan** [comment]
@zenweasel I think we might at this stage. But something on my upcoming agenda is to work on some standards for settings cards that will enable us to build this w/out design.

**Comment by efalayi** [comment]
@rymorgan is there layout for this section that I can use?

**Comment by zenweasel** [comment]
@efalayi So these values should be used like this:
1. When a new product is created it should use these values as defaults.
1. When shipping is calculated if no values are set (i.e. they are 0) then it should use those values to send to Shippo.
1. When the store owner sets the values it should ask them if they want to reset all existing products, and if so it will overwrite all values with this new default.
1. If the product is not set and the default is not set it should fall back to the dimensions of a flat rate priority and a weight of 1 so that we never get a situation where we don't have a weight for a product.

**Comment by zenweasel** [comment]
from @spencern 
USPS Priority Mail Medium Flat Rate Box - 11 1/4" x 8 3/4" x 6"
Not sure what a good default weight would be, maybe 7 or 8 lbs?

Reference for dimensions:
https://www.usps.com/ship/priority-mail.htm

**Comment by efalayi** [comment]
@zenweasel should the user also have the option of not resetting existing products? 
Also, should the minimum values for size be 0 or 1?

**Comment by efalayi** [comment]
@zenweasel could you please explain this part:
```
If the product is not set and the default is not set it should fall back to the dimensions of a flat rate priority and a weight of 1 so that we never get a situation where we don't have a weight for a product.
```

**Comment by zenweasel** [comment]
So this ticket should be just about defining default dimensions for Shippo (or alternately for any shipping plugin) but should not be used for other places such as defaults for the PDP.
