### ISSUE TITLE
Npm package Aliases doesnt work on custom plugins

### ISSUE THREAD

**Issue by josx** [reactioncommerce/reaction#3178]
### Expected behavior

Same way to include reaction imports on my custom plugin,.
I think if this cant be fixed at least we need clear documentation on how to do it or an advice.

### Actual behavior

Aliases on reaction package.json doesnt propagate to my custom plugin, if i am using package,json in my custom plugin.

So I need to replace  ``` import { registerComponent } from "@reactioncommerce/reaction-components";
```  with  ```import { registerComponent } from "/imports/plugins/core/components/lib";```

### Steps to reproduce the behavior

Create a new plugin with npm dependencies
And the make an import and @reactioncommerce aliases doesnt work.

### Versions
```
Node: 4.2.4
NPM: 4.1.1
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.0
Reaction: 1.5.3
Reaction branch: geo
Docker: 17.03.0-ce
```

**Comment by janus-reith** [comment]
Instead of doing the the direct imports, an easier short term solution is to copy the related aliases part of the main package.json to your custom plugin's file.

**Comment by jshimko** [comment]
I was thinking that this could possibly be fixed by syncing the aliases automatically with `reaction-cli` when the app starts.  The only potential issue is those changes would then need to be committed to the user's repo and it feels a little weird to make the assumption that that's ok to do on their behalf without asking every time the plugin's `package.json` gets updated.  Might still be worth doing though.  It's certainly much nicer than having to manage that manually yourself.

**Comment by josx** [comment]
I dont know how is done the build in reaction, but it is an alias in the js processor (like aliases in webpack).

**Comment by aldeed** [comment]
The solution is to move things that custom plugins need to actual NPM packages. Separate issues should be filed for anything specific that anyone comes across while creating custom plugins.
