### ISSUE TITLE
In multi-merchant order buyer is charged the total shipping cost for each individual sub-charge

### ISSUE THREAD

**Issue by prosf** [reactioncommerce/reaction#3190]
### Expected behavior
If there are more than one shops in an order, for each individual sub-charge(one for each shop), buyer should get charged the cost of this specific shipment.

### Actual behavior
If there are more than one shops in an order, For each individual sub-charge(one for each shop), buyer gets charged the full shipping cost(of all shipments combined) 

### Steps to reproduce the behavior
Enable a flat rate shipping option(e.g priority) from the marketplace dashboard.
Create two merchants with one product for each one.
Sign in with a third account(as a buyer) and add to card these products.
Select the available shipping rate .
Complete the payment.

In the order complete screen, each subcharge will have the whole shipping cost(of the two shipments combined).

Also If you login as a one of these sellers, and open this order, you will see the total shipping cost applied to the seller's subcharge. 

### Versions
Node: 4.2.6
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.19.0
Reaction: 1.5.4
Reaction branch: master
Docker: 17.03.1-ce

### Relevant Pics
![selectingrate](https://user-images.githubusercontent.com/8209895/32269473-2893f744-befb-11e7-8d28-634db06c9e2b.jpg)
![confirmationoforder](https://user-images.githubusercontent.com/8209895/32269472-287185ce-befb-11e7-988a-58acdf86d79e.jpg)

**Comment by prosf** [comment]
I' ll push a pr tomorrow

**Comment by zenweasel** [comment]
I actually think this is the expected/desired behavior not a bug. Each shop requires a shipment and needs to charge for it. @spencern We discussed this a bunch of times. This is how we decided to do this for now, correct?

**Comment by prosf** [comment]
Hmm Sorry it seems it's not clear in these pics what is the problem. The actual problem is that the shipping rate selected had an amount of 3 . So each of these sellers should get paid this 3$ (not 6)

**Comment by prosf** [comment]
I updated the pics so it's easier to spot the problem : Buyer gets charged $337,96 instead of $323,98 as he's charged the order's total shipping cost(6.99+6.99) twice.

**Comment by zenweasel** [comment]
I just tested this now and I don't think the issue you are reporting is due to the way shipping is being calculated but the way it is being displayed in the Completed Order page. If you look at the order confirmation email you can see that the merchandise total + the shipping total = the correct total displayed. In your own screenshots you can see that the total displayed actually reflects the shipping just being charged once per shop at the correct amount. ($10 + $300 + $13.98 = $323.98). There **is** an issue there, but I it's not affecting what the customer is being charged.

Here's screenshot of the order confirmation email
![maildev](https://user-images.githubusercontent.com/72819/32586891-54323e38-c540-11e7-9eb6-823e7a25957e.png)

and my completed order page
![cart_completed](https://user-images.githubusercontent.com/72819/32586963-d1d5e948-c540-11e7-88f5-06343566c0e0.png)

and the order dashboard

![reaction](https://user-images.githubusercontent.com/72819/32587051-35cb047e-c541-11e7-9f23-98dabf16e081.png)

**Comment by zenweasel** [comment]
Again to clarify. It is the **expected** behavior that if the shipping rate is $2.99 **each shipment** will be charged $2.99, thus the total charge will be $5.98.

**Comment by zenweasel** [comment]
So think the only issue is here, this should each say $2.99, **not** $5.98.
![cart_completed](https://user-images.githubusercontent.com/72819/32587170-cdcaedfc-c541-11e7-87a4-13447f0c6e21.png)

**Comment by zenweasel** [comment]
Based on your PR it fixes the above issue so maybe I misunderstood what you were trying to say here

**Comment by prosf** [comment]
With the last Reaction's implementation of charges(e.g in Stripe) an individual charging of buyer happens for each
different Shop of the cart, so in your example two different stripe charges will take place.

You can see that if you check the Shop-loop in imports/plugins/included/payments-stripe/server/methods/stripe.js:210 (Method: "stripe/payment/createCharges")


So the "Order Total"($47.97) is not the amount that actually get charged. Instead buyer will get these two separate charges:

1. 19.99 + 5.98(2.99+2.99)
2. 22.00 + 5.98(2.99+2.99)
---------------
53,95

At the end of the day ,buyer will get charged totally: 53.95 and not the correct 47.97

**Comment by codejockie** [comment]
Fixed.
