### ISSUE TITLE
Password must be at least 6 characters long

### ISSUE THREAD

**Issue by kosir** [reactioncommerce/reaction#323]
I created my first test shop month or so before with my private email address, but was stacked in loading... Tried again today, and nothing changed. So I tried with my company email, got a shop but can't login to admin account.
When I created account, I didn't get any password via email, so I tried with reset password, to log in to admin account-. When I try to set new password, I got this error: Password must be at least 6 characters long (no matter what I enter).
Is it necessary to set up Facebook app for admin account?
Thanks in advance for any reply...

**Comment by kosir** [comment]
I also tried to connect via Facebook, entered appID and appSecret, but when I try to connect, I got this error: Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by aaronjudd** [comment]
hi @kosir.  Thanks for the feedback!

I'm a little confused, are you trying to login to https://reactioncommerce.com/account , or login to the test shop you created? I guess a little of both here?

I'm not sure if anything is wrong with the password reset on reactioncommerce - I just tested changing my password for the account and that worked for me.  

However, that doesn't change the "shop" passwords - those are listed in the control panel. You login to the test shops using the email of the reactioncommerce account you used to create the shop + the password listed.

You should have got an email when you created the shop, the email also provided these details.

Regarding Facebook, you'd have to setup a Facebook app with the url of the test shop, to enable Facebook authentication for the shop, however, you shouldn't need to mess with that in order to login as a shop administrator.

**Comment by kosir** [comment]
@aaronjudd thanks aaron, but if I try to login to my test shop with my reactioncommerce email and password I got: wrong password error. If I try to reset my password, I got error:Password must be at least 6 characters long. Then I reset my original https://reactioncommerce.com/account password, restarted my test shop and got Application Not Responding, or just loading screen all the time...

**Comment by kosir** [comment]
I just deleted that shop and created new test shop and I got the same result. When I want to login (inside my shop) with my reactioncommerce email and password, I got Incorrect password error.
