### ISSUE TITLE
Confusing Marketplace Seller Signup Process

### ISSUE THREAD

**Issue by it-all** [reactioncommerce/reaction#3242]
### Expected behavior
There should be a link to "Become a Seller" on the homepage after enabling the Marketplace and Allow merchant signup.

### Actual behavior
A seller is required to Register before seeing the Become a Seller link. This is very confusing and I believe would prevent most seller applications/registrations.

### Steps to reproduce the behavior
Enable Marketplace in the Admin
Check Allow merchant signup

### Versions
1.5.6

**Comment by rymorgan** [comment]
@it-all I agree that the ux here is confusing. It's something on our design roadmap that we know we need to address. At the same time, I think it's a fairly normal marketplace approach to ask a potential seller to register in order to become a seller. I think the UX confusion could be solved around messaging. Maybe, there is a Login/Join link or some messaging that says register to become a seller that shows up in the registration form.

**Comment by aldeed** [comment]
Closing this since marketplace is no longer a core plugin
