### ISSUE TITLE
reactioncommerce site updates

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#333]
I'm receiving the "You've launched a new shop" email every time I click restart from my account dashboard.

Not a big priority, but might be an easy fix.

**Comment by aaronjudd** [comment]
Thanks, I'll update that with the next release. I was wondering what the better approach was, because we're actually archiving the instance if it wasn't running and launching a new instance.  You should only get the email when it rebuilds, but not with a restart where it was running. A little confusing, so I'll just cut out the email from a rebuild as well (or change the message).

**Comment by spencern** [comment]
Actually scratch that, it was on the rebuild. I just rebuilt and then restarted so close together that I perceived it as happening on the restart. Still a bit confusing, so changing the message would be solid I think. Thanks

**Comment by aaronjudd** [comment]
I've just renamed, we can leave this as an issue to track a couple other suggested reactioncommerce site updates as well.

* remove trello footer link, update to waffleboard
