### ISSUE TITLE
Enhancement: Being able to set Tax inclusive on Tax settings

### ISSUE THREAD

**Issue by wackywombaat12** [reactioncommerce/reaction#3342]
It would be really good to be able to set a Tax Inclusive option for Tax Settings.

This would be great for Australian stores as the tax is usually 10% inclusive of price country wide.

I saw that in https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/taxes/client/settings/settings.html#L5 some work has been started on it.

I am assuming that someone had plans for this orginally?

**Comment by aldeed** [comment]
This is one outstanding issue I did not implement with recent 2.0 tax improvements. It would now need to be implemented in the `taxes-rates` included plugin, but it would not be too hard if anyone is interested in submitting a PR.
1. Add `rateIsTaxInclusive` to `Taxes` schema
2. Add a check box field for this to the `"customTaxRates-update-form"`
3. In the `calculateOrderTaxes` function, change the calculation to be tax-inclusive for each tax where this is `true`.

**Comment by derBretti** [comment]
I would like to tackle this issue, since it is very important for my project as well. However, the following point should be discussed.
When the tax inclusive setting can be applied on a tax rate level, the total tax applicable to an order might be partially included in the item total, hence the equation `total = itemTotal + fulfillmentTotal + taxTotal + groupSurchargeTotal - groupDiscountTotal` as used in xformCartCheckout and addInvoiceToGroup would not hold true anymore. 
I see several possible ways to correct this:
1.  Correct the calculations, but keep displayed values as they are such that the sub total includes included taxes and the total tax includes all taxes(inclusive and exclusive). In this case the calculation might look implausible to the user, since sub total and tax would not always add up to the total.
2. Move the tax inclusive flag to the shop settings and treat all taxes as either included in the price or as additional. The sub total would still be the sum of the displayed prices for each item times the quantity, however, the net total should be stated somewhere on the invoice.
3. Calculate the total inclusive and additional tax separately and display both numbers in the summay. This would imply quite a few changes to the schemas and the frontend.
4. Keep the tax inclusive setting on the tax rate level and display either the net or gross value of the individual items in the summary. In this case the calculation would still be plausible. I suggest adding an option to the shop settings to chose which amount to display. This would provide more flexibility than option 2.

**Comment by aldeed** [comment]
@derBretti An example with some numbers would be helpful. I would think that any tax included in `itemTotal` would NOT be in `taxTotal`, thus the math would still work.

**Comment by derBretti** [comment]
Let's ssume we are in a jurisdiction where taxes are usually included and there are items with a total display price of $44, including 10% VAT.
As a customer I would expect the item total to be either $40 (the net price) or $44 and the $4 of taxes to be disclosed in tax summary as required in cases. The calculation would have to change, but everything else would be consistent.

Now we add an item with a display price of $100, excluding a 5% sales tax (I'm not sure if there is real world scenario for this, but the shop allows us to do so if we can set individual tax rates to be inclusive). In this case the total, including taxes, is $149, the sum of all taxes is $9, but the sum of the display prices is $144 (or $140 if we use net prices).
Not including the $4 in `taxTotal` would mean that the tax does not show up anywhere in the tax summay if included in the item price.
Including them would make the tax summary look odd (items: $144, tax: $9, total: $149).
Using net prices in `itemTotal` would make the tax summary consistent (items: $140, tax: $9, total: $149), but the sum of item prices would not add up to `itemTotal` unless we use net prices in which case we would not need the inclusive setting in first place.

**Comment by aldeed** [comment]
@derBretti Thanks, the "to be disclosed in tax summary as required in cases" is the part I wasn't thinking about. The way I'm looking at it, we essentially want the tax calc function to be able to return an "included tax amount" that can be used for display purposes only. It would still return 0 for the `taxTotal`. But we'll need to give this some more thought to figure out any gotchas.

In the meantime if you want to work in this direction (essentially your proposed option 3), that may also help determine if it makes sense.

**Comment by aldeed** [comment]
@derBretti I was also just looking back at this issue description, and I think what you're working on is not quite the same thing. This issue is about tax inclusive rates, whereas you're talking about tax being included in the item price. Both are things that should be supported eventually, but they are not the same thing.

Tax inclusive just means that the percentage is expressed inclusive of the tax itself. So it changes the math to figure out the tax amount, but it has nothing to do with the item price, and it's a change that is isolated to the tax service.

Allowing tax to be included in item prices would also be good, but it seems like a much larger project that may involve tying the pricing engine and tax engine together somehow. I would focus on tax-inclusive flag and calculations in the `tax-rates` package, which should be all that's needed to support a typical VAT situation.

**Comment by derBretti** [comment]
@aldeed Thank you, this clarified things. I'm going to add another feature request for being able to include taxes in the item price.
