### ISSUE TITLE
Incorrect Shopify credentials displays a success message

### ISSUE THREAD

**Issue by cindyfirestone** [reactioncommerce/reaction#3371]
### Expected behavior
If incorrect information is entered into the Shopify connector, I should receive an error message that tells me my credentials do not match or is incorrect. 

### Actual behavior
Currently if I enter in incorrect information into the Shopify connector, I receive a success message. 
Note: the success message appears to be saying that I have successfully entered and saved my Shopify credential, not that I've entered a valid Shopify credentials. 

### Steps to reproduce the behavior
1. Create Reaction shop
2. Go to Connectors
3. Enter in Shopify API information, purposely put in incorrect information in any of the API fields
4. See success message upon hitting save changes.

**Comment by zenweasel** [comment]
@cindyfirestone So when you save you are getting a success message for having successfully saved the settings, not necessarily that the API is a valid one. In order to know what we would need to make an API call and record the results. Do you want us to make an API call on every save or add a "Test Credentials" button like we did for Avalara.

**Comment by tom-gerken** [comment]
It seems like making a test API call when you save would work the best.  That would be the same way the email settings work, correct?  After all, it is unlikely that a user would care if their bad credentials were saved.
