### ISSUE TITLE
Cannot resend emails as an admin if email was successfully sent on the first try

### ISSUE THREAD

**Issue by joykare** [reactioncommerce/reaction#3388]
### Expected behavior
As an admin I should be able to resend emails from the email panel.

### Actual behavior

As an admin, I cannot resend emails from the email panel. This is happening exclusively with emails that have already sent successfully once.

I can only resend emails that were unsuccessful on the first try.

### Steps to reproduce the behavior
- Do not setup email config
- Perform action that sends email, observe that it fails to send
- setup email config 
- resend email, see that it succefully sends
- on the same email try resend it, observe that it fails (status red)

**Comment by iakhator** [comment]
@joykare , I believe an implementation of not to allow a resend if the email is successful would be fine because when email fail it doesn't send email to the user until the failed email is resent. what I propose is that a successful mail sent shouldn't be able to resend unless it is a failed mail. I would lik e to know what is required here.

**Comment by zenweasel** [comment]
@iakhator What if a customer calls and says they didn't get their email? You are going to want to resend it even though our system says it succeeded. "sent" !== "delivered"

You should be able to resend an email for any reason, if it is "succeeded".
