### ISSUE TITLE
Incorrect image shown in product grid

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3399]
### Expected behavior
Image for top-level variant should be the image shown in the grid

### Actual behavior
The first image added shows up in the grid

### Steps to reproduce the behavior
1. Create a product with a top level variant and two options
1. **important** in this order: Add an image to each of the options, and then the top level variant.
1. View the product grid
1. Observe that the image for the option, rather than the top-level-variant displays in the product grid

**Note: Probably no work should begin on this until https://github.com/reactioncommerce/reaction/pull/3368 is merged as the relevant product publication code will change significantly.**

### Versions
```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Reaction: 1.6.1
Reaction branch: master
Docker: 17.09.1-ce
```

**Comment by iakhator** [comment]
@zenweaseal,  I have looked at this issue consciously and with care. The current implementation of `Media` collection  was done in the sense that any image that is uploaded first takes the position to be the top level image which is displayed in the product grid. In the media data there is no way one can differentiate between a top level variant and a lower level variant since it is not specified that is to say that all of the `Media(images)` contains the same properties.

**Comment by aldeed** [comment]
@zenweasel I think this is resolved in example storefront, right?

**Comment by zenweasel** [comment]
Yeah, this bug is for the old product grid that doesn't exist any more.
