### ISSUE TITLE
Shippo: create parcel only considers first item in cart

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3408]
As a user, there's no (observable) behaviour that could describe this issue. Therefore skipping the issue template below..

As a programmer though, the code looks strange and a community member was wondering, if there's something wrong there.

The code in question is: imports/plugins/included/shipping-shippo/server/methods/shippo.js, Line 423:
`shippoParcel = createShippoParcel(cart.items[0].parcel, cartWeight, unitOfMeasure, unitOfLength);`

The user was wondering, why only the first item in cart is used to build the shippo parcel. Is this functionality possibly work-in-progress?

### Steps to reproduce the behavior

**Comment by zenweasel** [comment]
Actually you could probably file this as a classic issue by simply having multiple items in the cart and showing that the rates are calculated by the first item. (e.g. one item is 1 pound, second is 75)

But I believe this was done because what is used there is dimensional weight (the size of the box is usually more important than the weight) so we currently don't have any good way of calculating what the "total size" of a box will be given the dimensions of the various items. Some much more sophisticated code needs to be in there to calculate that based on items per box, average box size, etc. You can't just add these up because it all depends on the size of the boxes, e.g. 1-3 t-shirts are probably the same box, but 30 t-shirts would be a totally different box size. (so even if you had only one item in your cart, you have to use quantity as well)

Generally this shouldn't have a huge impact on the rates (in my experience) because distance is way more important than size, but could if you had items that varied dramatically in size/weight (e.g. a t-shirt, an amplifier)

**Comment by willmoss1000** [comment]
I would suggest this isn't minor, even if the effect on price is small? If the wrong service level is purchased the couriers will not collect. This would render Shippo unusable for marketplace, since the merchants are unable to make amendments.

Perhaps this isn't the place - but I think the Ideal setup would be for each merchant to have access to their own Shippo dashboard. This would i) allow them to make amendments, and mean they are wholly responsible, and ii) solve the issue that the admin is being charged for shipping, but currently the merchants are receiving the funds.

**Comment by zenweasel** [comment]
Bumping up to major

**Comment by zenweasel** [comment]
Closing this bug in favor of the ticket to create a box calculation plugin: #4012
