### ISSUE TITLE
Meteor build isn't deployable using Nginx and Passenger

### ISSUE THREAD

**Issue by gezzz** [reactioncommerce/reaction#3436]
For bugs, please fill out the three following sections completely. For the ticket to be resolved, you'll want to provide as much information as possible.

Are you looking for help with getting started on Reaction? Please go
to our [Gitter room](https://gitter.im/reactioncommerce/reaction) instead.

**Hey Reaction!** Love the shop! I just want the app to work and deploy properly!

I asked questions and provided as much detail as possible on gitter but didn't get any suggestions or possible config changes. The build and/or deploy process seems to be broken or I am missing something critical in the deploy. Ideally this would be a build/deploy using Nginx and Phusion Passenger with no changes to the master branch but I am open to other deployment methods. I have also tried deploying with Docker too which also didn't work for me. I have all prerequisites installed using [https://docs.reactioncommerce.com/reaction-docs/master/requirements](https://docs.reactioncommerce.com/reaction-docs/master/requirements) although the page isnt loading right now for some reason.

### Expected behavior
`meteor build` to bundle a deployable node app out of the box.
I tried a variety of build flags but nothing has worked yet.
`meteor build --server-only ../new_package --architecture os.linux.x86_64 && mv ../new_package/*.tar.gz ./package.tar2.gz` also tried removing the `--server-only` and `--architecture` flags and all configs produce a `package.tar2.gz` which I was able to extract, set all environment variables, etc. I am deploying with Phusion Passenger using [this rough guide line](https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/ownserver/nginx/oss/xenial/deploy_app.html) but the app is still not launching/deploying properly. See screen shots below. 

### Actual behavior
The `meteor build` bundled app is not deployable. I have edited settings in `settings/settings.json` before the build too. I mentioned on gitter that I tried a multitude of config's was able to un-tar `package.tar2.gz` and set environment variables (ROOT_URL, MAIL_URL, MONGO_URL, etc.) in Passenger/Nginx, set my Nginx root folder to `bundle/server` and also tried `bundle/programs/web.browser` the latter seemed closer to loading the app (atleast the minified js files were now linking properly.) I also set the app start script as `bundle/main.js` and `/bundle/programs/server/boot.js` but neither config's worked. I've also gone into the the `bundle/programs/server/` folder and did `npm install --production` and also `meteor npm install --save bcrypt` no errors with npm too all seemed to install fine.

### Steps to reproduce the behaviour
Tried multitude of config changes and asked for help and suggestions on gitter with no response. Nginx/Passenger loads up a blank page with the following errors in the console; Firefox ontop and Chrome on the bottom [https://imgur.com/a/hoxEC](https://imgur.com/a/hoxEC). As mentioned above I was able to remove some of those errors and link the minified js scripts properly.

### Versions
Node v8.9.x LTS
Nginx v1.12.2
Phusion Passenger v5.1.x
Meteor v1.6.0.1
Reaction v1.6.3 + latest cli version (not sure how to check that)
Mongo v3.4.x

If there is any other info or diagnostics I need to provide that could help please let me know and I will reply asap.

For enhancements or other issues, please describe, in as much detail as
possible, how the app should be changed, and how this would benefit other users and developers. 

We're giving away t-shirts, tote bags, and $500 gift cards to anyone who contributes a feature or fixes a bug. Learn more about the [Reaction Hack-a-bug-a-thon](https://blog.reactioncommerce.com/introducing-the-reaction-hack-a-bug-a-thon/).

**Comment by ahsan-munir** [comment]
- [ ] 

- [ ] 

- [ ]

**Comment by jshimko** [comment]
I can't offer any support on configuring Passenger or Nginx, but I can confirm that manually building a bundle and running it works fine.

```sh
# get the latest release of Reaction from Github
# (also installs all Node modules)
reaction init mytest
cd mytest

# if you don't run the app at least once, you need to run the plugin loader
reaction plugins load

# create the production bundle
meteor build --directory ../mybuild

# install modules in the server bundle
cd ../mybuild/bundle/programs/server/
meteor npm install --production

# go to the root of the bundle - ./mybuild/bundle
cd ../../

# set required configs
export ROOT_URL=http://localhost:3000
export MONGO_URL=mongodb://localhost:27017/mydb

# optional custom port because some OS's don't allow running services on port 80
export PORT=3000

# start the app (make sure you're using Node 8.x)
node main.js
# or use the version of Node bundled with Meteor instead
meteor node main.js
```
App is available at http://localhost:3000

Or you can skip all of that manual work and use our official Docker build.  ;)

**Comment by gezzz** [comment]
@jshimko thanks for the walk though this is essentially what I've tried todo! I will attempt your steps on a fresh install and see what happens with the build instead of packaging a tar. I can't get the build to launch with or without Passenger using Node or Meteor. I've also tried to deploy using Docker too! Eventually made it past the error of not being able to bind to 0.0.0.0:80 (as I mention on Gitter) but my container wasn't staying active in the background and was shutting down for some reason even without detaching from console. I also ran into issues with SSL/TLS. I wasn't able to get back into the Docker container console to set up Lets Encrypt. I already have my certs setup using Lets Encrypt with Nginx. I'll report back after replicating your steps above. Thanks again and Happy New Year!

**Comment by gezzz** [comment]
@jshimko followed your steps with a fresh init and I am still unable to launch the bundled app on my system using Node or Meteor. `node main.js` and `meteor node main.js` both produced a blank page that couldn't find resources (minified js and css files). It appears the app has launched in console I just can't see anything in a browser. What should the 'public' folder be set to?

**Comment by jshimko** [comment]
@gezzz Ok, this may be a silly question, but I have to ask... you sure your Mongo database is running and that the app can connect to it with whatever you set as the `MONGO_URL`?  Because nothing will work without that.  And if the build really is broken, there would definitely be some errors in your terminal after starting the app with `node main.js`.  And if the app _is_ working properly, then you should see the default admin user and the sample fixture data get inserted into the database as the app starts up.  Usually after it has been running for 5-10 seconds.  There's a bunch of colored log output of the whole process.  If you don't see that, something before that point is definitely wrong.

I've gone through the whole process that I outlined above several times now and still don't see any issues.  I suspect you're either missing a small detail of one of the steps or there's an error in the logs that you didn't notice.  If you could provide detailed steps you've taken to produce your issue with a fresh clone, I can try to reproduce it on my end.  Otherwise, I don't think there's actually a build issue with Reaction.  I think this is likely a minor detail you're missing.  If these build steps didn't work, our docker builds wouldn't work either because they're doing the exact same thing (which you can see [here](https://github.com/reactioncommerce/base/blob/master/scripts/build-meteor.sh#L19-L35)).

I'd also like to plug our officially supported Docker build one more time... It exists specifically so nobody needs to go through this manual build and server setup process from scratch.  It's a process that can be very error prone and often hard to maintain or update.  With Docker images, you can build versioned images that have everything you need and you can easily roll forward or backward to different versions with a single command.  You can put an nginx container in front of it too.  No manual nginx setup required there either.  You certainly don't _have_ to use Docker, but I guarantee it'll be easier than manually installing/managing everything needed to build and deploy Reaction, Nginx, SSL, etc.

In case you haven't already seen it...
https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker

Anyway... we'll need some detailed steps to reproduce your issue for us to be able to offer any additional recommendations.  Otherwise, I can't currently see any issues happening with manual production builds and have to assume it's a minor detail you missed somewhere.

**Comment by zenweasel** [comment]
@gezzz One suggestion I would have would be to create a dummy project (the built-in sample todo project for example) and try to get the deployed using the method you are attempting to try. That way you could isolate if the problem is actually Reaction-specific.

**Comment by gezzz** [comment]
Hey @jshimko @zenweasel thanks for all your help and suggestions! I am not opposed to using Docker to launch the shop. I would be willing to launch it anyway possible. @jshimko to answer your question, yes, I am able to connect to Mongo via the url, console, etc. I tried running the following docker command ``docker run -p 80:3000 -e ROOT_URL="https://sub.domain.com" -e MONGO_URL="mongodb://localhost/shop" -e REACTION_EMAIL="email@email.com" -e REACTION_USER="user" -e REACTION_AUTH="r3@cti0n" reactioncommerce/reaction:latest`` I get the following error... 
```
=> Starting app on port 3000...

/opt/reaction/dist/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```
Any suggestions to get passed this error?

**Comment by zenweasel** [comment]
Deploying via Passenger is not really supported and there is no real issue with Reaction itself. Still glad to help via Gitter/Forum with trying to get deployed with Docker
