### ISSUE TITLE
Cannot use multiple instances of accounts-ui

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#348]
When an invited organisation user tries to set his password, he will be shown the ```the password must at least 6 characters long``` even if the password is more than 6 characters. It is impossible to set a password.

![screen shot 2015-03-17 at 1 03 46 am](https://cloud.githubusercontent.com/assets/7354143/6674752/e2833606-cc41-11e4-8285-a1e88a8812de.png)

**Comment by aaronjudd** [comment]
Thanks. Yes I saw this one... it would work if the route didn't already display the login box (hidden).  I saw this frequently during the guest checkout test - and have decided the accounts package needs another refactor to allow for multiple display of the login (the meteor default uses 'id' to identify the inputs). I actually also believe I did this once before, and it got edited out, well because it was a mess. Hopefully this time around it's a cleaner update.  A number of things have improved in Meteor, but not necessarily the accounts, so it might be a new package.

**Comment by nikhildaga** [comment]
This issue is also being discussed in meteor :  https://github.com/meteor/meteor/issues/1472

**Comment by mikemurray** [comment]
This also affects https://github.com/reactioncommerce/reaction/issues/427

**Comment by queso** [comment]
Commenting to watch this ticket

**Comment by Aesop7** [comment]
/me just learned from queso that if I comment, I'll be able to watch this ticket
