### ISSUE TITLE
Upgrade to autoForm 0.5.x

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#349]
Task to upgrade to latest autoForm, and test / update all forms.

@aldeed 
I did a little testing, didn't seem to a big task but wasn't sure if you felt a more detailed review might be in order?

**Comment by aldeed** [comment]
I was going to try to do a review/update this week. It shouldn't be too much, but other than the compatibility break stuff, I think you also had some areas that could use the new `update-pushArray` form type.

**Comment by aldeed** [comment]
@aaronjudd currently still waiting on a fix or workaround to some "bug" that autoform was using which no longer works with Meteor 1.0.4 due to MDG "fixing" the "bug". Not sure if you're more interested in AF5 or Meteor 1.0.4, but at the moment they are not compatible. Hopefully can figure out a solution in the next week.

**Comment by aaronjudd** [comment]
I tested a couple of the new forms with`aldeed:autoform@5.0.2` and had them working, but have run across the 'schema' undefined error.  I'm going to downgrade and revert the two forms to work with 4.x and will wait to see what happens before upgrading everything.

**Comment by aldeed** [comment]
@aaronjudd, `aldeed:autoform@5.0.3` should work with new Meteor release now.

**Comment by aaronjudd** [comment]
I'm working on shipping forms update now.@mikemurray do you want to take some other forms just to get used to these.. we can knock this out quickly with two of us.
