### ISSUE TITLE
Perf - Localisation panel is slow to respond.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3497]
### Expected behavior
The panel should be quick to reflect the changes.
### Actual behavior
After toggling any language, there is a lag after which the toggle happens.
![local](https://user-images.githubusercontent.com/7762605/35044335-044e2d4e-fbb6-11e7-80e3-10055c473233.gif)

### Steps to reproduce the behavior
1. Run `reaction`
1. Open `Localisation` panel from Action Menu
1. Toggle any language and observe the lag.

**Comment by kieckhafer** [comment]
@Akarshit Researching into this, it doesn't seem to me like the data fetching / changing itself is slow: I click the toggle, then viewing the meteor dev tools, it seems to take about 1.5-2 seconds round trip for the call to be made, the DB to be updated and then the switch to switch to the correct position.

I agree that the switch delay should be updated. My thought is since the roundtrip seems to be pretty normal, we add a `state` to the switches, and control the visibility with the state, instead of directly with props.

This would create the illusion that it was triggered right away, even though it's technically still running for a second or two in the background.

If you do think that 1.5-2 seconds is too slow to make that data change, then we can think of alternatives.

What do you think?

**Comment by zenweasel** [comment]
2 seconds seems like an eternity. Especially if that is the round trip locally, not taking into account network latency. (yes, nobody asked me)

**Comment by kieckhafer** [comment]
Ok, 2 seconds is 2 long! Will look into other solutions.

**Comment by zenweasel** [comment]
@kieckhafer Yeah, I guess the idea would be for it not to do all that stuff just to toggle a toggle? Could/Should components check a `shouldComponentUpdate` to see if their specific component changed or is that a brute-force method?

**Comment by kieckhafer** [comment]
The issue seems to boil down to the `Router`. Anytime we do `Shops.update`, the `Router` re-renders. Since these toggles are changing shop settings, we run `Shops.update`, the `Router` re-renders, and that delay is what we are seeing.

So I think in this case, a toggle isn't just a toggle, since it updates the Shop settings as a whole, not just package settings inside the shop. 

If the `Router` requires a refresh if shop data is changed, any ideas on possible solutions, aside from using React's state to "fake" the update while it runs in the background.

To me it seems until we use a global state manager, or rewrite the `Router`, there aren't a lot of options.

**Comment by kieckhafer** [comment]
Notes for discussion: It seems like the Router is re-rendering one additional time every time a language / currency is enabled.

The first time you click a toggle, it'll run `x` times (usually 2). The second time, it runs `x+1`. The third, `x+2`, etc.
