### ISSUE TITLE
Multiplying package creation

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#350]
@vkoudela @boboci9 

> Hi Aaron, could you tell me what could be the reason of my packages starting to multiply, I for now have 13 packages for reaction-shipping for the same shopId and several for reaction-paypal as well my checkout page looks like a mess  and not sure where I should debug this, I know they are created with the fixtures but not sure why they multiply on the way?
boboci9 March 19 2015  

I haven't been able to duplicate this, but I think it's highly possible that an out of date register.coffee in some package could cause this.

**Comment by boboci9** [comment]
Hi Aaron, 
I still have this issue and I didn't found the cause for it's occurrence yet. For now I deal with it by deleting the packages table very often so that my app won't get slowed don't. I spent a lot of time debugging this issue but I couldn't find the reason yet, most of the cases the issue appears when I add a package but it won't go away if I remove it so I'm not sure where to look for the issue.
I will let you know if I find out any useful details.

**Comment by vkoudela** [comment]
Same here. I've been trying to find the way how to reproduce this bug, but it acts weird every time so I couldn't write the exact steps how to reproduce it. Currently, when new meteor update is available and I run `meteor update`, there's big chance that packages will start to multiply. After update, every new application build will add new records in Packages collection, and so on. Emptying Packages collection solves the problem. But, I still can't guarantee this is the way how to reproduce it.

**Comment by boboci9** [comment]
I have been debugging this because it started to become very hard to handle if you have multiple shops and I think the issues starts when you have multiple shops, we have the packages multiple times because we have one for every shopId but the system won't stop there but keep recreating them over and over again for every shopId at once I even had around 500 entries in the packages collection instead of around 30 ( 10 packages and 3 shops). Did you try to have more than one shop?

**Comment by aaronjudd** [comment]
from @boboci9 

>Hi @aaronjudd, I think I found the source of the issues #350, is could be coming from the unless line:
```
  unless ReactionCore.Collections.Packages.find().count() is Object.keys(ReactionRegistry.Packages).length
    _.each ReactionRegistry.Packages, (config, pkgName) ->
      Shops.find().forEach (shop) ->
        ReactionCore.Events.info "Initializing "+ pkgName
        ReactionCore.Collections.Packages.upsert {shopId: shop._id, name: pkgName},
          $setOnInsert:
            enabled: !!config.autoEnable
            settings: config.settings
            registry: config.registry
            shopPermissions: config.permissions
            services: config.services
```
form the fixutres.coffee

**Comment by aaronjudd** [comment]
Closed PR https://github.com/reactioncommerce/reaction-core/pull/128
