### ISSUE TITLE
Memoize `getShopId` to Reduce Queries

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#3507]
### Expected behavior
Once the "current" shop id is determined, return a cached version to avoid querying the DB again.

### Actual behavior
On startup, we call `getShopId` more than 900 times
Per request, it's about 30.
(this method makes one or two calls to the database, depending on whether you are logged in and have an "active shop" selected).

### Steps to reproduce the behavior
place a `console.log` statement [here](https://github.com/pmn4/reaction/blob/master/server/api/core/core.js#L313) and [here](https://github.com/pmn4/reaction/blob/master/server/api/core/core.js#L322) to count the number of times we go to the database to get the current shop.

### Versions
master

**Comment by spencern** [comment]
@zenweasel are you or @jshimko going to review this one?

**Comment by Akarshit** [comment]
This might be fixed in #3463 [here](https://github.com/reactioncommerce/reaction/pull/3463/files#diff-e0509424f4672c76deaab12707ba478dR465).
Basically the setShopId is not done when the newId is same as the old one, hence all the multiple calls to `getShopId`(because of reactiveness) are prevented.
But not 100% sure.

**Comment by zenweasel** [comment]
My mistake. Assigning to @jshimko to review
