### ISSUE TITLE
Bug - Shop manager can see packages not given permission for.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#3541]
### Expected behavior
Users in the `Shop Manager` group should only be able to see the packages they have been given permission for.
### Actual behavior
Users in the `Shop Manager` group can see all the packages(irrespective of if they have been given permission for it or not)
### Steps to reproduce the behavior
1. Run `reaction`
1. Invite a user to Shop Manager group.
1. Login as that user in incognito mode and check that the user can see all shortcutBar icons
1. Toggle off the following permissions from the shop manager group: Orders, Email, Tax, Shipping
1. Check that the user can still see those shortcutBar icons.
### Cause
The cause of the issue is that the Shop Manager has admin access([here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/versions/server/migrations/5_update_defaultRoles_to_groups.js#L60) and [here](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/groups.js#L78)).
And [here](https://github.com/reactioncommerce/reaction/blob/master/server/publications/collections/packages.js#L21) we say that admin can see all the packages. So even if some permission is not given to the Shop Manager, he still has the admin permission and thus would be able to see everything.
### Solutions
1. Remove the `admin` role from `Shop Manager` group 
1. Only allow `admin` users to see packages they have permission for.

**Comment by spencern** [comment]
@impactmass @Akarshit 
Right now `admin` acts as a kind of global permission for the shop, similar to `owner`.
For users that should not have access to certain dashboards/"packages" I think we'll need to remove the `admin` role and assign specific roles.

Let's considering removing the `admin` role from the Shop Manager group by default, identifying what problems it solves and any new issues it may create. I think that is probably the right direction, but we need to make sure that any additional issues it creates are accounted for.

I think restricting `admin` users to seeing only packages they have permission for might defeat the purpose of that role, but I can also see why that role is confusing from the UI as it appears that certain privileges are revoked, when a user will still have access because of their `admin` role.

**Comment by impactmass** [comment]
noted @spencern, so we'll go ahead and remove the `admin` role from the shop manager default group, but @Akarshit can we make a note of actions that a user in this group will NOT be able to perform by removing "admin" from it?

**Comment by spencern** [comment]
@Akarshit do you have any progress or updates for this issue?

**Comment by Akarshit** [comment]
@spencern The fix for the issue has already been merged in `release-1.8.0`.

**Comment by zenweasel** [comment]
@spencern it looks to me like this ticket was up to date? We were just waiting for `release-1.8.0` to be ready for it to be closed?

**Comment by spencern** [comment]
@Akarshit @zenweasel thanks for the update, I didn't see that there was an attached PR and it was in the "in progress" column, so I wasn't sure.
