### ISSUE TITLE
Remove "kadira:dochead" Meteor package

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3548]
Work:

- "kadira:dochead" Meteor package is used only in /lib/api/router/metadata.js, which runs only on the client, so we do not need isomorphic. Copy just the client parts of the `DocHead` object (and only the functions we use) into Reaction. Code is here: https://github.com/kadirahq/meteor-dochead/blob/master/lib/both.js
- Remove the kadira:dochead Meteor package
- Move all the metadata code into the core plugin within /imports

**Comment by jshimko** [comment]
FYI, I created a little `addTag` helper to add any kind of tags to the head when I created the custom favicons stuff.

https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/included/default-theme/client/favicons.js

Perhaps that can somehow be used or consolidated in this process.  I only mention it because I happen to prefer the more flexible `addTag` function instead of making a method for each tag type like `kadira:dochead` did with... `addLink()`, `addMeta()`, `addLdJsonScript()`

Maybe we create a new `Reaction.DOM` namespace for this stuff?

```js
Reaction.DOM.getTitle();
Reaction.DOM.setTitle(title);
Reaction.DOM.addHeadTag(type, attributes);
Reaction.DOM.loadScript(src, attributes, callback);
```

Or something.  :)

**Comment by willopez** [comment]
@aldeed @jshimko I agree with Jeremy, this is a good opportunity to consolidate document head utilities. If there are no objections, I'll move forward and create a new namespace, `Reaction.DOM` and move the relevant functions from the meteor package to it.
