### ISSUE TITLE
Copy vsivsi:job-collection package API into the app

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#3551]
Goal: Decrease Meteor pkg deps

Work:

1. Copy the vsivsi:job-collection Meteor package code (https://github.com/vsivsi/meteor-job-collection) into an app plugin
1. Remove the package
1. Ensure that background jobs still run correctly

**Comment by zenweasel** [comment]
If we move it into the app, let's convert it from CoffeeScript? 😛

**Comment by spencern** [comment]
@zenweasel how's the progress coming along on this issue?

**Comment by zenweasel** [comment]
I have not started on it yet, trying to finish up the performance data project first. Will start in the next day or so.

**Comment by spencern** [comment]
I’m going to remove your assignment for now, please reassign yourself once you start.

**Comment by zenweasel** [comment]
Ok, will do

**Comment by aaronjudd** [comment]
We're currently pinned at v1.4 as well, so when we migrate, we'll be updating to 1.5.2.  Since the project is in maintenance mode, I'd say we do go ahead and convert from CoffeeScript in this process.  (It'd be really nice if CoffeeScript was not a dependency!).  I can't remember why we were pinned - other than it was a breaking change, so we'll want to test jobs thoroughly.

**Comment by zenweasel** [comment]
I took a quick look at the files and there is surprisingly little code there. Probably even less if we eliminated the client-side stuff which I don't think we use. (would need to double-check)

**Comment by spencern** [comment]
@zenweasel are you starting on this now?
Pretty sure that we're not currently using the client side stuff.
