### ISSUE TITLE
Error thrown when creating/editing group as shop user with dashboard access

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#3649]
### Expected behavior
Creating / Editing a group should not throw `Error creating group`. It should create/edit group successfully. 

![screenshot 2018-02-05 21 18 51](https://user-images.githubusercontent.com/5229321/35826831-3d6c8b1c-0aba-11e8-911e-6d770f5b27b2.jpg)

### Actual behavior
Creating / Editing a group should throws `Error creating group` when performed by a user other than the shop owner.

### Steps to reproduce the behavior
1. Add a user to shop manager group, and login as that user
2. Try creating / editing a group as that user

Some Notes: 
- This could be a case of user not having required permission. 
- Maybe show a better error message for user not with right permission to perform the action
- Or maybe should not show the edit/create module for users without right permission in first place

### Versions
Node: 8.9.1
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.26.4
Reaction: master

**Comment by prinzdezibel** [comment]
Because editing / creating groups needs the admin rights server side, I'd propose to display the EditGroup component read-only, if this permission is not available.

**Comment by mattt416** [comment]
I don't want to divert attention from this specific bug, but I've seen two additional issues trying to replicate this bug:

1. As a `Shop Manager` user, on the `Accounts` tab I can select `Shop Manager` under `Edit Groups` and can then successfully toggle `Accounts` (to off).  This seems to work but then results in a blank `Accounts` page. The user can't seem to flip this back on and requires the admin user to do so.
2. As any user, when you click on the `Accounts` tab, no group is selected by default under `Edit Groups`. However, there are toggles visible which is a bit confusing and misleading as it's not clear what these toggle.  If, as any user (admin or not), I try to toggle anything without actually selecting a group I get an `Error updating group` flash message.

Should I create separate bugs for these issues?

**Comment by prinzdezibel** [comment]
@mattt416 Yes, please create new tickets. 

I've seen your number 1 as well, but this is some kind of expected. If you're going to revoke yourself the permission to see the current page, you won't see it any longer. But you may file this as issue nevertheless, because maybe we should address this, because it's certainly no UIX best practice.

Also I've recognized number 2 but missed to address this as separate ticket. I've seen code that should pre-select one of the groups. But as you've realized correctly, there's no group selected per default. This is wrong and I guess that has once worked, but now is broken. Would be great if you could file a ticket for that. Thanks!

**Comment by mattt416** [comment]
👍 @prinzdezibel, I'll get these created ASAP.

**Comment by prinzdezibel** [comment]
Merged, going to close now.
