### ISSUE TITLE
currency handling bugs

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#366]
Two areas this seems to be not working:

1- currency symbols are switching (across all pages)

2 - checkout with paypal express shows a conversion issue (maybe be representative of other issues):

![screenshot 2015-04-14 07 41 14](https://cloud.githubusercontent.com/assets/439959/7139310/6951c172-e27a-11e4-8de4-efb6cfaabd49.png)

**Comment by aaronjudd** [comment]
when you set the currency in the core->settings, you are setting that value as your shop base currency. The currency symbol and conversion should be your saved price values adjusted to users locale (so if you are in US you should see $, regardless of the currency format in settings.

**Comment by aldeed** [comment]
When we set the currency value for the express checkout popup (https://github.com/reactioncommerce/reaction-paypal/blob/express-checkout/server/methods/express.coffee#L44), I believe it is to tell them what unit the `AMT` is in. Then the popup shows a conversion if the buyer's paypal account currency is different from that.

**Comment by aldeed** [comment]
Are you saying the `cart.cartTotal()` will already be converted to user's currency rather than shop currency?

**Comment by aaronjudd** [comment]
what is displayed it different from what is stored - the formatting / conversion is client side, view only dependant on locale.  So we should send the shop currency (not the users locale), and paypal will convert from there.

**Comment by aaronjudd** [comment]
Maybe / needs to be resolved https://github.com/reactioncommerce/reaction-core/pull/212

**Comment by zenweasel** [comment]
As it is this bug is a little broad and the issue with currency display seems to be largely gone. I created https://github.com/reactioncommerce/reaction-paypal/issues/21 for the Paypal issues and https://github.com/reactioncommerce/reaction/issues/603 for the one issue I found with currency display and https://github.com/reactioncommerce/reaction/issues/595 for fetching currencies. So I think this issue is well covered.
