### ISSUE TITLE
Inputting refunds while processing orders is difficult, or nearly impossible in some cases

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#3703]
### Expected behavior
When typing a refund inside the dollar amount input box, I should be able to easily input a number that correctly registers in the input.

### Actual behavior
When typing a refund, there are two main issues.
1) Due to what seems like our `currency.js` internationalization of prices, it is hard to type the correct number in the input box, without clicking at the beginning of the number and inputting from there.
2) If I click at the end of the input box (after both cent decimals, i.e. after `.00`, no matter what number I type, the number will increment by 1 cent, making it nearly impossible to get the correct number without clicking again:

### Steps to reproduce the behavior
- Create an order
- Capture the payment
- Create various refunds by clicking at different places inside the refund input box (i.e. `0.00`, click before the first 0, click before the decimal, click after the decimal, click at the end, and try to input a number after each click)

![number increasing mov](https://user-images.githubusercontent.com/4482263/36012799-69e683e8-0d15-11e8-9d73-4eeb08f22652.gif)

### Versions

```
Node: 9.5.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 18.01.0-ce
```

### QA

QA by @kieckhafer + @cassytaylor

**Comment by zenweasel** [comment]
fwiw I have been complaining about this for literally years

**Comment by prinzdezibel** [comment]
@rymorgan I think it doesn't make too much sense to have the $ character in the input field. That way the user can edit it, but the currency is not meant to be changed there at all.

On the other hand I realize that it's helpful to see the this field is going to accept a currency value. So I guess it's also not nice to omit it completely.

The correct way of dealing it would probably be to have the $ character as label text outside of the input control. What do you think?

**Comment by rymorgan** [comment]
@prinzdezibel I think we could approach it in two different ways. 

1. We could leave it out the idea being that the currency is implied by the calculation above. The advantage being we don't have to deal with localization and add more labels and what would that label be? It'd be weird to have the label be just the currency symbol. The disadvantage being some loss in clarity to the user. 
2. We could have an "alternatively displayed" label that makes it clear. Disadvantages being  the need to adust the component and having to deal with some localization with currency labels that are displayed on the right vs the left. 
![screen shot 2018-02-21 at 9 09 44 am](https://user-images.githubusercontent.com/20409254/36494549-2bb669a4-16e7-11e8-80c7-478cbf760f48.png)

I tend to think we should go with option 1 here in order to fix the other bug.

**Comment by rymorgan** [comment]
@prinzdezibel  Ok, dug deeper into this. We are actually doing the number 2 option now. Which I think is the better way to do it. I think what we are missing here is a graphical distinction between the currency and the number. For now, I think you leave it as is and we can work on the graphical distinction in an issue dealing with eh overall input component. 

In other words, ignore my first comment :)

**Comment by Akarshit** [comment]
@prinzdezibel @rymorgan If the design doesn't need to be changed and you still want the currency formatting, you can have a look at #3808

**Comment by prinzdezibel** [comment]
Alright then, @rymorgan. Thanks!

**Comment by prinzdezibel** [comment]
@Akarshit  I like that approach you were choosing. It satisfies the statement from @rymorgan and still does not confuse the admin at the moment he's entering the value.  Going for that route to be consistent.

**Comment by zenweasel** [comment]
Since the issue we are blocked by has an approved PR we can move forward with this again
