### ISSUE TITLE
Import products from Shopify

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#378]
A task to import products, variants from https://docs.shopify.com/api/product

**Comment by nlcluigi** [comment]
I think this is an essential feature but because a lot of ecommerce systems (woocommerce, amazon, shopify) have .csv import/export plugins, why not implement this feature as a ".csv import/ update for products" with shopify being a subcase in this scenario? 
Anyway we need something like this because we will need to create/ update products, prices, qty every day and by having a .csv update feature we will be able to save a lot of time. Can't even think going thru hundreads of products to update qty or listing 100 products manually.

Regards,
Luigi

**Comment by aaronjudd** [comment]
Mongo has a native import/export that I believe will handle .csv files, so there is a way currently to handle import/export.  Also, you can import json using our fixtures methods.  The goal here is to import (and potentially synch) with Shopify (and eventually others).

**Comment by nlcluigi** [comment]
If I would know how to use json with fixtures methods I wouldn't use a CMS :)
Also, Shopify and others mean plain .csv files. That's why speaking about csv's make more sense than speaking about Shopify. Everybody's working with excel/csv files but not everybody use Shopify.

**Comment by markchipman** [comment]
I think Reaction Commerce isn't at a point yet to think about how to (of even "if" it should) transfer content from other systems like woo (MySQL) , shopify (online API), etc... Aaron is right that its very straight forward and easy to map a .csv file to the Mongo collections in Meteor... I suggest you Google this as its not worth the diversion from what the core team needs to focus on.  I think Reaction Commerce strength is in its "ease" of use for non-technical users... this is what needs to be the current focus, and not getting side stepped into 'moving' data from one system to another... You could afterall, re-key all your Shopify data manually into RC. :) That should be on your shoulders... not theirs.

**Comment by aaronjudd** [comment]
@DenisGorbachev is building some tools in a separate project that should help with ETL and importing from other systems.  Core development is focused on getting the "core", and all the necessary workflow steps fully functional.  Once we hit that milestone, I'd like to see how much progress he's made - and we can decide at that time what the next steps should be for import tools.  Of course, some other solution might present itself in the meantime as well.

**Comment by nlcluigi** [comment]
Hi,

Please re-read my statement. I don't use Shopify and I didn't suggest any content transfer feature from other systems. 
Summary: we should be able to use a .csv file in order to import products in RC in a CMS fashion way. 

p.s.: I still think it's a must. You can't list products one by one neither mapping Mongo with Meteor - that's not a CMS way but rather a educated technical approach.

Regards,
Luigi

**Comment by spencern** [comment]
Should be closed by #2584.

@aaronjudd should I create a separate PR for merging the Shopify connector into `development` as well?
