### ISSUE TITLE
Discount codes account limit and total limit not honored

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3783]
### Expected behavior

Discount `Account Limit` and `Total Limit` should be honored.

### Actual behavior

Discount codes can be used past their limits.

### Steps to reproduce the behavior
![cart_completed](https://user-images.githubusercontent.com/42217/36332065-807a8198-1325-11e8-8aa7-b1643e72a9c7.png)

1. Add a discount code in payment settings: see screenshot
2. Check out and apply the code
3. Code should be applied successfully, complete checkout
4. Check out again and apply the code once more
5. The code is applied again and should not be. (Not only is the account limit 1, to total uses is 1 as well)
6. Complete checkout, and view orders dashboard
7. There should be two orders both with the discount applied.

This happens on both `master` and `release-1.8.0` branch.

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.3
Meteor NPM: 5.5.1
Reaction CLI: 0.27.0
Reaction: 1.7.0
Reaction branch: master
Docker: 17.12.0-ce

**Comment by Akarshit** [comment]
This bug is happening because [here](https://github.com/reactioncommerce/reaction/blob/release-1.8.0/imports/plugins/included/payments-example/client/checkout/example.js#L76) `processor: "Example"` is set and [here](https://github.com/reactioncommerce/reaction/blob/release-1.8.0/imports/plugins/included/discount-codes/server/hooks/orders.js#L15) we only add discount transactions to the cart with `processor: "code"`
I think the problem is somewhere in the way we want to store the `paymentMethod` when there are more than one. I tried but couldn't find the right way this should be implemented.

**Comment by zenweasel** [comment]
@aaronjudd 
This is definitely a regression in that it worked when it was implemented (I remember testing it). But in terms of a release are we sure this is working on `master` since in his original ticket @mikemurray notes that it's happening on `master` as well as the release branch?

**Comment by zenweasel** [comment]
@spencern Could we get some direction about how we should store `paymentMethod`s when there are more than one?

**Comment by aaronjudd** [comment]
@spencern updates on this?  I'm not sure how to answer @zenweasel as the discounts were always meant to be added to the paymentsMethods array, just like any other payment, we have always allowed for multiple...

**Comment by spencern** [comment]
Digging in on this now. I thought that discounts were already added to the paymentMethods array.

**Comment by spencern** [comment]
So it appears that we're not currently leveraging the `transactions` array that's stored on an order
```
export const Order = new SimpleSchema({
  ...
  transactions: {
    type: [OrderTransaction],
    optional: true
  },
  ...
```
https://github.com/reactioncommerce/reaction/blob/master/lib/collections/schemas/orders.js#L214
In fact, the only place it seems that we're storing the discount right now is on the invoice within the `billing` array.

![image](https://user-images.githubusercontent.com/1203639/36909972-b81d8ef6-1dfc-11e8-886d-99d3b8123aa2.png)

I'd say we should probably be adding all transactions to this transactions array, as it seems that's where things were intended to go.

I think we could also store the additional transactions in the billing array, right now, the discount appears to be applied to the invoice that is then used to charge users via another payment method.

![image](https://user-images.githubusercontent.com/1203639/36910273-796995a0-1dfd-11e8-9ea1-34000f343dbe.png)

Discount codes could (should?) probably be used to reduce the overall amount that is being passed to the next transaction, e.g. you could have a billing or transaction array that might look like this:

```
Cart amount: $100.00 ($80.00 subtotal, $10 shipping, $10 tax)
⬇️
Discount code: SAVE10 ($10 credit) - new cart amount $89.00 ($70 subtotal, $10 shipping, $9 tax)
⬇️
Discount code: SHIPFREE (100% discount shipping) - new cart amount $79
⬇️
Stripe transaction of $79
```

I think we'll have to have some type of model like this in order to support multiple discounts + gift cards + customer credit + points / loyalty rewards etc.

@zenweasel @aaronjudd does this help?

**Comment by zenweasel** [comment]
@spencern Yeah, that helps a lot. I think that gives us what we need to move forward. @prinzdezibel This is going to be a change that probably touches a lot of places so let's maybe work together on testing/testing plan

**Comment by zenweasel** [comment]
@Akarshit @prinzdezibel Can you help me understand what is up with this ticket? We had a question about handling multiple payment methods but we also have an approved PR?

**Comment by Akarshit** [comment]
I was working on this initially but then I figured out it involved changing too many things to do it right. So I unassigned myself and added the `core-bug` label so that core team could take a look on this.

After that I *think* @prinzdezibel solved the problem somehow in the PR.

**Comment by prinzdezibel** [comment]
Here are some investigations I found today.

After digging deeper, I can say the following:
- The PR does resolve the issue at hand
- Discounts feature does not and did not work within a marketplace setup. This feature was in mind, but not implemented yet.
-  `billing[0]` access into the billing array is done all over the place, because one can assume safely, that the data is available in a denormalized manner everywhere (billing[0].address === billing[1].address === billing[n].address). 
![screen_shot_2018-03-06_at_13_46_59](https://user-images.githubusercontent.com/1733229/37035466-f0e7355e-214c-11e8-82a2-7b71446d4642.jpg)
