### ISSUE TITLE
Can't make product visible when revisions are turned off

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3978]
## Issue Description
This might be user error, but if there is a way to make the product visible when Revisions are turned off I can't find it.

## Steps to Reproduce
1. Login as admin
1. Go to Catalog dashboard panel and disable Revisions
1. Add a product
1. Observe the visibility button is not available in the header
1. Observe that `isVisible` is set to `false` in the db so the product is not shown in the product grid

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce
```

**Comment by zenweasel** [comment]
Well, I've gone back to v1.5.0 and products are still not visible when created so either I don't know how to make products visible or this has been broken for a long time.

**Comment by zenweasel** [comment]
I guess this can't be a critical if nobody has noticed it in forever.

**Comment by prinzdezibel** [comment]
Not sure this is a but per se, because there's an alternative way to make products visible/non-visible. Could be that one was supposed to toggle visibility in the "grid settings" from the beginning of time, although would admit that this is a bit awkward. 

One can verify this works through navigating to the PDP, e.g. 
http://localhost:3000/product/example-product

The reason why the products are not visible in the product grid (home page) is another one which is covered in this separate issue: #4001. 


![reaction](https://user-images.githubusercontent.com/1733229/37399590-5d17165a-2782-11e8-9637-b5ebbe63e4f3.jpg)

@rymorgan  Please provide guidance if the current behaviour is ok or not. If not, how should this functionality look like from a UIX perspective? Thanks.

**Comment by prinzdezibel** [comment]
I guess this is a impact-minor, because there's a workaround.

**Comment by prinzdezibel** [comment]
Because 4001 turned out to be a non-issue, this issue is really about the missing publish button. This means it's not possible to publish products right now. Re-labelling as impact-major.

**Comment by rymorgan** [comment]
From a design standpoint we should show the eyeball in the publish bar and have a trash can icon as well. In this scenario, for all intents and purposes, you would be deleting the product.

![visibility no revisions](https://user-images.githubusercontent.com/20409254/37534628-9a304e40-2902-11e8-81dd-966e0aaa2ff3.png)

**Comment by prinzdezibel** [comment]
@rymorgan  AFAIK – from a technical standpoint, i.e. the way the application works right now – there's the need for a "Publish" button AND a "eye-ball" even in the case that product revisions are turned off.   @mikemurray, can you confirm my thoughts on this?

**Comment by prinzdezibel** [comment]
Looking a bit deeper into this it's clear to me that there should be some architectural decision on how to proceed with this.

The culprit is the following:
Right now the `Products/grid` publication (used for non-admin grid view) get its data from the `Catalog` collection. This means that there's a direct dependency not only on the `Catalog` collection, but also on functionality in the `catalog` plugin. For instance, even if the catalog plugin is not installed you'd need to have access to the publish functionality to get the Catalog collection populated. In Reaction's current state it's not possible to just delete the catalog plugin and have the program working properly.

So there are at least two obvious possibilities to deal with the situation:

Option a)
Move `publishProductToCatalog` (and possibly some helpers) out of the catalog plugin into core. That would allow us to publish products (read populate Catalog collection) even if Product Revisions are turned off (or the plugin code is missing completely – once we're moving to NPM)

Option b) 
Don't use the Catalog collection for data retrieval when Product Revisions are turned off.

**Comment by prinzdezibel** [comment]
@spencern I'd like to hand this over to the core team to decide on how to deal with it.

**Comment by zenweasel** [comment]
@prinzdezibel I am unclear on why you think either `catalog` or `revisions` would be optional plugins since they are both located in `core`. The purpose of things being in core is that they cannot be removed so I don't think we need to do any engineering to handle their possible removal.

**Comment by prinzdezibel** [comment]
@zenweasel thanks, Brent. I somehow overlooked that catalog functionality is in core. Going to re-assign to me and work on it.
