### ISSUE TITLE
What's with the paypal-debug-id returned in the terminal?

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#409]
Configured PayPal. Clickig on the paypal button does nothing. Entering the detailsa and pressing the button doesn't do anything. other than the paypal-debug-id returned in the terminal. What is that?

**Comment by aaronjudd** [comment]
just to capture the essence of the discussion from gitter:  the paypal-debug-id  is output from the node package ( I believe when connecting to sandbox, but not sure) - this is for paypal support (not sure, but I think you might be able to reference this in the transaction logs as well).  If nothing is happening, take a look at console logs in the browser. This is most likely caused by a configuration/credential issue, however we handle the errors right now beyond resubmitting the payment. It could also be related to #393
