### ISSUE TITLE
Currency is always USD

### ISSUE THREAD

**Issue by abhisheksoni27** [reactioncommerce/reaction#412]
I have changed it in Settings to INR.

But on the product list page, it still shows the price entered in dollars.

Also,when a product is clicked and its own page opens, the currency is converted to US Dollar equivalents, but still the currency is shown in dollars.

Any news or way to change it, so that it always shows INR, and hence can be forwarded to the payment gateway?

**Comment by Gouthamve** [comment]
I am currently tracking this. I think this is an issue with the ```getLocale``` method.

Even when the currency is INR, its returning $ instead of rupee symbol

**Comment by Gouthamve** [comment]
Wait everything is working fine actually! 

You need to change the address of the shop to India in shop settings. Please try that and check.

**Comment by aaronjudd** [comment]
I think you have to refresh the page after setting as well.

**Comment by Gouthamve** [comment]
Hmm, true, but there is still some issue. 
It is not being set on load. Like I have to open a product page for the currency to change.

Like when I reload, I see dollar (refreshing the front-page doesn't change anything). I have to go to a product page for the currency to change to Rupee.

Hopefully a small fix.

**Comment by Gouthamve** [comment]
Figured it out.

So currency info is taken from the formatPrice function here: [Link] (https://github.com/reactioncommerce/reaction-core/blob/8ba0b77cb519831d492b4286583b75d937a3bd05/client/helpers/i18n/i18n.coffee#L145-158) which uses ```ReactionCore.Locale```

ReactionCore.Locale is set by this function: [Link] (https://github.com/reactioncommerce/reaction-core/blob/8ba0b77cb519831d492b4286583b75d937a3bd05/client/helpers/i18n/i18n.coffee#L64)

The bug is, ```formatPrice``` is being called before ```getLocale``` and I have no idea how to make it reactive.
