### ISSUE TITLE
Investigate and improve Catalog schema

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4185]
The basic idea here is to look at what the starterkit frontend actually ends up using and needing, both for grid and PDP, and then go back and adjust GraphQL schema and write some migrations to make everything line up. In general:

- `Catalog` collection should be renamed to `CatalogItems`, and they should have a `catalogId` property.
- Probably move all of the product fields down into a `product` object on each item, to match the graphql schema
- Create a new `Catalog` collection which currently will have exactly one auto-created "primary" catalog per shop
- Add `productId` field rather than relying on `_id` matching
- Examine the way `media` array is put onto catalog items and potentially change it. Rename as `images` since they're currently only images. Maybe load them dynamically in resolvers instead of denormalizing. I am concerned about the root URL being stuck in those URLs. Would it be better to have variant images on each variant? Also adjust the object structure to match GraphQL and don't store metadata that isn't necessary.
- isDeleted: does this make sense on catalog? Couldn't we hard delete from catalog collection when you publish a delete, and re-create it if you publish an undelete?
- rename `hashtags` to `tagIds` and `handle` to `slug` to match GraphQL schema (or vice versa)
- createdAt/updatedAt: Make sure that these are tracked separately to represent the catalog item being created / changed rather than just being identical to the related product
- positions: Is this the best object structure, and should this be a property of the catalog item rather than the product in the GraphQL schema?
- do we need/use/want all other catalog product fields, and do any need to be renamed to clarify what they are for? e.g., `weight`
- While doing this, add descriptions for all fields in the catalog.graphql file.

 ----------------------------------------------------------------------------
Below was added by @spencern when transforming this ticket into an epic

It should be completed in tandem with #4189 and refers to the renamed `catalogItem` schema.

#4189: Migrate data from `Catalog` => `CatalogItems`
 - Delete existing catalog records afterwards

The `catalogItem` schema

#4192: Create new `product` field and move the existing fields associated with the product into the `product` field.

#4193: Change the `product` part of this schema to use `tagIds` in place of `hashtags` and `slug` instead of handle. 

#4194: Add the following fields at the `catalogItem` root:
```
_id: String
catalogId: String
isDeleted: bool
isArchived: bool
isVisible: bool
tagIds: [String]  // changed from hashtags
updatedAt
createdAt
```

#4195: Change the positions map into an array, move it to the catalogItem root and to add the other merchandising data into it. Maybe consider changing the name from positions to `merchandising` or something more clear that it involves positions, grid size (display weight), etc

e.g. 
```
merchandising: [ProductMerchandising]
```

```
/**
 * @name ProductMerchandising
 * @memberof schemas
 * @type {SimpleSchema}
 * @property {String} tagId // renamed from tag which was a slug, let's consider using tagId instead?
 * @property {Number} position optional
 // Current position doc includes `pinned` which doesn't appear to be used used on current UI, so I'd vote to burninate.
 * @property {Number} displayWeight optional, default value: `0` // renamed from 'weight', open to other name suggestions
 * @property {Date} updatedAt required
 */
export const ProductMerchandising = new SimpleSchema({
  tagId: {
    type: String // Was optional before, don't think it should be
  },
  position: {
    type: SimpleSchema.Integer,
    optional: true
  },
  displayWeight: {
    type: SimpleSchema.Integer,
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 3 // Do we need a max?
  },
  updatedAt: {
    type: Date
  }
}
```

#4196 Update the product publication methods and any code that pushes data to the catalog to strip variants that are deleted (`isDeleted: true`) from the publication and to use the updated catalogItems schema.

#4197 Create a migration to migrate data from an existing shop that has the old `catalog` collection to the updated `catalogItems` collection.

**Comment by ticean** [comment]
From team discussion:

- `Catalog` collection should be renamed to `CatalogItems`, and they should have a `catalogId` property.  
- Create a new `Catalog` collection which currently will have exactly one auto-created "primary" catalog per shop  

We agreed that we should do this. @aldeed will attempt to make those modifications on completing the catalog graphql functionality.

---

- Probably move all of the product fields down into a product object on each item, to match the graphql schema
- Add productId field rather than relying on _id matching

----

* createdAt/updatedAt: Make sure that these are tracked separately to represent the catalog item being created / changed rather than just being identical to the related product

All agreed.

---

* isDeleted: does this make sense on catalog? Couldn't we hard delete from catalog collection when you publish a delete, and re-create it if you publish an undelete?

@ticean recommended keeping isDeleted for easier transport of deleted records to external systems, like search here.

We discussed the isDeleted attribute and whether it should go on the product or the catalogitems. Decided that it should go on both.

---

* positions: Is this the best object structure, and should this be a property of the catalog item rather than the product in the GraphQL schema?

We all agreed positions should go on the CatalogItem.

Position supports a setting per category. Also agreed to change the positions from a map to an array. @aldeed noted that the weight is not part of that and we agreed that we should combine the weight and position.

We liked the idea of creating sorts freely from tags and other entities. But didn't resolve a full design for that.

---

* do we need/use/want all other catalog product fields, and do any need to be renamed to clarify what they are for? e.g., weight

This is currently the size of the display. We agree that this should be more clear. Potentially change to `displayWeight`.

---

* add descriptions for all fields in the catalog.graphql file.

All agree.

@ticean to include descriptions from the design process and to create the design to a branch for discussion.

**Comment by ticean** [comment]
* rename hashtags to tagIds and handle to slug to match GraphQL schema (or vice versa)

All agreed!
