### ISSUE TITLE
Add a hash of published product properties to all top-level products

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4264]
## Work
- As part of publishing a Product to the Catalog, create an object hash of all of the properties that should be considered "changed". This will be most properties, but not system-managed properties like `updatedAt`.
- Save that hash onto a new property on Products collection, on the top-level product only. Name can be something like `publishedProductHash`
- Ensure that that field is being published to client code when an admin is logged in ("Products" publication)
- Add a migration that calculates this field for all existing CatalogProducts and saves it onto their related Product document.

The remaining client work will be done in #4281 

## Testing
- Create a Product and publish it. When logged in as admin, ensure there is a published product hash property on the related Product in client code.
- Create Products in the base branch and publish them. Update to this branch and ensure that migrations run. Ensure that all Products have a published product hash property in client code.

**Comment by aldeed** [comment]
Whoever does this, note the potentially-related changes in https://github.com/reactioncommerce/reaction/pull/4073

**Comment by kieckhafer** [comment]
How is this going to work to compare hashes? It seems we are saving the hash on the original publication of the product to the catalog, but then seems like we might just be overwriting the hash the next time the product is published.

How are we able to compare and see that the hash has changed? Is that done prior to updating the hash? And if so, where do we save the info that the hash has been changed?

**Comment by aldeed** [comment]
@kieckhafer When publishing, you'll hash all the properties we care about for the product and save it on the `Product`. Then, when an admin is editing that product, client code will dynamically re-hash those same properties and compare to the saved hash. So we only ever need the "last published hash" stored because the "current product hash" is generated as needed from the product doc. (That comparison stuff is all part of #4281, not this issue.)
