### ISSUE TITLE
Catalog integration test to use Factory mocks

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction#4284]
## Issue Description
The Catalog GQL integration test has an entire folder of hand-coded mock objects. These mocks need to be replaced with the new Factory test util.

**Comment by trojanh** [comment]
@aldeed is this relevant? can I work on this?

**Comment by aldeed** [comment]
@trojanh Still some stuff to do here, yes. Specifically:

- In `tests/mocks` folder, there are four files, which are imported into `tests/integration/api/queries/catalogItemProduct` and `tests/integration/api/queries/catalogItems` tests. It would be good to move these closer to where they are used, maybe in `tests/integration/api/queries/catalogItems` since that is more the pattern lately. `mockShop` and `mockTags` files can possibly be deleted entirely and contents moved to the files that import them. Goal would be to delete the `tests/mocks` folder.
- Within those mock files, particularly `mockCatalogItems.js` and `mockCatalogProducts.js`, the mocks are much larger than they need to be. You can combine factory functions such as `Factory.CatalogItem`, `Factory.CatalogProduct`, `Factory.CatalogProductVariant`, and `Factory.CatalogProductOption` to create the objects, which will auto-fill most of the field values. You can provide override values for those that need to be something specific. Search for `Factory.CatalogProduct` in other tests for examples.
- After above changes, some of the test expected objects or snapshots may need to be updated because the field values are different, etc. This is fine to do as long as the test is still testing what it says it is testing.

**Comment by trojanh** [comment]
great, thanks @aldeed , I will create a PR for this soon. 

One question: `catalogItemProduct` and `catalogItems` query both do not take shopId as input, any reason to not include it or do we plan to do it soon?

**Comment by aldeed** [comment]
@trojanh `catalogItems` takes `shopIds` array, which seems like the same thing. `catalogItemProduct` probably does not take `shopId` because we usually include it in order to do permission checks (most permissions are shop-specific), but `catalogItemProduct` has no permission checks because it's meant to be public. It's not a bad idea to add `shopId` everywhere for consistency, but I don't know if everyone will agree. You could propose it in a separate issue if you want.

**Comment by trojanh** [comment]
thanks @aldeed for the clarification. 

I had noticed `shopIds` for `catalogItems` later and forgot to update the comment here, but does ` shopIds` array mean that we can display multi-shop products(`catalogItems`) alongside and use it for cart and orders later? I mean does our system support adding products from another shop to the cart which is specific to single `shopId`? That would be interesting. 

Maybe there's some other intention to allow `catalogItems` not specific to a single shop, I guess which I might be missing.

**Comment by aldeed** [comment]
@trojanh Great question. In the early days of the 2.0 release, there was a thought of supporting multi-shop carts and orders. We decided not to prioritize it yet, but the idea is that you *should* be able to build something custom off Reaction that does support that. I think to do it right now, you would have to do a lot of reconciling in storefront browser code. In other words, you could display products from multiple shops, and behind the scenes add them to multiple shop-specific carts, displaying them all together and adding up the totals. Then check out each one separately, or somehow do a single checkout flow but in the end call `placeOrder` mutation once per shop.

The other reason for `shopIds` instead of `shopId` is for admins. Right now the multi-shop support on the admin side is not great, but after 3.0 we hope to improve it. This would allow admins to manage multi-shop catalogs, fulfill orders across multiple shops, etc. I suspect that we'll end up adding `shopIds` param to most of the queries that return a connection, but it's a long way until that will be fully featured.

**Comment by trojanh** [comment]
Great thought @aldeed, makes total sense. This must be good for scalability as well.
