### ISSUE TITLE
Archived products don't get removed from the Catalog

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4347]
## Prerequisites
* [x] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Products that have been archived may still appear in the catalog to customers.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. As an operator publish a product
2. As a customer load the product grid and view that product
3. As an operator archive and publish that same product
4. As a customer, check to see if the product is still visible in the grid

## Possible Solution
It seems that the product publication method may not consider archival status for products, variants, and or options.

### Versions
```
Node: 9.11.1
NPM: 5.6.0
Meteor Node: 8.11.2
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.0
Reaction branch: release-1.13.0
Docker: 18.03.1-ce
```

**Comment by aldeed** [comment]
As far as I can see, both `createCatalogProduct` and the Meteor "Product" publication are correctly filtering by `isDeleted` for products, and variants do not get included in the catalog product if they're deleted. Whoever takes this should add some Jest integration tests to try reproducing this and validating a fix.

**Comment by kieckhafer** [comment]
Just writing some notes in there, and confirming what @aldeed said, that it does look like code-wise, the publication looks like it should be filtering correctly.

That being said, I can reproduce the issue, and it's occurring both in the core app, and in the GraphQL query / starterkit, so my inclination is it's probably the publication not filtering correctly. 

Still digging in...

**Comment by kieckhafer** [comment]
Don't know the reason behind it yet, but the issue is the `isDeleted` data is never getting updated in the `Catalog` product when a product is archived. As Eric mentioned, `createCatalogProduct`'s code looks correct, and it _should_ be updating the `isDeleted` field, however that field always stays `false` in the Catalog no matter what is published from the `Products` collections.

When I manually update `isDeleted` to be `true` in the `Catalog` collection, the product is removed from both the next starterkit, and a logged-out user on the core app, so at least we know the publication is working correctly.

Still digging in...

**Comment by kieckhafer** [comment]
Ok... So I think....

When a product is archived, the first thing that happens is it is updated in the `Products` collection to be `isDeleted: true`.

It then is removed immediately from the display in Admin mode, so you don't have a chance to "Publish" the product to the `Catalog` collection, so the product in the `Catalog` collection never gets that updated `isDeleted` value.

Even when you "Publish All", from the Product grid, you're only publishing the products that are available inside the `Products` publication, since the Admin gets the `Products` publication, while a non-admin gets the `Catalog` publication. Since the `isDeleted: true` is updated in the `Products` collection correctly, it's no longer on the grid, and therefore isn't published when you `Publish All`.

I think the solution is going to be to update the `Archive` function to pass the `isDeleted` data to the Catalog collection as well, so that it gets done even when the product is no longer available to an Admin.

**Comment by kieckhafer** [comment]
It also seems this issue is only when a product is archived via the PDP, which may explain why it's not 100% reproducible.

Because the PDP is reactive, as soon as you archive the product, the page refreshes and the product is gone.

However, because the Grid is not reactive, if you archive the product from the grid, it's still sticks around until you navigate away and head back to the grid. So if you archive from the grid, you can then `Publish` from the grid, and the data will correctly be published since the grid still has now deleted product visible.
