### ISSUE TITLE
Generate dynamic sitemaps on recurring schedule.

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#4353]
## Summary
Create recurring job to generate sitemaps for product pages and tag/category product grid pages.
We need to be generating a `sitemap.xml` that site operators can submit to Google's webmaster tools, prerender.io, etc.

## Suggested approach
We should create a job to generate a dynamic sitemap.xml file that can be updated on a recurring basis. This initial sitemap should have the index `/` route, as well as all PDP routes and tag product grid routes.

The tag routes should be generated from all visible tags.

We should generate a PDP route for each visible, non-archived product in the Catalog.  We will not generate routes for variants or options at this time.

We should be able to look at this meteor plugin to get some ideas for how to do this quickly.
https://github.com/gadicc/meteor-sitemaps

Here's a next.js example from @nnnnat: https://gist.github.com/evantahler/ba75e277c756fce337b7370035b298e7

This initial approach can be focused on single-shop instances, but we would welcome a PR to add support for multi-shop marketplaces as well.

The solution here should work on the starter kit as well.

**Comment by vwadher** [comment]
@spencern since we now have a robots.txt file - as a 1 time update when the sitemap file is created for the first time, the robots file should have this directive added to it - 

sitemap: [absolute URL of the sitemap.xml file]

**Comment by spencern** [comment]
The solutions team has requested that we leave this issue for them.

**Comment by zenweasel** [comment]
@dancastellon As we discussed, one thing to consider is that this will get generated on one machine, but in a production environment would need to get served by all instances, so just writing out a local file to the filesystems would not work in most cases.

**Comment by zenweasel** [comment]
@dancastellon Possibly we could look at using the `updatedAt` field to only update products/tags that have been updated since the last regen, or possibly skipping regen when nothing has changed.

**Comment by vwadher** [comment]
@zenweasel @dancastellon you also want to consider products that get removed entirely. Those urls will serve a 404 error if they exist on the sitemap file. So need to trigger an update upon removal of products too.

**Comment by dancastellon** [comment]
@zenweasel & @spencern - See my approach below and feel free to let me know your thoughts:
- Add a setting to Admin -> Shop -> Options labelled "Sitemap refresh period" that defaults to "every 24 hours"
- Create a new Sitemaps collection
- _id: String
- shopId: String
- type: String (index or sitemap)
- xml: String
- createdAt: Date
- Create a new included plugin named sitemap-generator
- Create a job that generates XML for sitemap(s), that includes home/index route, PDP routes, and tag grid routes. Job should generate both the sitemap index XML, and XML for sitemaps themselves
- Job will only regenerate sitemap(s) if there are tags or products that have been created or updated since the last time sitemaps were generated
- Each generated XML sitemap string will point to max 50k URLs (sitemap limit), and use "BASE_URL" instead of the actual base URL (So that Storefront can load these records via GraphQL & replace BASE_URL w/ storefront's URL)
- Each XML sitemap will be stored in the Sitemaps collection, with a reference to the shopId
- For the Meteor sitemap:
- Update robots.txt to point to a sitemap index route
- Sitemap index route will return XML that points to routes for each sitemap - https://www.sitemaps.org/protocol.html#index
- Individual sitemap routes will load the XML from the Sitemaps collection, replace "BASE_URL" with Meteor.absoluteUrl() and return the XML
- Storefront implementation TBD (will create separate issue in starterkit repo). Rough idea is that Storefront will load sitemaps via GraphQL.

**Comment by spencern** [comment]
@dancastellon this looks like a great start.

I see you're including `shopId` is it worth including shop slug? How could this be made to work for a marketplace install with some customization?

**Comment by ticean** [comment]
Hi @dancastellon. Are you planning an interface to generate a sitemap on demand? I think that we should implement this *before* the scheduling interface; at least include it as a first-class item in the initial release along with the scheduler.

Without an on-demand interface this will be more difficult to inspect and debug as we'll be at the mercy of the scheduler to see the latest results. And without it site admins will have to wait up to 24h for their changes to appear in sitemap?

**Comment by dancastellon** [comment]
@spencern What would be the benefit of including the shop's slug? One downside I see is that if the slug is changed via the UI, we'd have to have additional logic to update it in the new Sitemaps collection. I feel like to start, I should have my sitemap generation function take an array of shopIds to generate sitemaps for. Initially it will just be the main shop _id, but later we can easily update it to include multiple shop _id's.

@ticean That's a great point, I will include a button to generate/regenerate the sitemap(s) on demand.

**Comment by spencern** [comment]
@dancastellon that makes sense. 👍

**Comment by vwadher** [comment]
@dancastellon note that if multiple sitemaps need to be generated due to the 50K limit then you will need to generate a "sitemap_index.xml" file which will then reference the rest of the sitemap xml files. Example of a sitemap index file : 

<?xml version="1.0" encoding="UTF-8"?>

<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

   <sitemap>

      <loc>http://www.example.com/sitemap1.xml.gz</loc>

      <lastmod>2004-10-01T18:23:17+00:00</lastmod>

   </sitemap>

   <sitemap>

      <loc>http://www.example.com/sitemap2.xml.gz</loc>

      <lastmod>2005-01-01</lastmod>

   </sitemap>

</sitemapindex>

And looks like SDI currently is leveraging this too - https://us.sportsdirect.com/sitemap.xml
