### ISSUE TITLE
Indexes missing in stock reaction

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4407]
## Issue Description
From the results of load-testing, it seems that the following index need to be created for a production site to work.

1. `db.Catalog.createIndex({ createdAt: 1 })`
1. `db.Catalog.createIndex({ "product._id": 1 })`
1. `db.Catalog.createIndex({ "product.variants._id": 1 })`
1. `db.Catalog.createIndex({ "product.variants.options._id": 1 })`
1. `db.Products.createIndex({ "ancestors" : 1 })`
1. `db.Orders.createIndex({ cartId: 1, userId: 1 })`
1. `db.Jobs.createIndex({ status: 1, expiresAfter: 1 })`
1. `db.Assets.createIndex({ type: 1 })`
1. `db.users.createIndex({  roles: "hashed" })`
1. `db.users.createIndex({  "roles.__global_roles__": 1 })`
1. `db.users.createIndex({  "roles.J8Bhq3uTtdgwZx3rz": 1 })`
1. `db.Accounts.createIndex({ groups: 1 })`
1. `db.cfs.Media.filerecord.createIndex({ "metadata.type" : 1 })`
1. `db.cfs_gridfs.small.chunks.createIndex({ files_id: 1, n: 1 })`
1. `db.cfs_gridfs.image.chunks.createIndex({ files_id: 1, n: 1 })`
1. `db.cfs_gridfs.large.chunks.createIndex({ files_id: 1, n: 1 })`
1. `db.cfs_gridfs.thumbnail.chunks.createIndex({ files_id: 1, n: 1 })`
1. `db.cfs_gridfs.medium.chunks.createIndex({ files_id: 1, n: 1 })`

Will it make sense to include some of these(if not all) in the stock reaction code.
If this is not included in stock `reaction` can we at-least mention these indexes in the docs?

### Versions
v1.13

**Comment by aldeed** [comment]
For Catalog, I think we more often look up by `"product.variants.variantId"` and `"product.variants.options.variantId"` rather than `"product.variants._id"` and `"product.variants.options._id"`. But a solution to that better than indexes on all of these would be saving a `productIds` array at the top level of the catalog item (indexed) and querying that. Then all of the queries should be faster in general, too.

After my current PR is merged, the orders one should be `{ cartId: 1, accountId: 1 }` rather than `{ cartId: 1, userId: 1 }` because user -> account.

**Comment by spencern** [comment]
@aldeed thanks for reviewing this. Your proposal to save productIds at the top level makes sense as well. 👍

**Comment by spencern** [comment]
My current understanding is that we index via Collection2/simple schema/simple schema index, but that may be out of date now. 🤔

**Comment by zenweasel** [comment]
@spencern No, you're correct, but I was hesitant to hardcode a bunch of new indexes into the code since indexes have a cost as well as a benefit and not everybody may need them depending on how they use the app. Also I don't know if SimpleSchema supports hashed and composite indexes.

**Comment by aldeed** [comment]
@zenweasel I'm pretty sure that SS index package supports most types of indexes, but I didn't write most of it. That said, I'd prefer that we remove that package and remove all of the `index` and `unique` from all schemas, and then have a single file that runs on startup where we explicitly import the `rawCollections` and call `createIndex` as necessary. It may be that it should eventually be moved out to its own app or script, but I'd rather start with this one small step in that direction.

Note that whoever does this should name every existing index explicitly to match what they are currently named, including the `c2_` prefix. Otherwise we might get duplicate indexes or errors.

**Comment by spencern** [comment]
@zenweasel I think he means the Schema Index package (https://github.com/aldeed/meteor-schema-index) which is separate from simple schema but included automatically with Collection 2

**Comment by zenweasel** [comment]
@spencern ah,got it. Thanks

**Comment by aldeed** [comment]
It's no longer included automatically with C2. It's in our Meteor packages list and we can remove it if we remove all of the `index` and `unique` from all schemas.
