### ISSUE TITLE
Product price range shows up undefined

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4467]
## Issue Description
When you add a product and you publish it the product shows up as `$NaN.undefined` when you view the site as an anonymous user

## Steps to Reproduce
1. Create a new product
1. Make it visible and publish
1. Observe that the price is `$NaN.undefined`

![2018-07-20_09-48-45](https://user-images.githubusercontent.com/72819/42978912-1c48e876-8c02-11e8-8d68-40cb4da2d627.png)

## Possible Solution
It looks like making the top level product visible is no longer make the variant/options visible any longer.

### Versions

Release 1.14.0

**Comment by hrath2015** [comment]
I  dig into it a bit further  and found that, It happens,  when  product is published without  any variant details. 
It will not occur if at least, **variant title and price field** is entered on product admin UI.
Sending a PR soon.

**Comment by zenweasel** [comment]
I am still seeing this even when I enter all variant details. I can repro 100% of the time

**Comment by hrath2015** [comment]
I did try it on Fresh Clone and found it to be inconsistent:
 
- Created and published 2 products with 1 variant each,  variant was not made visible.  can reproduce.

- while debugging, put some `console.log `  in https://github.com/reactioncommerce/reaction/blob/dadb5939d9065b31ad745e1721a18f04e507fac7/imports/plugins/included/product-detail-simple/client/containers/publish.js#L23 and  https://github.com/reactioncommerce/reaction/blob/dadb5939d9065b31ad745e1721a18f04e507fac7/imports/plugins/included/product-detail-simple/client/containers/publish.js#L31

and surprisingly it **started working**.  

Not sure  why second method call to, update variant is not triggered in first place. Will look into it further.

**Comment by zenweasel** [comment]
@hrath2015 Herman, here is an example of one that has variants and options with all data, and still turns out undefined. I pretty much always add products the same way with the same data so I haven't seen it NOT happen but I haven't played around with it much.

![2018-07-27_07-55-28](https://user-images.githubusercontent.com/72819/43294555-7ed67e02-9172-11e8-9662-3e947b5ae409.png)

**Comment by hrath2015** [comment]
@zenweasel  please try below,
Navigate to Product Page  (Add Product or from Grid)
Force Reload the page, by clicking in browser.  
Now click on eye icon to see the changes in both product and its variants.

As per my analysis, This is because the current router state is not reflected in **App** component.

**Comment by kieckhafer** [comment]
This crosses over to the starterkit as well. Since the starterkit and logged out / anonymous users share the same data now, it seems like this is an issue with the data itself. Probably just need to make sure we return a `$0.00` price when no variants or options are published.

Or do we remove the price display altogether if there are no published variants / options?

Displaying 0 would be an update just in the `reaction` repo that provides the data. Removing the display of it would need an update in the starterkit as well.

![reaction](https://user-images.githubusercontent.com/4482263/43745739-3b2d38d2-9995-11e8-90e8-12ab5de2dc13.png)
