### ISSUE TITLE
[1.14] Client-side FileRecord throws "Cannot read property 'absoluteUrl' of undefined"

### ISSUE THREAD

**Issue by loanlaux** [reactioncommerce/reaction#4470]
## Prerequisites
* [x] Are you running the latest version? (pre-release 1.14)
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Client-side FileRecord (`imports/plugins/core/files/client/index.js`) throws `Cannot read property 'absoluteUrl' of undefined` on page load, preventing the DOM from loading and leaving me with a blank page.

## Steps to Reproduce
While running latest 1.14:
1. Open 127.0.0.1:3000
2. `Uncaught TypeError: Cannot read property 'absoluteUrl' of undefined` shows up in the JavaScript console, also causing a blank page

## Possible Solution
In `imports/plugins/core/files/client/index.js`, replace `import { Reaction } from "/client/api";` with `import Reaction from "/client/modules/core/main";`.

### Versions
(run `reaction -v` from your reaction directory)

Node: 8.7.0
NPM: 6.2.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: release-1.14.0
Docker: 18.03.1-ce

**Comment by pmn4** [comment]
This is the circular dependency issue popping up again. My bad!!
the issue is that `Reaction` imports some code which imports this file, which in-turn imports `Reaction`. Since we are in the process of importing `Reaction`, it is `undefined` until the importing is done. The resolution is to import the "mixin" directly (since it has no repo-defined dependencies).

**Comment by loanlaux** [comment]
Makes sense. Thanks @pmn4!

**Comment by loanlaux** [comment]
This is now fixed. Thanks a lot @pmn4!
