### ISSUE TITLE
GraphQL API - get shop by slug

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction#4486]
## Work
Currently there is no way to load a shop in GraphQL via its slug or mongo _id. See the `tag` query, which takes a slugOrId param. It'd be great if I could query for a shop by its slug or mongo _id so that the new GQL Meteor product grid can show the correct products when marketplace is in use.

**Comment by aldeed** [comment]
@dancastellon The plan was to try to keep Mongo ID internal, so that wouldn't allow querying by it. Query by slug is fine. You could add a `shopBySlug` in `/imports/plugins/core/graphql/server/no-meteor/queries.js`, similar to the `shopById`, and add corresponding query to the GraphQL schema.

If necessary, you could convert the Mongo ID client side and use `shopById`, but I think it should work to query by slug only. We can say we've dropped support for the ID being in the URL, but I don't think that ever really happens because the shop creation code always sets a `slug`.

If there isn't `shopIdOrSlug`, I believe you would use the `slug` from the primary shop object to do the query.

**Comment by aldeed** [comment]
@dancastellon Good question. The tags one is that way mostly because we support the URL having a tag slug or ID in it, and the client won't actually know which it is. For shops, I think we can limit it to slug only in the URL. So having separate `shopById` and `shopBySlug` is a slightly better approach because it will result in simpler, faster database queries for each.

**Comment by aldeed** [comment]
@dancastellon This is done?

**Comment by dancastellon** [comment]
@aldeed Ah yep, this one was done with the catalog grid.
