### ISSUE TITLE
Add "Client" to the data model

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4588]
## Problems
1. When a client needs to know what shop ID to use for some action in the client (e.g., which shop to get the catalog for or which shop to create a cart for), it looks up its own domain in the `domains` array of each `Shop` and takes the first shop it finds. If a shop is not found, it falls back to the shop with `type === "primary"` (there can only be one). Mapping shops by domains isn’t a great way to do this because something like a native mobile client doesn’t have a domain. Also, it is not a good model because we need exactly one default shop per client, but there could end up being multiple shops that list a domain.
1. There are pieces of data we need for a client UI, which we want to be able to define and edit in the database. Examples are navigation, routing, external links, and blurbs of legal text. We currently store such things on a Shop, but they are not inherently "shop things" in that a single shop might have several different client UIs, each with different needs for navigation, routing, etc.
1. Other things like available fulfillment and payment methods might need to vary by client, too, even for the same shop.

## Solution
All of the above problems lead to a simple proposed solution: add a "Client" type to the data model

- Add a `Clients` collection. Each document has just two properties for now: a unique name and a default shop ID.
- Add `createClient`, `updateClient`, and `deleteClient` GraphQL mutations. (Note that Client mutation will require super-permissions, i.e., permissions that are not shop specific.)
- Add `clients()` and `clientById(id: ID!)` GraphQL queries, for super admins only.
- Add a `defaultShopForClient(clientName: String!)` GraphQL query, which looks for a client with that name in the Clients collection and then returns the `defaultShopId`. If one is not found, falls back to the shop with `type === “primary”`
- Potentially add admin UI for managing clients, but just GraphQL might be fine for now.

How would this be used?

For problem 1, figuring out what default shop to use for a client, each client would have a name (e.g., "reaction-storefront1") compiled into its code. On startup, it would do the `defaultShopForClient` GraphQL query with that client name.

For the other problems, the GraphQL queries for `navigation`, `routes`, etc. would ask the client to pass its client name rather than a shop ID. In the database, these models would be related to clients rather than to shops.

**Comment by ticean** [comment]
Hi @aldeed, I think we can resolve the problems without adding a Clients collection to the db. Keep in mind we're introducing OAuth2 which has the concept of Clients already. We can probably leverage that where we really need client-specific functionality. I'll make notes on each problem statement so we can discuss each independently.

### 1. Determining Shop ID
> **When a client needs to know what shop ID to use for some action in the client**

This is a global router concern and I don't think client-specific code should be dealing with it. The router should apply a set of rules to extract a context that already includes an extracted Shop ID. 

##### Example: Server-Side Proxy Routing
I think we have confusion because we haven't clearly pulled apart the routing concerns, yet. It might be helpful to think about how a proxy (like nginx, or an API Gateway) works. There, the gateway handles the request and can transform the request before passing it to a backend. A request like `https://www.myshop.com/awesome-shoe-model-2018` would be transformed into `https://backend/shop/myshop/products/awesome-shoe-model-2018`.  The URL is normalized. The backend service doesn't need to do the Shop extraction. That's done. The backend handles a finite amount of normalized routes.

A business-aware proxy/router can transform that URL even more:

* Merchandising URLs with user manageable rewrite rules:
  * From `https://www.awesomecorp.com/myshop/best-shoe-of-2018`
  * To `https://backend/shops/myshop/products/awesome-shoe-model-2018`.

* With entity ID awareness:
  * From `https://www.myshop.com/awesome-shoe-model-2018`
  * To `https://backend/shops/1234/products/9999`.

##### In an SPA
The situation's a little different in an SPA but the concept can still apply. The problem is that our current front-end router is implemented as a single layer. It would be helpful to separate that into at least two layers. One layer to handle the global context like shop identification, that's then passed back to a second layer that handles client routes. The client routes would always be normalized, like `/shops/:shopId/products/:productId`.

Think that would make it more clear?
  
### 2. Different Data Per Client
> **There are pieces of data we need for a client UI, which we want to be able to define and edit in the database. Examples are navigation, routing, external links, and blurbs of legal text.***

Excluding routing, those do look shop related. Code within clients could be customized to show the data with different views but I don't think there's a need to support different data per client? Nav *data* and legal text would be the same for a given shop. If there's a case where someone needs to customize that then it sounds like a good place for a custom plugin?

### 3. Enabled Features per Client
> **3. Other things like available fulfillment and payment methods might need to vary by client, too, even for the same shop.**

I don't know if this is really required as a core feature, but if it needs to be implemented it could be handled on the client side. The client could maintain a list of its allowed payment methods and filter out the others. Client side implementation would probably be OK for the most cases. If server-side validation is required then the OAuth2 Client IDs could be used. Sounds like another good case for a custom plugin.

**Comment by ticean** [comment]
Cool. I'll try to explain better. I think we may agree more than not. Something somewhere needs to find a Shop ID. We're just not synced on how that happens. I think that the thing that should handle this is a "router", not a "client"". Talking about it as a router is more clear and reveals applications in addition to determining Shop.

#### Routing at the Edge

The "router", which is at the boundary edge, takes the input URL and figures out which shop the request is for. This happens regardless of the shop count which probably isn't known by the client. The input to the router's decision function is the request (domain/path/headers). The router finds the shop by matching on configured rules. It appends the shop information (and other info) into the context and passes that context on for handling by the client code. The client code doesn't ever try to figure out what shop should be used. That's provided to it by the router.

That the "router" is different than the client application routing is important. They work in different scopes. The "router" handles user input from the wild. Client routing handles pre-defined, static routes. The paths matched by the client application routes will often differ from what was intercepted by the router. 

That's important because the "router" will actually be doing *"rewriting"*.

* `https://myshop.com/nike -> router -> /shop/myshop/tags/nike`
* `https://myshop.com/back-to-school -> router -> /shop/myshop/pages/back-to-school`

##### Where exactly is "the edge"?

Above, I claimed the router should be on the boundary edge. On the server side, that's usually the edge of the network. Load-balancers, reverse proxy, or API gateways can take on this role and rewrite requests before relaying them back to the backend apps that they proxy. The setup is so common that it's almost ubiquitous. Apache, NGINX, all have rewrite rules and people have been doing that for a long time.

I know that current state Reaction has single page apps. I think the concepts of separation and responsibility still apply.

Given what we have today, the edge would be the user-facing, top-level request handling of the application. It would be like a data-driven middleware at the top of the client request stack. Decoupled from and opaque to the client application code.
 
There are some difficulties in an single page app, though, that we'll have to figure out.

#### Making Decisions with Routing Rules

How does the router make it's decisions? It implements routing rules. The routing rules would be stored in a datastore and the router would be the single writer for those rules.

The router is decoupled from other components in the system, unaware that anything else even exists.

It should have an interface to read and manage rules.

Routing rules can be created through the interface by some higher-level logic. For example today the Shop's domain/path is stored in the shop collection. We can listen for Shop events and update the routing rules as needed. If we decide to store that somewhere the internal router logic doesn't need to be modified.

#### Challenges in Single Page Apps

* There may be a large amount of routing rules in a typical installation which equals a lot of data to pass around before getting to a route output.
* The rules would be exposed to the client as a data which may not be wanted.
* Client needs to be updated of routing rule changes once the page is loaded.

#### Other Use Cases

The conversation has focused mainly on Shop, but there are other reasons we need routing functionality:

* **CMS** - Routing pages.
* **Product Merchandising** - Changing the URLs of products. Re-routing commonly mispelled friendly URLs. Putting products in a custom path.
* **SEO** - Redirecting old URLs to new ones to retain SEO ranking
* **Code Stability** - With a router in place, client app code can remain stable. The routing desired in an installation can be changed without updating client paths.


##### Example Routers/Rewriters

Here's a non-exhaustive list of example software with rewriting rule engines:

* [Skipper](https://opensource.zalando.com/skipper/)
* [Apache Camel](http://camel.apache.org/)
* [Zuul](https://medium.com/netflix-techblog/announcing-zuul-edge-service-in-the-cloud-ab3af5be08ee)
* [Vulcan](http://vulcand.github.io/#documentation)
* [Hystrix](https://github.com/Netflix/Hystrix)
* [NGINX](https://www.nginx.com/blog/creating-nginx-rewrite-rules/)
* [Magento2 Routing](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/routing.html)
