### ISSUE TITLE
Sidebar buttons no longer open side panel on product grid

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4633]
## Issue Description

Clicking the sidebar buttons no longer opens the sidebar when on the grid page

![reaction](https://user-images.githubusercontent.com/42217/45643134-2afa8f00-ba6f-11e8-9fe3-c89a4123d3d1.png)

## Steps to Reproduce

1. On the grid, click a sidebar button
2. See it doesn't open
3. Then click on a product
4. Then click a sidebar button again, see the panel change

## Possible Solution

The button in the sidebar probably isn't setting the right state to open the side panel, though it does change the contents.

### Versions

Node: 10.7.0
NPM: 6.2.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 1.16.0
Reaction branch: release-2.0.0
Docker: 18.06.0-ce

**Comment by aldeed** [comment]
I bet it's because of this code I changed: https://github.com/reactioncommerce/reaction/blob/release-2.0.0/imports/plugins/included/product-variant/containers/productsContainerAdmin.js#L170-L180

It should hide the action view only if it's currently showing productSettings, or even just not hide it.

**Comment by spencern** [comment]
My guess was going to be #4628 which I think is what @aldeed is referencing as well
