### ISSUE TITLE
Custom Rates taxes don't apply

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4655]
## Issue Description
Even though Custom Rates are enabled they are not applied on checkout

## Steps to Reproduce
1. Enable Custom Rates for CA
1. Attempt to checkout with an address in CA
1. Observe that taxes are not applied

### Versions
Reaction: 2.0.0

**Comment by aldeed** [comment]
I know this was working when I first ported that code, and I thought I saw taxes being applied properly just yesterday. I'll have to dig into what might have happened.

One question would be whether they were truly not applied on the order. Because it is now possible that they would not appear during checkout but would still be correct on the order. That should not happen because the client sends the expected total amount to the server and I assume that would not match if taxes were different. But you never know.

**Comment by zenweasel** [comment]
I think it might be true that it the tax is being applied but just not appearing during checkout (which is sort of worse)

**Comment by zenweasel** [comment]
Testing this locally I don't see Taxes being applied at all

**Comment by zenweasel** [comment]
It looks like when items are being added to cart that `isTaxable` is being set to false even though it's set to `true` on the product. Looking into `addToCart` (if I can find it)

**Comment by aldeed** [comment]
That makes sense because I believe I tested originally by manually setting `isTaxable` to `true` on some items. Oops
