### ISSUE TITLE
Footer template can't be customized

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction#469]
Hi,
I am trying to customize the footer template but every time I overwrite the `Template.myLayoutFooter.replaces("layoutFooter");` it's not taken into consideration because the core `client/templates/layout/footer.js` overwrites thes layoutFooter template in the main folder and not at the package level so that will always run last.
Any ideas how can I override the footer template from my theme pakcage?
Thanks.

**Comment by mikemurray** [comment]
Similar to https://github.com/reactioncommerce/reaction/issues/383

**Comment by aaronjudd** [comment]
Closing,  use Shops.layout > v0.12.0  for structure management now.

**Comment by carlos-olivera** [comment]
About this topic, I faced the same problem in my custom plugin, this is my solution:

[https://github.com/carlos-olivera/Next-Reaction/commit/bdbe8f8de24db93335c7f66688eca87af43cfc3f](https://github.com/carlos-olivera/Next-Reaction/commit/bdbe8f8de24db93335c7f66688eca87af43cfc3f)

I guess, is not the best way, due to overwriting in the Packages collection, nevertheless, for now, works.

**Comment by josx** [comment]
I am using master version (1.4.x), how can i put and customize the footer for the whole application.?
