### ISSUE TITLE
Updating cart causes multiple tax API calls.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4711]
## Issue Description
In the tax-plugins, the function to calculate the tax is run on `afterCartUpdate` event.
This causes the function to run everytime something is updated in the cart, which is quite a lot.
How do I implement something like: run this function only when the cart is being displayed or the user is in the checkout screen.

**Comment by aldeed** [comment]
As of the linked PR, the tax plugin calculation function will only be called after there is a shipping address on the cart, so it shouldn't be called until that point in the checkout process. A tax service plugin could choose to cache requests or otherwise optimize to avoid calling the external tax service more than is necessary.

The core code is still called on every cart update, so there may be some database queries happening more often than necessary as part of that. We can keep an eye on it and optimize if necessary.
