### ISSUE TITLE
Create Query.primaryShop GraphQL resolver

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction#4727]
We have `Query.primaryShopId` and `Query.shopById`. A client currently needs two requests to those to get the primary shop data, which is the most common case and happens all the time on first load. We can simplify this for client development by creating `Query.primaryShop`, which combines those two lookups on the server (and reduces to a single DB query).

**Comment by spencern** [comment]
@ticean 
The way that our current marketplace/multi-shop setup works is that each installation must have exactly one primary shop. There can be any number of other shops, but only one primary shop. I believe this is currently hard-coded to the first shop that is created, though I'm not certain about this. 

We can discuss how we'd like improve this but I believe this issue is mostly about creating a helper query that simplifies the lookup of that primary shop (which is the only shop in a single shop installation)
