### ISSUE TITLE
Generated "permalink" uses ID rather than using slugified title

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4735]
## Issue Description
The permalink should generated from a slugified version of the product title whenever possible (which should be always?). Currently it's using the ID instead. This is bad for SEO and readability

## Steps to Reproduce
1. Create a new product
1. Observe that the permalink is not a slugified version of the title

## Possible Solution
The `handle` field is not being set properly. Possibly this is caused by `getSlug` or similar not being available? Just a guess

### Versions
Reaction: 2.0.0-rc5

**Comment by janus-reith** [comment]
I take that back, just tried to look it up myself, createHandle in catalog does exactly that: [/imports/plugins/core/catalog/server/methods/catalog.js](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L128)

Somehow I was under the assumption that it calls slugify without checks, nevermind.

**Comment by mpaktiti** [comment]
I did some debugging and these are my findings:

- When we create a new Product the [createProduct function](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L642) is called without arguments (i.e. `props` is null).
- As a result the [newProductOrVariant object](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L185) looks like this: `{ shopId: 'J8Bhq3uTtdgwZx3rz', type: 'simple' }`
- The slugified title should be generated by this [if statement here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L203) but this never runs, since the object does not contain a `newProductOrVariant.title` property. Therefore the permalink is generated by `newProductOrVariant.handle = Random.id();`.

**Comment by mpaktiti** [comment]
When we update the title of a product, the permalink is still not updated. 

The reason is the second condition in [this line](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L819). 

The `doc.handle === doc._id` will never return true because the doc.handle is populated [with a random id here](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/methods/catalog.js#L206).

@zenweasel How do we want to fix that? If I remove the 2nd condition then when I set a title the permalink is generated correctly. And every time I update the title it gets updated. Wdyt?

**Comment by mpaktiti** [comment]
Fix merged
