### ISSUE TITLE
No toggles on payment plugins operator UI

### ISSUE THREAD

**Issue by lynnnyn** [reactioncommerce/reaction#4768]
## Issue Description
Providing a clear description of the issue will enable a developer to quickly reproduce and understand the issue. Please provide a detailed description including images, animation and/or videos. For client issues, include browser console errors, for server issues please add terminal output and stack traces.
Hi, I am trying 1.16 version.
It had no error, but has a warn.
<img width="1436" alt="screen shot 2018-10-22 at 12 16 53 pm" src="https://user-images.githubusercontent.com/26138685/47308024-18d3b980-d5f6-11e8-8611-723333dc0016.png">

And it did not show toggles for each payment plugin in the website.
<img width="1375" alt="screen shot 2018-10-22 at 12 30 15 pm" src="https://user-images.githubusercontent.com/26138685/47308108-59cbce00-d5f6-11e8-88b7-10bc89be2ed4.png">

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug
I have tried 1.15 and 1.17, but both have problem to start MongoDB.

### Versions
(run `reaction -v` from your reaction directory)
1.16

**Comment by aldeed** [comment]
@lynnnyn You say you are running 1.16, but your screen shot shows `2.0.0-rc.5`. 1.16 had a serious bug if you have taxes enabled, so I recommend 1.17.

To better understand what the real error might be, open developer tools in the browser and look for any errors there.

If you did try 2.0 and then go back to 1.17, you might need to restore your database from backup or create a new one because it will now be updated to the 2.0 migration version. It is a known issue that there is no simple way to migrate the data back down to what 1.17 expects.

**Comment by zenweasel** [comment]
@lynnnyn There is currently a bug that at certain widths the payment toggles are not shown (https://github.com/reactioncommerce/reaction/issues/4713). You can work around this bug currently by just making your browser width larger or smaller.

**Comment by zenweasel** [comment]
Closing. Duplicate.
