### ISSUE TITLE
Different params passed to tax-plugin.

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#4807]
## Issue Description
When the function `calculateOrderGroupTaxes` is called on the checkout screen, the cart(modified) is passed in which the `items` has the property `priceWhenAdded`. But when the order is placed, the same function is called with parameters in which the `items` has the property `price`. This is causing the plugin to break.

## Steps to Reproduce
1. Add a taxed-plugin with following function to calculate the tax:
```js
export default async function calculateOrderGroupTaxes({ context, group }) {
  if (!group || !group.items || group.items.length === 0) {
    return {
      itemTaxes: [],
      taxSummary: {
        calculatedAt: new Date(),
        referenceId: Random.id(),
        tax: 0,
        taxableAmount: 0,
        taxes: []
      }
    };
  }
  console.log("price", group.items[0].price, "priceWhenAdded", group.items[0].priceWhenAdded);
  return {
      itemTaxes: [],
      taxSummary: {
        calculatedAt: new Date(),
        referenceId: Random.id(),
        tax: 0,
        taxableAmount: 0,
        taxes: []
      }
  }
}
```
2. Checkout with a product and see the logs in the console.

### Versions
I checked this with `origin/refactor-aldeed-split-tax-rates-plugin`

**Comment by Akarshit** [comment]
@aldeed I think this would address the error about "expectedTotal" not being equal to the "currentTotal" issue too.

**Comment by Akarshit** [comment]
Also while checkout, the object doesn't have `currencyCode` but while placing order, the object has `currencyCode`.

**Comment by aldeed** [comment]
@Akarshit Thanks for figuring this out. I will fix to ensure the provided data is the same in both cases.

You can work around for now by using `item.subtotal` rather than `item.price`. The `subtotal` is present and correct in both cases, and is the price multiplied by the quantity. Maybe Radial requires you to pass in the price and quantity separately, in which case you'll need the fix or you can divide `item.subtotal` by `item.quantity`.
