### ISSUE TITLE
Include shopId in product lookups by slug

### ISSUE THREAD

**Issue by pmn4** [reactioncommerce/reaction#4813]
I am reading through the `catalogItemProduct` source and am curious, should the Primary Key of a Product/CatalogItem be it's `_id` _and_ the `shopId`? I ask because as written, any shop could request any other shop's products if it knew the `_id`. At the very least, shopId should be required when requesting by slug.

Here is the source: https://github.com//reactioncommerce/reaction/blob/master/imports/plugins/core/catalog/server/no-meteor/queries/catalogItemProduct.js#L28

Now that I think about it, the question applies to almost all collections.

**Comment by aldeed** [comment]
@pmn4 While there are places in the code where shop ID checks are missing, something we'll be fixing soon, I don't believe this is one of them. The catalog data is public so any shop (or any person) _can_ request any other shop's product by ID, and that's by design. At some point there may be certain fields added to Catalog that are not public, and those fields may be returned only for someone logged in with proper permissions. Or there may be a use case for a shop that is entirely behind login, which should not have publicly visible products. But neither of those cases are yet supported.

**Comment by pmn4** [comment]
Ok, I guess am using the platform a little differently than the primary marketplace use-case (instead, building a white-label platform with the primary shop storefront disabled), so I guess it makes sense that I look at this issue a little differently.

**Comment by pmn4** [comment]
I think I will always find it a little strange that a shop owner might run into slug naming conflict with a product from a different shop

**Comment by aldeed** [comment]
> I think I will always find it a little strange that a shop owner might run into slug naming conflict with a product from a different shop

That part of your issue is valid I think. We should be doing all slug lookups by both shop ID and slug, and slug uniqueness should be enforced per-shop rather than globally. Two places where this fix would be needed:
- Add required `shopId` argument to `catalogItemProduct` GraphQL query. It could be recommended rather than required if we want to leave open support for products shared among multiple shops and/or to keep backwards compatibility.
- Verify that we are not enforcing uniqueness on `handle` or `slug` anywhere, or if we are, that we're doing it by shopId+slug.
