### ISSUE TITLE
Meteor frontend UI 'accessible' during OAuth flow

### ISSUE THREAD

**Issue by impactmass** [reactioncommerce/reaction#4852]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When performing OAuth login flow from a storefront using the Hydra IDP setup in the Meteor app, it is _possible_ to see other pages of the Meteor app (i.e the classic frontend). This can cause user confusion if they manage to navigate away from the login form to other pages on the Meteor app's classic UI.

For example, in the case of a startup issue where the login page can not be found, the Meteor app shows a 404 page with a nav bar that links to other pages in it's app. Clicking on the nav takes users to the classic UI (not the Storefront earlier visited).

First reported by @ticean.

## Steps to Reproduce
1. Try to login with the Starterkit (which starts the OAuth flow and takes you to the Meteor app which is serving as the OAuth IDP).
2. Once you see the login form, edit the URL (e.g change /account/login to a random string)
3. Press enter to visit that. Note that if you get a 404 page, it comes with a 

## Possible Solution
- Can other parts of the app be hidden by an ENV var configuration (either at access time or at deploy time)?

### Versions
2.0-rc-5 and newer

**Comment by impactmass** [comment]
Proposal from my research:

### Possible Solution:
- We can disable all routes except the Hydra login route and the 404 page route.
- The 404 page should not show navigation and admin controls. It should only show the bare 404 page text.

### How To:
- Routes created by Packages/Plugins can be removed/disabled by updating the relevant entries in the Packages collection in the DB.
- The "default" routes ("/", "/shop/:x", and "not-found") are defined in the code. These are harder to deal with because they are written in code. A separate effort to move them into DB(?) is needed to allow disabling as suggested above.

**Comment by mikemurray** [comment]
@impactmass I think you're on the right track with your solution. Disabling all other routes and only having the views for login would help prevent the user from seeing the rest of Reaction on an auth error.

The new Operator UI does this in `imports/plugins/core/ui/client/components/app/app.js`

```js
      if (currentRoute.route.path.startsWith("/operator")) {
        return this.renderOperatorApp();
      }
```

Tthe `children` prop of the `App` component is what contains all the routes. If you omit that and only add the auth routes, then you can effectively hide the other parts of the app.

There may be other things to consider, like the 404 page or other event handlers that trigger route changes, but this is a good place to start.

**Comment by janus-reith** [comment]
Why are such workaround necessary at alll?
What is the reason that the login form can't be rendered in the next app?
And if it's some Meteor specific code, why can't it be abstracted in the backend instead?

**Comment by ticean** [comment]
Hi @janus-reith. We're working toward a complete security system that provides Single Sign On, federated-identity and powerful authorization features. The starterkit is a non-privileged client application. It outsources the login to our Identity Provider (IDP), and gets the user token from Hydra (OAuth2/OIDC.) In this design, it doesn't have access to the user password and has fewer security concerns. It can be replaced without worrying about re-implementing login/logout. New clients, like mobile apps, point-of-sale systems, and server-side applications can be added using similar OAuth/OIDC patterns.

We kept the IDP functionality in Meteor for now. The functionality was there. We just made a few minor modifications, like adding login pages that are compatible with the OpenID Connect flows. We weren't able to migrate from (or feature match) Meteor's groups and roles functionality in the time we had to ship starterkit. So we *added* Hydra for OAuth/OIDC and will be *extracting* IDP soon.

**Comment by janus-reith** [comment]
Thanks for the answer.
I understand that the IDP is currently provided by Meteor, but what I still don't get:

Shouldn't it be trivial to take the currrent login call from Meteor, create an Apollo mutation (that still relies on meteor) and call that from a login form inside of the nextjs app.

To me this seems cleaner than the redirect.

**Comment by loan-laux** [comment]
@janus-reith Personally, I would much rather have an OAuth flow in place, even if it temporarily has to use Meteor.

If a client has an OAuth server already in place and wants their existing customer accounts to work on Reaction, it'll be much easier to implement than if no OAuth support was provided. Big pro for enterprise use cases IMO.

**Comment by janus-reith** [comment]
@loan-laux Agreed. But I'm not trying to debate wether to ditch Meteor Logins at any point earlier than when a full featured replacement exists.

Im raising the question if the current browser redirect to the meteor app is necessary, or if relevant calls could be encapsulated in a GraphQL mutation(and some client-side fetch call to the classic page, if neccesary ), and Login data entered on the nextjs page.

**Comment by loan-laux** [comment]
@janus-reith While I agree with you, I'm pretty sure that you can't implement OAuth without a redirect (cf. https://en.wikipedia.org/wiki/OAuth).

However — and I'm aware that this deviates from the scope of this issue and even this repo — we could think of opening this Meteor-server login form in a pop-up window. That's what a lot of e-commerce sites do when dealing with external login services such as Facebook and Google. This would avoid reloading the Next.js storefront and perhaps make the loading time more understandable to users.

To be discussed on the `reaction-next-starterkit` repo if there's an interest. Just food for thought otherwise.

**Comment by ticean** [comment]
Hi @janus-reith. As @loan-laux suggested, we're using a standard OIDC flow for the login and the redirects are part of that flow. The team at ORY have already put in the work to get Hydra [OIDC certified](https://openid.net/certification/). That's great for us because we can lean on their expertise. We follow existing flows and the specs to keep our security services and clients safe and conformant.

RE: Why not add a login mutation to the GraphQL API so the IDP could be implemented in starterkit?
Exposing such an endpoint would bypass the security of the Identity Provider and the OIDC flow. The IDP is the only party that has ability to 1) see the username/password data submitted by the user, and 2) make validation requests to the identity database, directly or by API.

It could be possible to expose such an API query IF client access is restricted to privileged clients. In that case we'd restrict to a dedicated *IDP* client, rather than the *starterkit* client. We're not actively working toward a design that exposes a login API, though. And I'd even push against doing so to encourage the most secure architecture on Reaction shops.

**Comment by ticean** [comment]
As a follow up, there is an OAuth Resource Owner Password Credentials Grant Type that allows clients to authenticate users with the username/password. Hydra doesn't support it for valid reasons. Their [documentation on the decision](https://www.ory.sh/docs/hydra/limitations#resource-owner-password-credentials-grant-type-rocp) provides good context and links to other good articles. It's not exactly 1 to 1, but it's pretty close to a spec around a username password API.

I hope these comments help clarify our rationale for the overall design and this particular issue. Happy to discuss further! 😄

**Comment by janus-reith** [comment]
Interesting, I had a good read, although this still left some questions that would certainly go beyond the scope of this issue. 
However, I'd anticipate a seperated IDP instead of loading the whole Meteor client bundle just for login.

**Comment by aldeed** [comment]
If loading full Meteor UI just for login is a serious concern, creating a separate Meteor app for IDP only would likely be quite easy. The tradeoff is the overhead of spinning up and managing another container/URL for it.

**Comment by impactmass** [comment]
house-keeping on this stale issue. This was done in #4903... and also the user facing Meteor client has been removed
