### ISSUE TITLE
Add ability to have Loyalty or Gift Card payment method as second payment method

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4860]
We need to be able to write a payment plugin that would store and manage loyalty rewords points that could be redeemed for dollars off an order.

This differs from a discount in that it does not lower the amount to be charged for tax purposes but is an actual payment against the order and can be used to pay the entire amount of the order.

We would also need to have it treated slightly differently than a normal payment in that a return on an order should always be credited to the Rewards first and then a tendered payment method second.

I _think_ these major changes need to be made:

1. Schema and other changes to allow more than one payment to be reflected on an order.
1. Allow multiple payment methods during checkout, and allow amount tendered to decrease balance of order and when balance reaches $0 the order is placed (as opposed to the current method of having the payment method responsible for placing the order)
1. Introduce the concept of a "store-credit" payment type and have the main core arbitrate when a cancellation/refund comes in that store-credit payment types are credited first over tendered payment methods.
1. Provide some way to communicate to a payment method that an amount has changed.

According to @aldeed there were discussions about how to handle this in the past with @spencern and @ticean and we would need to determine how to best accomplish this in the near term while remaining aligned with those plans.

**Comment by aldeed** [comment]
Good summary of the requirements.

The main reason (I think) we ended up with the `placeOrder` GraphQL mutations being provided by the payment plugins is because each payment provider will need different pieces of information to authorize or confirm a payment, and we do not want to store this data anywhere for security reasons. More specifically, we don't want to store something like a Stripe card token on the cart until we have the final order totals and can create the necessary charges. So as soon as we get the payment info we create the charges and the order in the same single API call.

The main supported payment provider is Stripe, but all providers that deal with credit cards have similar flows.

Unfortunately, as @zenweasel said, this doesn't work well once we want to pay with two different sources because now the mutation provided by one payment plugin will have to be aware of the other payment plugins and how they work.

It seems like the only solution will be to flip the process, so that the `orders` plugin will provide a single `placeOrder` mutation, which can be passed multiple payment sources. I believe we can still avoid generic `JSONObject` type for the payment source data (which was one priority) by having each payment plugin extend a base `PaymentDataInput`, which they actually already do for the payment data that is stored on the order.

It should be possible to add this way of placing an order and deprecate the existing way, keeping it temporarily so that this is backwards compatible for some time.

That is the most complex change needed. Otherwise, we just need to decide how an operator should configure payment methods such that they can be charged and refunded in the desired order, and then build that logic into the `createOrder` function.

Another complexity to keep in mind is that payments are handled per order fulfillment group, and not per order. So there is an allocation process involved for partial payments. E.g., if I am using $50 rewards, which groups and items is that allocated to? Do we need to keep this allocation or can we simplify?

**Comment by zenweasel** [comment]
Discussed this today with @aldeed 

A couple of factors that affect Loyalty payments would be:

1. Allowing multiple payments by allowing the client to create a client-side order object that would have each payment type, the amount to apply, and any other info necessary to complete the payment, which would then all get submitted to `createOrder`

2. Allow the customer to define a "refund order", so that if a partial refund comes in, the first payment in that sequence would be refunded until it was exhausted, and then the next. The canonical example here would be a gift card would be refunded first, and then a tendered payment method like Credit Card would be refunded.

There are other issues e.g. when and if we would split up orders but they are not directly related to this ticket now.
