### ISSUE TITLE
PDP URL Handle UX updates

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#514]
I'm accepting https://github.com/reactioncommerce/reaction-core/pull/206 which introduces behaviour where the product title is creating the handle, and when the title is updated the handle/url is also updated.
However, the previous way of setting the handle on the tags, is still functional, and we'd like it to remain so.

A few updates are needed to smooth out the user experience though:
1 - if handle is in tags, do not change on title change
2 - supply edit functionality (bookmark icon) on the title input to switch from tag handle to title handle, and make it visually more obviously what's happening.

![reaction___example_product](https://cloud.githubusercontent.com/assets/439959/11104037/2fb24278-887b-11e5-8226-c250c238b81d.png)

**Comment by newsiberian** [comment]
Hello,
currently we have a different URL-behavior for route “product”. The URL can be like: `http://localhost:5000/product/example-product` or it can be like: `http://localhost:5000/product/6YMujPhrgdbLkZWXr/kjSmrRKtjnvcdx3aK` if we go through cart. I'm not sure why we using different logic for it. Is there any security explanation or other? For me the current logic looks not beauty that's why I want to implement something more smooth. Here is a few variants.
**variant 1:**
at first glance, it needs a minimum of changes. We could keep `_id` for variant, but use only `handle` for products. It will be looks like: `http://localhost:5000/product/example-product/kjSmrRKtjnvcdx3aK`
**variant 2:**
add `handle` prop to variants. In fact this is by default in ancestors model. We could use handles for product and variants:  `http://localhost:5000/product/example-product/green-variant`.
One lack of this approach is in too long variant name like [here](http://www.amazon.com/adidas-Performance-Speed-Trainer-Training/dp/B00RM4ZVWO/ref=sr_1_2?s=apparel&ie=UTF8&qid=1448795952&sr=1-2&nodeID=7141123011&keywords=adidas+shoes) for example.

So the question is: do we interested in such kind of changes?
If answer is "yes", then we could do it as part of ancestor model changes. It fits very well in them.

**Comment by kieckhafer** [comment]
With the massive amount of changes to the PDP being pushed with #1178 (over 100 files related to the PDP), we are holding off diving into this ticket until #1178 is pulled into development and we can work off of those changes.

**Comment by mikemurray** [comment]
Related to #869

**Comment by kieckhafer** [comment]
Closing this in favor of #1648
