### ISSUE TITLE
Similar / Recommended For you on PDP

### ISSUE THREAD

**Issue by rohanthacker** [reactioncommerce/reaction#518]
A popular feature on E-Commerce sites is to add an additional set of items to display on the Product Detail page. Usually under the title of "Similar Products" "Recommended for you" etc.

Although a full-blown recommendation engine is out of the scope of this project. 
I'm suggesting a package that will produce an additional set of products to display on the PDP by just calling getProductsByTag() again. 

Is this something that would be useful? Or do you have any ideas on how we can this possible?

**Comment by aaronjudd** [comment]
We have an internal list that has a lot of these features on it, but I've not written any architecture docs on these. I generally don't post an issue until I've written the docs, and we're nearing a point where the core team will work on it.  (really just because we don't want to have too many stagnant issues on the roadmap, so I generally have just put core features into the issues) If you'd like I can write up a semi-detailed plan on how I see this working ( I can do that for reviews as well, if you'd like). at least this could be a starting point for community discussion.

**Comment by rohanthacker** [comment]
@aaronjudd If you have the time to do that and it wont be too much of a hassle, That would be great.

**Comment by zenweasel** [comment]
We probably will be releasing this as a separate plugin. You can look in the [swag shop](https://github.com/reactioncommerce/reaction-swag-shop) for an example of implementing this.
