### ISSUE TITLE
Add reason, customFields to updateOrderFullfilmentGroup API

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction#5199]
A reason is normally needs to show why the status of the group was changed.  Adding a `reason` field would create a place to store the reasons.

**Comment by Akarshit** [comment]
Also would it make sense to add a custom field to it. This way we can save whatever extra information we have about the shipment in that field.

**Comment by aldeed** [comment]
I think this needs a little thought and discussion. We currently store the cancel reason on `cancelReason` field on each order item, but that may not be the best final solution. We'd have to add a more generic `statusReason` field, but it might be best to make that part of the status/workflow rather than storing in a single field. Because what if you cancel, uncancel, and then cancel again for a different reason? The reason belongs to each status action and should be stored as such.

So it might be a good time to come up with a better data structure for order statuses in general. The `workflow` array should perhaps be objects rather than strings, so we can store `changedAt` date, `changedBy` user, `reasonForStatusChange`, `oldStatus`, and `newStatus`. Also `statusHistory` might be a better name than `workflow`.

**Comment by aldeed** [comment]
@kieckhafer My comment above is related to order work you're currently doing, and @mikemurray you probably have an opinion or historical context to provide.

**Comment by aldeed** [comment]
Whatever structure we come up with should be the same for order-level and group-level statuses. I believe we've decided to get rid of item-level statuses.

**Comment by kieckhafer** [comment]
@aldeed Yes, we did decide to remove item level statuses. While doing so, the only thing I've come across that I can see maybe a reason to keep it is to use for inventory, the item gets the status `coreItemWorkflow/removedFromInventoryAvailableToSell"` when it's ordered. We currently don't use it anywhere, but maybe we need to keep that for the future?

**Comment by aldeed** [comment]
@kieckhafer `removedFromInventoryAvailableToSell` should no longer be necessary since I moved all inventory logic to SimpleInventory collection and switched to tracking reserved inventory. I must have neglected to remove code that was setting that, or else I'm misremembering my changes.

If we switch to a model where an item being in a group with "canceled" status is the only thing that makes it canceled, then I don't see a need for the item-level status there. It's possible there's a gotcha I'm forgetting.

**Comment by aldeed** [comment]
Closing this as not actionable
