### ISSUE TITLE
Deleted variants should be removed from all carts

### ISSUE THREAD

**Issue by Niko0918** [reactioncommerce/reaction#5237]
1. You add "Sample Product" to the shopping cart.
2. You delete this "Sample Product" with admin panel.
3. You Refresh shopping cart and get this err.

```
  7 |  * @param {Object} cartItem Object of the `CartItem` type
   8 |  * @returns {Object} Data suitable for tracking a `CartItem`
   9 |  */
> 10 | export default function getCartItemTrackingData(cartItem) {
  11 |   const variant = { ...cartItem };
  12 |   let url;
  
```

( Because when you delete some product with admin panel then this deleted product will not be removed automatically from shopping cart too. So you will get this err because this product doesn't exist. )

**Comment by aldeed** [comment]
There might be a few things here.
- a variant maybe should not be able to be hard deleted if it's in any carts or orders
- a variant that is soft deleted should be included in the cart items query even though it is soft deleted because it's still in the cart? Or we should have a setting/prompt for whether to remove from all carts.

**Comment by kieckhafer** [comment]
Closing in favor of https://github.com/reactioncommerce/reaction/issues/6077 which tracks the same issue with more discussion.
