### ISSUE TITLE
Refactor the Stripe Card Payment Plugin to use their Payment Intents API and some general considerations

### ISSUE THREAD

**Issue by janus-reith** [reactioncommerce/reaction#5304]
## Issue Description
Currently the Stripe Form executes a call to stripe from the client to create a token:
[/reaction-component-library/src/components/StripePaymentInput/v1/StripePaymentInput.js](https://github.com/reactioncommerce/reaction-component-library/blob/d3ca15bf3c586c8070900d5ddaa3ef088d27be72/package/src/components/StripePaymentInput/v1/StripePaymentInput.js#L78)

These kind of integrations will stop working reliably in the EU from September 14 2019 due to the new [Strong Customer Authentication](https://stripe.com/docs/strong-customer-authentication) rule coming into effect.

The current Token approach is considered outdated, while the new [Payment Intents AP](https://stripe.com/docs/payments/payment-intents/quickstart)I meets the requirement of the SCA.

We should therefore refactor the Stripe payments to this new API.
From what I got so far that kind of integration works similar to the way I did the Paypal integration. The token can be created on the backend and transported to the client using a graphql mutation.

What could be tricky: With Paypal I could trigger such a mutation upon clicking the button, therefore I could always be sure to have the latest total and trigger the checkout from there.

Filling the stripe credit card  form and generating a token doesn't exclude the possibility of changes to the card happening afterwards. While the Payment Intents API takes care of such scenarios by providing an endpoint to update the `amount` of a token, I'd prefer not to make the backend logic too complex just for this provider, or at least see if it makes sense to settle for a generic solution for payment providers with updated cart totals similar to the existing authorize/capture functions on context?

While every payment plugin could just use the cardUpdate appEvents for this currently, a separated function might help to structure things in an easier way?

**Comment by owenhoskins** [comment]
Hey @janus-reith. I am not familiar with your Paypal integration and I haven't done much yet with the new RC, but, I've just gone through integrating Payments Intent in a pre-v1 RC shop where I migrated from the Charges API to "Payments Intent with Synchronous Flows". 

Now looking at v2 RC the first thing I am trying to determine is which Payment Intents flow is appropriate here. Stripe strongly recommends an [async flow which uses webhooks](https://stripe.com/docs/payments/payment-intents/migration/automatic-confirmation) to monitor the status, because for one it reduces the trips required to the server that the synchronous flow would require.

The async flow is outlined like so:

1. Create a PaymentIntent on your server with the desired amount and currency
2. Send the PaymentIntent’s client secret to the client side
3. Collect the customer’s payment information in the browser with Elements
4. Use Stripe.js to perform Dynamic 3D Secure and complete the payment on the client side
5. Use webhooks on your server to fulfill the customer’s order if the payment is successful

The RC server would create a PaymentIntent and send it to the client in Step 1. And in Step 5 the server would monitor the payment status from Step 4 via Stripe webhooks and send success or failure status to the client, triggering an order complete workflow.

Following your above questions: can the webhooks approach fit into a generic solution for multiple payment providers (such as Paypal)? And if not, is the backend complexity justifiable for one payment provider?

**Comment by beingke** [comment]
Hey @janus-reith @owenhoskins,

Just following up on this. What is the status of [Strong Customer Authentication (SCA)](https://stripe.com/en-es/payments/strong-customer-authentication) readiness in Reaction Commerce?

**Comment by janus-reith** [comment]
@beingke No progress has been made on this since I wrote this, the offical Stripe Plugin in Reaction Commerce is not ready for PSD2/SCA.

That being said, writing a Stripe plugin that makes use of the newer Payment intents api in a PSD2 compliant way was rather simple, I did not have to use the webhooks for this, and just plugged in the latest version of stripe-node and wired up the Reaction payment steps(authorize/capture/createRefund/listrefunds) and different to the old stripe integration, added a new createStripePaymentIntent GraphQL Mutation which the client calls to recieve a token secret to authenticate the checkout.

On the Storefront, I used the react-stripe-js library and 3d Secure works fine, the RC component library still bundles an older version of Stripe Elements.

I'm happy to help updating the RC Stripe implementation, however would need some feedback from the core team wether to refactor the current plugin and possibly introduce breaking changes for some users, or to just create a new stripe payment intent provider and leave the current one untouched, and offer a new easily pluggable component for the storefront aswell.

**Comment by benkingcode** [comment]
Hi @janus-reith could you share your plugin for this? Would be super helpful

**Comment by Akarshit** [comment]
Update: I would be picking this up and start researching on it.

**Comment by janus-reith** [comment]
@dbbk Sorry for the late reply, it's currently part of some custom client projects, I would need to separate it out first, it shouldn't be too much of an effort though.

@Akarshit Great, let me know if you need any help!

**Comment by MohanNarayana** [comment]
Hi @janus-reith , great to see you were able to work on the payment update. Can you please share your work via a PR?

**Comment by delagroove** [comment]
Hi @Akarshit @janus-reith @MohanNarayana Is there any ETA in regards to this plugin? without this working there will be no default payment ready then.

**Comment by Akarshit** [comment]
@MohanNarayana has the lead on this. AFAIK he has started looking into this one, but yeah let's wait for him to send an ETA.

**Comment by janus-reith** [comment]
Sorry, I'm on this - You can expect a PR until the end of the week.

**Comment by delagroove** [comment]
@janus-reith @MohanNarayana apologies in advance to bug you about this, but do you have an ETA? currently without this there's no default payment methods.
if there's a partial progress maybe a WIP PR will help to bring more manpower to the issue?

**Comment by janus-reith** [comment]
@MohanNarayana @delagroove Sorry for the delay, I had a lot on my plate - I'm finally preparing the PR today.

**Comment by janus-reith** [comment]
Done, I created a PR for the api side :)
I will now create one for the storefront which for now is not intended to be merged since I want us to figure out best distribution options - Appreciate input on this.

Also, looking forward to move this over to TS in the future.
