### ISSUE TITLE
Testing with `yarn` instead of `npm` fails locally

### ISSUE THREAD

**Issue by cmbirk** [reactioncommerce/reaction#5332]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Running the integration test suite with `yarn test:integration` instead of `npm run test:integration` results in the error: `Cannot find module 'core-js/proposals/array-flat-and-flat-map' from 'array.js'`.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Run `nvm use` to use the correct node version and `npm install` to ensure the dependencies are up to date
2. Run `npm run test:integration` - see that it runs successfully
3. Run `yarn test:integration` - results in the error mentioned above

## Possible Solution
The error does seem to be a known issue with `apollo-graphql-server`: https://github.com/apollographql/apollo-server/issues/2263. It may be that the package needs updated or a resolution statement included in package.json. This is just speculation.

### Versions
(run `reaction -v` from your reaction directory)

```
Node: 8.11.3
NPM: 5.6.0
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
Reaction: 2.0.0-rc.10
Reaction branch: develop
Docker: 18.09.2
```

**Comment by cmbirk** [comment]
cc @focusaurus

**Comment by focusaurus** [comment]
My only comment at this point is that for reaction-core it's still npm-based and there's no yarn. That is partially because there's still `meteor npm` involved with plugin dependencies. Yarn is not something I want to include in core if at all possible so for now the solution/workaround is "don't do that". But if there's an easy update that will avoid this error in the case someone uses a locally-installed yarn, I'd be fine with that.

**Comment by aldeed** [comment]
Agree, mixing and matching `yarn` and `npm` doesn't work reliably. This is an NPM repo, which is why `yarn.lock` is gitignored. It *should* work if you `yarn install` instead of `npm install`, but the build script that installs plugin dependencies uses `npm install`, so you'll end up with a mixture that may not work anyway.
