### ISSUE TITLE
Bulk Tag/Product Feature: Show tags on list of products

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5370]
As a user, I should be able to see which tags are already associated with the list of products.

**Comment by machikoyasuda** [comment]
@cassytaylor Are there designs for this? I saw this in the "User Stories" list from Notion, but I don't see it in Zeplin or inVision.

**Comment by cassytaylor** [comment]
Hmm there are no designs for this currently, apart from the "inverse" way - which would be viewing a single tag via its Tag Details Page and seeing the table of products that are associated with it. 

If we added a Tags column to the main Products table, we'd probably need to show some sort of tooltip on hover of each cell that would show the entire list of tags. Otherwise, adding a Tags column would probably be pretty useless as you'd only see one or two in the column (or half of one even, since tags can be so long and wordy.)

**Comment by machikoyasuda** [comment]
@rymorgan Can we remove this User Story/GitHub ticket?
