### ISSUE TITLE
Bulk Tag/Product Feature: Product table's Action dropdown should always be shown

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5388]
Currently, the dropdown is only shown when there are products selected.

It should always be shown.

**Comment by machikoyasuda** [comment]
@cassytaylor Since the Action dropdown needs to always be shown now..

When there are 0 products selected, should the Dropdown still show options that require products, like Archive, Make Hidden/Visible? Or should those options be disabled, like a disabled button? I can either Hide them entirely or make them Disabled, depending on whether there are products selected or not.

**Comment by cassytaylor** [comment]
@machikoyasuda I'd keep those options visible, but disable them (like in this mock -> http://zpl.io/V0wg7Zx which only shows "Filter by file" enabled, because it doesn't require products to be selected.) 
That way if the operator is poking around without any products selected, and they select the dropdown, they'll be able to preview what the bulk actions are.
