### ISSUE TITLE
Enforce idempotency on placeOrder

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5390]
We need a way to enforce that orders are placed once and only once probably using some sort of `idempotency key` similar to what Stripe and Braintree do. This probably would not be hard but some discussion about how we should generate this key and how exactly it should work needs to be discussed.

A typical scenario would be to use cart items/total + customer information to generate the key and that this key must be unique with say 5 minutes or so.

There may be other places we need to enforce idempotency but I think placeOrder is probably the really critical one.

**Comment by aldeed** [comment]
Discussion with @rosshadden and @focusaurus about this:
- When an order comes from a cart, we can enforce idempotency by having a unique index on `cartId` in MongoDB. It is an optional field so it will need to be sparse. It does not appear that we currently have this index being created in the code.
- But orders can be created without a cart, so some solution is needed for that
- We might be able to reuse `clientMutationId`. All mutations have this optional param, but its main purpose is to help Redux match requests with responses in its cache. https://facebook.github.io/relay/graphql/mutations.htm#sec-Mutation-inputs The spec suggests version 4 UUIDs for this.
- If we don't want to mix uses for `clientMutationId`, we could add a similar field but call it `idempotencyKey`
- Whatever we do, we'd prefer to implement this as a general response caching layer, possibly using Redis. If there is something open source that exists, even better. The basic idea would be to identify a request as being a duplicate within some small timeframe, and re-return the previous response.
- So far we have only one example storefront, and it does use a cart and pass a `cartId` when creating the related order. So adding the unique index is the biggest and most important win here. The more robust solution will be necessary once some people decide to build a frontend that creates orders directly without first adding to a cart, or when we add ability to create orders directly in Reaction Admin.

**Comment by sneko** [comment]
Hi,

Sorry to ask here but I'm also looking at a way to do idempotency across all my sensible requests. Did you end up with a specific implementation? If so, I'm interested how you did that 👍 

@aldeed you talk about caching the first successful response in case a second request happens, so you can return it directly. Is it a well-known pattern?

Also in case I have several API instances, storing previous requests in a Redis cluster sounds like slowing down all the requests (since through network). I thought about using in-memory Redis to speed up this kind of checks, but it would imply my loadbalancer routes a specific user `A` "always" to the same API during its connection, maybe based on his IP address... what do you think? Have you ever seen that?

Thank you,
