### ISSUE TITLE
Add webkit-font-smoothing: antialiased to all type

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction#5419]
Open to how to implement this

**Comment by machikoyasuda** [comment]
@kieckhafer Could we just add `-webkit-font-smoothing: antialiased` to `<body>`?

**Comment by kieckhafer** [comment]
I was thinking on the `typography` object of the styling instead of on the body, but yeah, either or I think should work: https://github.com/reactioncommerce/catalyst/blob/master/package/src/theme/defaultTheme.js#L48

I guess for Buttons and non-`<Typography>` text though the `body` might be better.

**Comment by machikoyasuda** [comment]
Closing b/c this ticket exists in Catalyst now.
