### ISSUE TITLE
Spike: Investigate transitioning from Simple-Schema to Mongo Schemas

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5481]
Now that Mongo schemas have been out for a while, we should look into them and see how they could be leveraged to add a better level of data integrity/performance to using Simple-Schema.

**Comment by janus-reith** [comment]
I wondered the same thing when I found out that `attachSchema` is something Meteor-based that will become obsolete.

While the whole stack is tied tightly to mongoDB and there don't seem to be alternatives yet, I still wonder if it would be possible to keep the Schemas database-agnostic and simply enhance Simple-Schema to make use of Mongo Schemas where available.

Maybe Simple-Schema could somehow pass through data were applicable and thereby still give performance benefits.

And while we are at it: Moving a reference of the schema definitions to each `registry.js` would really help keep things more structured, as collections and their indices are defined there aswell. Currently all of them still are in `/imports/collections/schemas`, while `attachSchema` happens in /lib/collections and for some collections in the `/lib` or `/client` folder of plugins.

**Comment by focusaurus** [comment]
Getting mongodb schemas going and enforced in the db: :+1: 

JSONSchema seems like the most pragmatic approach. Hopefully we can find a good implementation of validation on npm. I've used a few in the past and the quality was so-so.

One stack to consider would be migrating our SimpleSchema code to `joi` and finding an npm package that could convert/downsample that to JSONSchema for mongo.

**Comment by aldeed** [comment]
I've used `joi` a bit and it's nice for what it is, but may not be best for the needs here. I recently tried [superstruct](https://github.com/ianstormtaylor/superstruct) and there are a few things I didn't like but overall it probably does not get much simpler, with the added benefit of being fast and everything being strings and scalars, which means it might be the easiest library to write a JSONSchema transform for.

**Comment by janus-reith** [comment]
I think it could be great to find a solution where we could also derive GraphQL types from, so Schemas don't need to be written twice.

**Comment by janus-reith** [comment]
Hey, has there been any further discussion on this and did someone maybe come up with a new idea?

**Comment by aldeed** [comment]
I'm not aware of any further discussion. The last I heard the thought was that a single plugin could try implementing mongo schemas for the collections it owns as an example and a trial, and then evaluate based on that. If someone wants to do a PR for that at some point, that could get things moving.

**Comment by janus-reith** [comment]
Hm, I would only want to put effort into a solution that reduces verbosity, by defining e,g, Product at a top level, then deriving both Apollo and DB Schemas from it, and whatever validation layer might be called on api calls then.

@aldeed do you know any solution that compiles down to both GraphQL Schemas and jsonschema?
I did a quick search but found nothing.

Another thing I had in mind, for typical calls we would then have three steps:
Apollo Schemas -> Validation in Function -> MoongoDB JSONSchema.
We can't really skip any of them completely, and while Apollo Schemas and MongoDB Schema probably have a small footprint on performance, the Validation inside a function might have one but also offers the most specific possibilities of validation and also might be necessary in cases where it prevents sideffects inside some function, as we don't necessarily have a straigt path where data goes from where. (Hope it is clear what I mean?)
So maybe it might be possible without added complexity inside some called function, to see if that has passed graphql validation, and therefore inside that next validation step, skip all field validations that are not more specific than thei already checked Apollo pedant - Just an idea.
All fuctions, e.g. queries on context should still work outside from being directly called from a graphql call, therefore this should stay optional. If only function parameters would work as sure indication that something passed graphql validation, those could be set on each of the resolver when they call queries on context as someoptiona parameter. But maybe this wouldn't even be necessary if we could gain insights on the chain from context itself maybe.

Would love to hear your ideas and opinions on this.

**Comment by aldeed** [comment]
- An abstract solution sharing or generating GraphQL schemas from JSONSchema or other data schema will never be possible, IMO. There are too many differences, many of them necessary.
- The main place where JSONSchemas stored in MongoDB would be useful is in create/update mutations, where we are currently using SimpleSchema validation on the full doc or modifier, immediately before we insert/update. These could be removed in favor of letting MongoDB do it, which should cut down on the memory usage and in theory can be done with better performance by Mongo. Another benefit is that external systems could write directly to the DB without fear of inserting invalid data.
- Resolver functions do tend to rely on GQL schema validation, not doing any additional validation. But the internal query and mutation functions typically redo argument validation because they are also sometimes called internally for ETL and other reasons. The best improvement here would be beginning to move to TypeScript, which is going to be a much faster way to validate arguments versus SimpleSchema or really any other validation library.
- If you want to explore generating one type of schema from another, some way of defining TypeScript types and having those convert to JSONSchema and attach to Mongo collections would be probably the best possibility of reducing overlap. But it might be a bit premature to dive into that right now since none of the plugins are TypeScript yet.

**Comment by set321go** [comment]
I did a minimalist spike today just looking at adding a schema to a collection and getting it into mongo. 
https://github.com/reactioncommerce/reaction/compare/trunk...set321go:SPIKE_5481

Its not a true conversion of the Shop schema 
1. I omitted anything that was marked as deprecated
2. I removed blackbox objects and just made them strings
3. I changed dates into strings because there is no native date type

I realized while i was doing this that the mongo implementation of jsonSchema has quite a few [limitations](https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#omissions). Some of the big ones that i was planning on using were:
1. `definitions` & `$ref` so you're unable to split up a large object and compose it like is already done in `simpl-schema`.
2. `default` many places where a required value is specified it would have been handy to  specify the default value

If i was to extend this and use it for validation in the app i would probably use the [ajv](https://www.npmjs.com/package/ajv) package as it has clear instructions/support for using different versions of the spec.

EDIT: I should probably add that I am in favour of a solution that uses something that is not specific to mongo. json-schema is a good option as its wide support makes it portable and robust, I like Joi as an option but I think json-schema has more going for it in this situation.

**Comment by aldeed** [comment]
@set321go This is very helpful research, thanks! I did not realize `$ref` isn't supported. That is unfortunate. Default values aren't critical but would also be nice. I see a longstanding issue for that here: https://jira.mongodb.org/browse/SERVER-24430

Note that to be the same as SimpleSchema, every object will need `additionalProperties: false` in the JSONSchema because the default is `true`. For the `blackbox: true` objects, those can be objects with no defined properties and `additionalProperties: true`.

I like your implementation in `ReactionAPI.js`. If you want to submit a pull request with only the changes from that file, I think we could merge that pretty easily and it would allow other people to experiment more with this. When you get the shop schema in a place where it's identical, you could submit a pull request for that, too. I'm not certain whether we're going to go down this road with the built-in plugins, but a PR would be a good way to test and discuss the pros and cons.
