### ISSUE TITLE
[v2.3.0] Shipping Handling is calculated twice at checkout

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#5572]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE REQUESTS ACCEPTED. For new features, add an issue in our [Request Feature Request](https://github.com/reactioncommerce/reaction-feature-requests) repository.

Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
Shipping Handling is calculated twice in Order
At checkout getting error "Client provided total price {amount} for order group, but actual total price is {amount}"while placing order

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. In admin portal, add Flat rate with any value in handling and rating (eg: Handling=3, Rate=10)
2. Add a product to cart and checkout and place order

Attached screenshots:
Here,
Product price is 100
Shipping Handling is set 3 
Shipping Rate is set 10. 
Order total is $113 (100 + 3 + 10) 

Error: Client provided total price 113.000 for order group, but actual total price is 116.000

Actual total price calculates Handling price twice

![Screen Shot 2019-09-19 at 11 52 16 PM](https://user-images.githubusercontent.com/12378687/65306106-7ab7de80-db39-11e9-9b42-8e7d9332a4e7.png)
![Screen Shot 2019-09-19 at 11 52 34 PM](https://user-images.githubusercontent.com/12378687/65306114-7f7c9280-db39-11e9-8ff1-67a5335e7a6b.png)

### Versions
Reaction - v2.3.0

(run `npm run version --silent` from your reaction directory)

**Comment by aldeed** [comment]
@vigyano Thank you for the report. This is really more of an issue with the example storefront checkout. It needs to update its `cart` cache more often, and especially just before showing the final review step. The expectation should be that the API will be continually recalculating amounts and totals whenever anything about the cart changes.

Note that even with perfect refetching on the client, this error can happen. For example, a price change may be published by an admin right before you press the Place Order button. The storefront should do a nicer job of detecting this error, refreshing the screen, and helping the user place their order.

Specific ideas for storefront changes (might be good to open storefront issues for these):
- set the cart checkout data query to poll every few seconds
- refetch the cart checkout data when moving to the final review step
- detect when this mismatch error comes, refetch the cart checkout data, and show a nicer error like “Some prices may have changed since you started checking out. Review the updated order totals and place the order again if you still want to place it.”
- make sure Apollo is updating the cache with the updated cart that comes back from each mutation at each step of checkout
