### ISSUE TITLE
Check for the existence of reaction/getUserId method and whether it still required

### ISSUE THREAD

**Issue by quophyie** [reactioncommerce/reaction#5834]
Check for the existence of reaction/getUserId method and whether it still required

**Comment by rosshadden** [comment]
What does this mean? What is it needed for? What are the implications of doing or not doing this?

**Comment by rosshadden** [comment]
@mikemurray can you provide any insight on this?

**Comment by trojanh** [comment]
I think what it means is we earlier had [`Reaction.getUserId()`](https://github.com/reactioncommerce/reaction/blob/b03e63be07a34c75a38100584d3dd60de407251e/imports/plugins/core/accounts/server/methods/index.js#L35) method to identify the logged-in user which was using meteor, now we need to identify if it's being used anywhere and if so, do we still need to use it ?

In my opinion, we had already removed that method a long time back and it shouldn't be present in the `v3` branch as far as I can find.

That said, we still have it in [reaction-admin](https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/accounts/server/methods/getUserId.js) which must be intentional and expected.

**Comment by willopez** [comment]
resolved via https://github.com/reactioncommerce/reaction/issues/5747
