### ISSUE TITLE
Cart token and order token are not the same.

### ISSUE THREAD

**Issue by samkelleher** [reactioncommerce/reaction#5891]
When checking out anonymously, the cart has a token and a "reference ID", and a cart ID.

Once converted to an order, the order has a new ID, the same "reference ID" and a new token.

The conversion from cart to order happens in the placeOrder call, where the cart is ultimately deleted, and the order saved.  A few other things happen during this call, and is one of the slowest and most critical.

"In the wild" it's possible that when a customer calls placeOrder, their device does not receive the response to placeOrder (lousy networking etc etc).  The call has ultimately completed, but if they try again (or refresh the page), they get a cart doesn't exist error, because placeOrder was successful and deleted it, they just never got the success response. We only clear the cart cookie when we get the successful result from placeOrder.

In this situation where a storefront gets a cart not found error, it would be possible for it to use the existing cart token and cart reference ID to try load an order, and thus take them correctly to the order completion page. But since the tokens are different, we're stuck on an empty cart state which is confusing.

Logged in state doesn't apply since it would be possible to see if an order exists given the cart ID.

Proposal is when an order is made, use the same token as it existed on the cart, don't generate a new one.

**Comment by aldeed** [comment]
The proposal could be fine. It's only a partial solution, but there may be no better one.

A summary of the issue is "what if my order is placed but for some reason I don't get the response with the token to access it."

Your solution should work when a `cartId` is passed but orders can be placed without a cart, and it relies on the client to know it should pass the cart token to the order query.

For cartless orders, I'm not sure there is any good solution. It's one of those edge cases that happens.

But in either case, I assume they would get a confirmation email, which would have a link, and the link should have the order token embedded in it. So the immediate aftermath might be confusion but if they check their email for the confirmation they'll realize it was placed and be able to see the order page.

As far as the "cart doesn't exist" error, it seems storefront could detect that and delete it's stale id/token behind the scenes without showing the error message to the user. Just show empty cart.

**Comment by aldeed** [comment]
@ticean or @mpaktiti , anything to add here? Can you think of any security concerns with copying the hashed token from the anonymous cart to the anonymous order rather than generating a new one for the order?

**Comment by mpaktiti** [comment]
@aldeed I can't think of something, it looks acceptable to me.
