### ISSUE TITLE
Login Hydra route is not found

### ISSUE THREAD

**Issue by jm18457** [reactioncommerce/reaction#5940]
## Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you able to consistently reproduce the issue?
* [ x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
When trying to log in through storefront it does not work.
Logs `console.log('currentRoute', currentRoute)` return not found result
Image provides said `console.log`.

![image](https://user-images.githubusercontent.com/20977577/71094811-e139b080-21ab-11ea-9f82-24b4eb24a78b.png)

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Start entire platform
2. Go to storefront and try to log in.
3. Do not be logged in

**Comment by spencern** [comment]
@manueldelreal can you take a look at this and see if it's related to any of the current bugs we're looking into?

**Comment by manueldelreal** [comment]
@spencern we are not seeing this error on the current 2.9 WIP branch. 

@jm18457 for which version are you seeing this one?

**Comment by jm18457** [comment]
@manueldelreal I tried setting up fresh install, but I am met with [Invalid-client error for hydra](https://github.com/reactioncommerce/example-storefront/issues/606#issuecomment-567248166) so I could not test it.


The basic idea regarding testing though, is that [isOauthFlow](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/components/login.js#L61) determines whether we should call [hydra react component](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/components/login.js#L66)

By going to URL generated from storefront for hydra auth (I don't know if this url changed with 2.9 as my local setup for 2.9 does not work due to issue mentioned at the start of comment) http://localhost:3000/account/login?action=signin&login_challenge=042ba25abaed43f29ee8717afe602340 and adding console logs to [line 64](https://github.com/reactioncommerce/reaction/blob/master/imports/plugins/core/accounts/client/components/login.js#L64) I receive the following logs:

![image](https://user-images.githubusercontent.com/20977577/71234632-f4f32d00-22f9-11ea-8cc8-8f541357d880.png)

**Comment by manueldelreal** [comment]
@jm18457 If you are running 2.x it might be that your hydra client is not created; there's a script for it in the storefront container code. Could you try going into your container and running the `create-hydra-client.js` script under the bin folder?

**Comment by jitenagarwal19** [comment]
@manueldelreal Thanks, running the script specified by you seemed to solve the problem. But, can we mention in any doc somewhere?
I am currently running the basic setup of reaction. When I click on login it takes me to localhost:3000 from localhost:4000 and after login it stays there(localhost:3000). When I manually comeback to localhost:4000 no user is signed in. Am I doing anything wrong here or is there a step that I am missing?

**Comment by jmaver-plume** [comment]
@jitenagarwal19 Login should not work due to bug specified in this issue.
Route is not-found =>Hydra Oauth is not triggered (only basic localhost:3000) is triggered => you log in and do not get redirected to hydra.

Issue is similar to #5726 as in logged out user does not have valid routes.

@YuuwakU found [issue](https://github.com/reactioncommerce/reaction/issues/5726#issuecomment-546810149)

I think it is related to de-meteorization of reaction.
If I understand correctly before de-meteorization "empty" user was created when logged out user came to `localhost:3000` (as in user without email).

I assume this made all routes be accessible. After empty user stopped being created, then there were no logged in users and routes stop being accessible.

@manueldelreal I will try your fix when I get home and see if login works. Which branch should all my repositories be? Is master sufficient or develop?

**Comment by manueldelreal** [comment]
@jm18457 master should suffice as the script is in the recent 2.9 tag. For 3.0.0 the client is created automatically but maybe we should backport that process so that it is also created on the 2.X tags as well.  (CC @spencern @aldeed )


@jitenagarwal19 that redirect issue should be fixed on 2.9.1 (already tagged)

**Comment by aldeed** [comment]
The Hydra client should be auto-created in 2.x as well, but it is part of the Docker Compose scripts so it is less reliable and won't work if you run without DC. In 3.0 it's part of the actual storefront server startup code so it will always happen, even in deployed environments. I think it would be possible to backport that change to 2.x, but it's an older version of Hydra, so we'd have to confirm it has everything we need.

As far as documentation, the 3.0 docs are much more explicit about Hydra clients, so I think we'll be good after those are released.

**Comment by aldeed** [comment]
@jm18457 Are all your concerns resolved in 2.9.1? If so can you close this?
