### ISSUE TITLE
create  createNavigationTree mutation and an integration test for it.

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction#6011]
### Issue Summary
In order to support switching between multiple navigation trees in the admin UI, there needs to be a mutation to create navigation trees: `createNavigationTree`, which does not exist at the moment.

**Comment by trojanh** [comment]
@willopez is this same as [createDefaultNavigationTreeForShop](https://github.com//reactioncommerce/reaction/blob/d587c859a8809b3df80088f16376d7039e0e8928/src/plugins/navigation/util/createDefaultNavigationTreeForShop.js#L6) with the ability to allow the some of the inputs in `createNavigationTree` mutation variable ?. 

If yes, what all fields are we planning to take from as input in this mutation?

**Comment by aldeed** [comment]
@trojanh I think the only part of `createDefaultNavigationTreeForShop` that would be the same is this:

```js
// Create the tree
  const navigationTreeId = Random.id();
  await NavigationTrees.insertOne({
    _id: navigationTreeId,
    draftItems: items,
    hasUnpublishedChanges: true,
    items: [],
    name,
    shopId
  });
```

I would start from `updateNavigationTree` mutation function, but without `navigationTreeId` param because it will be randomly generated. Remove some things where they don't make sense, such as checking for an existing record. Instead of `NavigationTrees.updateOne`, do the `insertOne` above. 

The rest will be pretty similar to an update. In the gql schema unfortunately the existing `input NavigationTreeInput` won't be suitable because `name` should be required. I'm not sure the extra layer is needed anyway. I suggest adding this gql:

In `extend type Mutation` block:

```graphql
"Create a new navigation tree"
  createNavigationTree(
    "Mutation input"
    input: CreateNavigationTreeInput!
  ): CreateNavigationTreePayload!
```

And the new types:

```graphql
"Input for the `createNavigationTree` mutation"
input CreateNavigationTreeInput {
  "An optional string identifying the mutation call, which will be returned in the response payload"
  clientMutationId: String

  "The draft navigation items that make up this tree"
  draftItems: [NavigationTreeItemInput]

  "The name of the tree, for operator display purposes"
  name: String!

  "The ID of the shop this navigation tree belongs to"
  shopId: ID!
}

"Response payload for the `createNavigationTree` mutation"
type CreateNavigationTreePayload {
  "The same string you sent with the mutation params, for matching mutation calls with their responses"
  clientMutationId: String

  "The created navigation tree"
  navigationTree: NavigationTree!
}
```

The tree should be created with the name and `draftItems` that are given, but `draftItems` isn't required. It shouldn't have `items` because those are created after they publish it.

**Comment by trojanh** [comment]
Great @aldeed , that was very helpful. I am working on a PR for this issue.

**Comment by mian-muhammad** [comment]
I can see `createNavigationTree` mutation but I think relevant role is missing from roles collection mongodb, here is what I have tried, any help will be appreciated @trojanh @aldeed  correct me if I am wrong, Admin authorization token was included 

![Screenshot from 2020-10-15 10-33-19](https://user-images.githubusercontent.com/20898558/96082140-1dc16000-0ed4-11eb-8bef-d615e4b36a11.png)
