### ISSUE TITLE
Post documented reaction release support schedule

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction#6109]
Spencer and I discussed making sure Reaction's default support timeline and policy for our releases is documented and posted properly. This issue is to track that work.

**Comment by spencern** [comment]
Thanks @focusaurus

**Comment by HarisSpahija** [comment]
Can we combine these across platforms? I want to release my i18n implementation hopefully end of next month. Would be kinda nice to see that the other repo's (reaction-admin, example-storefront, component-library, reaction) each have their respective roadmaps and policies.

For component library we just update it whenever there is a PR instead of bundeling items and making a difference between major and minor releases. Bugfixes that solve security should be flagged as important releases and not crawl between minor release notes.

Tagging @aldeed since he has been helping me make sense of things that needed to be done on both component-library and example-storefront.

@aldeed Are you in charge of releases on these repo's? If not, can you tell me who is?

**Comment by aldeed** [comment]
@HarisSpahija 

@kieckhafer is in charge of all releases. Component library auto-releases with semantic release. The goal is to do that with example-storefront, too, I think. And new API plugin repos will also auto-release. Auto-releases happen on every merge to `trunk`.

For now `reaction`, `reaction-admin`, hydra, and the development platform are still manual release processes, every week or two.

I don't know that we have any good plan for calling out certain bug fixes as important, especially as more and more projects are released automatically. Everything follows semantic versioning, so a bug fix is always going to increment the patch version regardless of how important it is. I'm sure @kieckhafer has some thoughts here.

**Comment by kieckhafer** [comment]
@HarisSpahija

As @aldeed mentioned the goal is to get `example-storefront`, and almost every other package we have that's part of the `reaction-development-platform` setup, into the auto-release pattern with `semantic-release`. 

At this time, `reaction` is the only non-beta repo I'm purposefully holding off on adding the `semantic-release` package to, because we want to keep a little more control on the releases there at this time. Once we finish moving the bulk of our internal packages into their own auto-published npm packages, the plan is to get `reaction` on an auto-release schedule as well (we've already started, https://github.com/reactioncommerce/plugin-authentication for example).

Also as @aldeed mentioned, we don't currently have a plan to categorize certain patch fixes as extra important, and I'm not entirely sure we should be categorizing specific fixes different than others. The opinions on what constitutes a "more important" fix will vary per person, per issue, and since one of the goals here is to take the human side out of releasing as much as possible, there shouldn't be much - or any - opinion thrown into the process.

That being said, perhaps after the fact, we could call out fixes deemed to be security related in a bigger way in our release notes, a blog post, or other ways.
