### ISSUE TITLE
Missing field "description" in input schema in createShop mutation

### ISSUE THREAD

**Issue by CristianCucunuba** [reactioncommerce/reaction#6147]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? 

## Issue Description

The `description` field is missing in the input schema when you are creating a shop. It's defined in the graphql schema but not in the validation schema. So, if you create a shop with description, the API throws a validation error 

## Steps to Reproduce

1.use createShop mutation and pass it the description variable

## Possible Solution

define `description: String` in the input schema 

### Versions
3.1.0

**Comment by aldeed** [comment]
The fix is this:

Add this:

```js
description: {
    type: String,
    optional: true
  },
```

Here: https://github.com/reactioncommerce/reaction/blob/trunk/src/core-services/shop/mutations/createShop.js#L20

Then add `description` [here](https://github.com/reactioncommerce/reaction/blob/trunk/src/core-services/shop/mutations/createShop.js#L62) and add it to the `const shop = {` properties.

We seem to be missing `createShop` integration tests in `tests/integration/api/mutations`, so this would be a good time to create them to verify this fix and ensure there aren't other issues. (I don't see any other missing fields based on a visual check.)

**Comment by aldeed** [comment]
Fix is in shops plugin 1.0.1. Still needs to be pulled into the API and write integration test.
