### ISSUE TITLE
allowGuestCheckout default value is NULL

### ISSUE THREAD

**Issue by HarisSpahija** [reactioncommerce/reaction#6185]
## Issue Description
When querying for allowGuestCheckout 
```
query { 
	primaryShop {
    allowGuestCheckout
  }
}

returns

{
  "data": {
    "primaryShop": {
      "allowGuestCheckout": null
    }
  }
}
```
Due to the default setting being null 

on [placeOrder.js](https://github.com/reactioncommerce/reaction/blob/4890007760db489a68fe0bfb81f81f86525f8498/src/core-services/orders/mutations/placeOrder.js#L135) fails unless mutated trough graphql queries. 
```
  if (!userId && !shop.allowGuestCheckout) {
    throw new ReactionError("access-denied", "Guest checkout not allowed");
  }
```

## Steps to Reproduce
1. Start a new reaction project trough make
2. Try to checkout
3. Checkout fails with error message: Guest checkout not allowed

## Possible Solution
The default value of the guest checkout should be either true or false but not null. Currently because guest-checkout is not able to be set trough reaction-admin it is best to make the default value true in order to maintain a successful checkout flow trough the make tool

### Versions
`"version": "3.4.0"`

**Comment by manueldelreal** [comment]
While the default is `null` checkout can be completed for logged in users as long as you are providing the authorization token, and that behavior is the same as if we made the default value false, that would not be a breaking change. 

We see the value in defaulting to `true` as any commerce site would want to make checkout as easier as possible, there are some implications for setups that already explicitly defined it as `false` via an `updateShop` mutation, so that would be a breaking change for them. 

The change from defaulting to `true` would have to be packaged in another release, but definitely not on its own as a patch. We'll keep this one in our radar for the next one.

And for whoever else is reading this issue and didn't find the mutation in the docs, you can change the value for the setting via graphql with the following mutation:


``` 
mutation {
  updateShop(
    input: {
      shopId: <_id>
      allowGuestCheckout: <boolean>
    }
  ) {
    shop {
      _id
      allowGuestCheckout
    }
  }
}
```
