### ISSUE TITLE
Figure out how to delegate node debugger ports across application

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#6191]
From https://github.com/reactioncommerce/authorization/pull/130

> I don't know what we should do here but I can't help thinking we should try to solve the larger problem which is that we have this problem across all node projects. There are other ports that node debugger listens for automatically that we could use (like 9222), but we have many node projects and would quickly run through those. We could make them all relate to the main service port, so this one would be 6009, reaction's would be 3009, etc. (arbitrarily choosing 9 as the ending port digit).
> 
> It might be best to remove the exposed node debugger port on all of our containers, including reaction. We have services where we do not expose the port, and when I debug those services I expose the port myself. It's not that much hassle and people working with docker should know how to use the --publish flag.
> 
> What do you think?

**Comment by focusaurus** [comment]
I'm OK with either:

- Never publish the node debug port automatically. Developers publish via command line as needed
  - Tradeoff: initial instructions are probably a bit harder
- Publish only on the api project since so much code runs in there
  - Tradeoff: fairly likely to conflict with other assorted node projects a developer might have running in debug mode
