### ISSUE TITLE
database settings in reactioncommerce

### ISSUE THREAD

**Issue by price2b** [reactioncommerce/reaction#625]
I installed reactioncommerce and I would like to access the database settings to check the name that the installation created in my mongodb server. I checked the information on the website but I cannot find any details about it.

in mongodb: when I use "show dbs" in mongo I cannot see any new db in my server. on the other hand, the demo application is running on port localhost:3000.

any guidance appreciated.

**Comment by zenweasel** [comment]
The mongodb for meteor always runs at one port above the meteor port. So by default the db is running at 3001. While you can have Meteor running you can also run meteor mongo and get a db console that way.

**Comment by jshimko** [comment]
@price2b As @zenweasel mentioned, you can open another terminal window while your app is running and run `meteor mongo` in that window to get a mongo shell.  

http://docs.meteor.com/#/full/meteormongo

Or if you prefer, you can use something like [Robomongo](http://robomongo.org/) to explore the database with a GUI.  Assuming you're running Meteor on the default port 3000, you would connect to the database on port 3001.  No auth required.

**Comment by price2b** [comment]
thank you so much. Im confused, mongo installation in my computer is running on port 27017 but I meteor db runs in port 3001. do you know if it creates its own installation of mongo outside of the default installation in port 27017?

**Comment by jshimko** [comment]
Yes, Mongo is included with Meteor.  If you installed Mongo separately on your computer, it is not the version Meteor is using.  Although you could optionally point Meteor at that install by setting your `MONGO_URL` to `mongodb://localhost:27017/somedb`, but I'm not sure there's any good reason to do that (other than perhaps testing a different version of mongo).  That'd mostly be extra complexity with little or no gain.  You'd also lose the `meteor mongo` convenience tool.

**Comment by price2b** [comment]
thank you jshimko!.

**Comment by nilesh0604** [comment]
Hi @jshimko I'm new to the "reactionCommerce" world. I am planning to use reaction for my small eCommerce project. I'm on a bit low budget for this project so can you please suggest some options to push this project live with low cost?

**Comment by ticean** [comment]
Hi @nilesh0604. We don't provide endorsement for any MongoDB providers but there are a few to choose from. Here's a link to [a similar question on Quora with answers](https://www.quora.com/What-is-the-best-MongoDB-hosting). The advice in the top answer seems reasonable to me.

If you're going for absolute cost value then the cheapest solution would be to run your own MongoDB on the host of your choice. Be aware that you will assume the responsibility of maintaining that instance and ensuring it's availability, along with your own backup & restore plan. Maybe you are OK with that, but since you ask the question here, I assume that you need some help and are looking for a hosted solution.

You could compare these to get started. I'm just providing a quick list. There are others out there too.I think most of these offer plans on Heroku, too. That can be an easy way to get started, and it's fairly cheap for light usage.

* https://mlab.com
* https://www.compose.com/databases/mongodb
* https://www.mongodb.com/cloud/atlas
* https://mongodb.scalegrid.io
