### ISSUE TITLE
Extend the Product Schema from Plugin

### ISSUE THREAD

**Issue by victors1681** [reactioncommerce/reaction#6323]
## ❓ Questions and Help

I'm building a new plugin for reaction-api, In this plugin, I want to add all custom properties for `Product`  and `Order` collections. 

I'm not able to access to `Product` schema from `from "/imports/collections/schemas"` because I'm working on a new package. The question is, is there any way to achieve this using the `app.context` `export default async function register(app) { }`

Please feel free to let me know if I'm doing something wrong and suggest to me the best approach.

**Comment by loan-laux** [comment]
@victors1681 You can extend schemas using the `simpleSchemas` field in your `app.registerPlugin` call. See `api-plugin-accounts` for an example of that.

With that being said, since this is a bug tracker, this issue will be closed by an admin. If you have further questions, feel free to ask them on [our Gitter channel](https://github.com/reactioncommerce/reaction). Thanks!
