### ISSUE TITLE
how to use paypal payment?

### ISSUE THREAD

**Issue by epubreader** [reactioncommerce/reaction#6327]
how to use paypal payment?
Thanks.

**Comment by loan-laux** [comment]
Thanks for your interest in Open Commerce, @epubreader. To answer your question, there's no open-source PayPal plugin for Open Commerce as far as I'm aware.

Since this is a bug tracker, an admin will close this issue. For questions about Mailchimp Open Commerce, feel free to use [our Gitter channel](https://github.com/reactioncommerce/reaction).
