### ISSUE TITLE
Update to MongoDB 5

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/reaction#6383]
MongoDB 4.2 will reach EOD soon. We should update to MongoDB 5 (if there are even breaking changes at all).

**Comment by brent-hoover** [comment]
There are some significant breaking changes between the 4.x driver (which is required for 5) and the current 3.x driver

None of them are crazy hard to fix but the current code will absolutely not work with 4.x

**Comment by brent-hoover** [comment]
The two major changes I encountered was:

1. The way you instantiate the driver is different. https://github.com/mongodb/node-mongodb-native/blob/4.1/docs/CHANGES_4.0.0.md
2. If you are using something like `findOneAndUpdate` you must change `returnOriginal: false` to `returnDocument: "after"` if you want the updated document. This one is critical because it will not throw an error but just give you the old document

**Comment by janus-reith** [comment]
>This one is critical because it will not throw an error but just give you the old document

Wow, changes like this are hard to understand.

**Comment by janus-reith** [comment]
I wonder if we could just provide an easy migration path here to keep compatibility.

Especially regarding that case of `returnOriginal`, since calls don't go right to the mongodb package but `context.collections`, we could use that as a wrapper and set `returnDocument` accordingly and maybe log a warning about it being deprecated.
Same for other potential breaking changes.

That way required changes could be limited to api-core and other packages could be migrated gradually.

**Comment by brent-hoover** [comment]
Just coming back to this to say that these changes go even deeper because RC relies on certain elements of the Mongo driver that no longer exist. This affects how pagination works and a bunch of things. This will need to be a significant engineering effort

**Comment by brent-hoover** [comment]
That being said Mongo 4.4 is not End of Life until Feb of 2024
