### ISSUE TITLE
Exception when adding to cart

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#722]
Received this exception:
```00:36:33.191Z  INFO inventory: no inventory found, create 62 backorder

Exception in callback of async function: MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: meteor.Inventory.$_id_  dup key: { : "HHbPtJ4yMpWXNoimA" }```

Steps to reproduce:
1. Change change product data spec for `inventoryQuantity` to a much larger number
2. `reaction reset && reaction`
3. Navigate to product page and hit up slider to add quite a few items to cart.
4. Hit "Add to Cart"
5. Receive exception

You can make this happen with lower quantities but that large number seems to make it happen quickly.

I was trying to make a cart amount > $2000 so that I can test Braintree declining cards (and apparently I am not smart enough to just change the price of the one product)

**Comment by aaronjudd** [comment]
I'm not sure if we updated the inventory to use batchInserts, but if it's still cycling through each record and inserting I'm guessing that could be the root cause here..

**Comment by newsiberian** [comment]
I changed `batchInserts` to [unorderedBulk](https://docs.mongodb.org/manual/reference/method/db.collection.initializeUnorderedBulkOp/) in next PR. If this not helps, we still could try [orderedBulk](https://docs.mongodb.org/manual/reference/method/db.collection.initializeOrderedBulkOp/#db.collection.initializeOrderedBulkOp)

**Comment by newsiberian** [comment]
Hello, I have some findings on this.
First - specifically this bug is solved. It was caused by `inventory/backorder`'s `Inventory.insert`. I've updated it to `bulkOp` and now it works, BUT,
if play more aggressively with `add to cart` button, for example do the following:
add few thousand to items to "green" before test.
test: choose "red" -> add 99 items -> add to cart; choose "green" -> add 99 items -> add to cart; and so on as fast as you can, you could faced with:
```
Exception in callback of async function: MongoError: Invalid Operation, No operations in bulk
I20160128-15:02:08.388(6)?     at Object.toError (.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
I20160128-15:02:08.388(6)?     at [object Object].UnorderedBulkOperation.execute (.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/batch/unordered.js:353:16)
I20160128-15:02:08.388(6)?     at _.extend.wrapAsync (packages/meteor/helpers.js:118:1)
I20160128-15:02:08.388(6)?     at [object Object].Meteor.methods.inventory/backorder (common/methods.js:251:32)
```

Second. This error: `E11000 duplicate key error index`. Looks like this is an old not fixed mongo bug and currently I've faced with it in tests. As I understand this happens because of too many requests to `bulk` in short period of time (like tests does). Please, read these threads, they explain it very good: [here](https://groups.google.com/forum/#!topic/mongodb-user/APLpTS4iIuw) and [here](https://github.com/vsivsi/gridfs-locking-stream/issues/4)

**Comment by aaronjudd** [comment]
@zenweasel can we verify and close?

**Comment by zenweasel** [comment]
Verified Fixed
