### ISSUE TITLE
Behavior of Method orders/refunds/list

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#738]
I was going through the workflow for Items in order. Bumped into some issues. When investigated further, it turned out the return call from method "orders/refunds/list": function (paymentMethod)" is the reason where it is set up to run in Tracker.autorun(() in "ShippingInvoice.js".
Couple of Questions:
1. What is the expected Behavior  in case of Generic payment. (billing[0].paymentMethod.processor=Generic)
2.This method again call "Meteor.call(`${processor}/refund/list`". Is this complete as I could not locate any implementation in code for say paypal/refund/list ot Generic/refund/list.
Not sure if to be reported as bug or still in works.

**Comment by zenweasel** [comment]
I can't replicate the behavior of other payment method in Generic because when you issue a refund it does not get stored anywhere (see my ticket here: https://github.com/reactioncommerce/reaction/issues/709). So there are never any refunds to list.
If you have a suggestion as to what would be implemented on this payment method to make it more clear what happens here let me know. (I debated having it always return a refund, but it seems like that would be confusing because it would show up before you issued a refund)

**Comment by hrath2015** [comment]
Thanks for explaining.  I tested with Paypal express. It works so far without  issue.  It fails for Generic case as  check is done for string  in the APIs(generic/refund/list and GenericAPI.methods.refunds). For time being I commented both checks and it works with Generic Payment.  Let me know if u want me submit a PR if it is safe to comment out checks.  in these 2 instances.

**Comment by zenweasel** [comment]
Ah, I see what you are saying. I will fix the checks to be validating on `ReactionCore.Schemas.PaymentMethod`. That's what they should be doing. Thanks.

**Comment by zenweasel** [comment]
I've update the refund and refund list methods to work more completely (to the extent that they can). Once I realized that they wouldn't really work I must have given up on them. They should be better examples to model implementations on.
