### ISSUE TITLE
[suggestion] Handle L12n via 3rd party application

### ISSUE THREAD

**Issue by johannes-scharlach** [reactioncommerce/reaction#760]
Status Quo: Contributors are asked to add translation keys to `en.json` and if they don't do it, we log it on the client side. The only file that is kept in sync (most of the time) is the one for the English language. When I currently want to take care of German translations, I need to compare it to the English one AND search the source code where the translation is used, so that I can understand the context.

Proposal: There are numerous 3rd party applications that handle translation management really well: Keys added or deleted from `en.json` would automatically also be added or deleted from other locales, keeping localization cleaned and in sync.

One Application that I've used in the past for something like that is phraseapp.com. As far as I know they support open source projects for free. I'd happily take care of moving the translations if you like.

**Comment by aaronjudd** [comment]
@johannes we always intended to do something like this as we got closer - my real goal was to get the en.json to be a really solid and complete translation, then work to automate with a 3rd party service.   However, we need to make sure that we have a manual process as well, we don't want to force shops to sign up for a bunch of services for Reaction to work, these external dependencies should be "additional".    

Also,  the plan is to add management interfaces for the translations/languages soon, so that might be a good place to add some controls for this. (v0.12 added the i18n as a package, with a card on the dashboard).

Also @ramusus and @newsiberian have been working a lot on the translations, they might have some additional thoughts here.

**Comment by ramusus** [comment]
phraseapp.com from presentation video seems to me powerful enough. And as far as I understood there is no additional external dependancy - it's just management centre for i18n and translations could be easily exported to local machine of developer and committed after or committed straight to github automatically. 

It would be nice to try this service in case when "they support open source projects for free" and do not waste our time for inventing the bicycle again.

**Comment by newsiberian** [comment]
Idea is cool, but why not to use www.transifex.com? Semantic-UI is on it, Trello, Discuss even stackoverflow. Its says, they love open source)

**Comment by johannes-scharlach** [comment]
There is one additional change that I would like to propose:
Over the last years it seemed superior to me to use a flat key structure rather than nested json, because it makes it easy to copy & paste translation keys and simplifies refactoring.

---

As I see it, there are 2 steps to the integration of a translation app:

1) Managing the translation files
There are hundreds of services for this and I think we could argue forever which one is best. I agree with @ramusus that it is important not to reinvent the bicycle again. That is also the main pain I'm experiencing right now and I'd call this request a success if any system is used.

2) Efficiently working with translations & deep integration of a service
Optimally as a next step I would like to be able to have a good integration with the translation service, so that we don't need to manually upload and download translation files. This is where the difference between the services starts. Phraseapp and some others (I can't remember any specific ones) have a feature of "in context" translation, where you can write the translation in development mode in the place where it appears. This takes away some pains for translators and radically improves translation quality. @newsiberian this feature is apparently not available for transifex.com (they have it in transifex live, which doesn't manage the translation files...). I have never integrated the in context translation for phraseapp either, but judging from the documentation of it and of the i18n module it seems quite straightforward.

Something like that should probably integrated in an independent module, so that not everyone is forced to use the specific translation app we're going with.

**Comment by aaronjudd** [comment]
@johannes-scharlach have you reviewed  the format outlined here: http://i18next.com/translate/
and after reviewing this, particularly the concepts of `namespacing`, `keys` do you still disagree with the current format? 

I think this is a fairly well organized, and vetted structure and haven't had any problems working with it, I just think that we all need to review some of the more advanced topics here.  When I originally implemented i18next - > I do what I always do -> I implemented the most basic functionality to fulfill the immediate requirements, but choose a path that we could expand on.

For instance, giving all package their own namespace is easily accomplished (and I am implementing right now in an upgrade to i18next 2.0)  - we just defaulted to `core`. I did test multiple package namespaces when I implemented this, but the imports and registry stuff has changed a lot since then so I am reworking and testing now.

I have also set up an account with Transifex here: 

https://www.transifex.com/reactioncommerce/reaction/

Re: transifex this was an option planned way back when I first implemented - it was always what we intended to do as we neared the final beta stages - and now seems like a good time.

I'll gladly have this service perform the translations (and pay for them)- I've already loaded all our current format and all our existing files.   However, **what this means is that we really need to focus on getting all the possible i18n entries into the `en.json`**, anything in there, we'll have translated to other language..  _The other languages don't need to be completed_., but if anybody wants to review / collaborate on the translated files, I can add you on the **transifex** project. This might help: https://github.com/i18next/i18next-scanner, but haven't really looked into it.

re: `Phraseapp`, conceptually I wanted to build this functionality into Reaction UI itself..  when you select site language,  we would store a revision of the document you are editing with a language specific clone (for products etc), and site labels, etc would be editable directly in the translations (and could easily have attached UI inline editing as well.  Essentially we would just be adding language as a key to all collections and publications, in addition to shopId.

So even though `phraseapp` looks cool, I'm not sure we actually would want this long term, but I'm open to exploring the idea more.   One issue I see right now is now open source project pricing, and we always want a service that lets us invite additional users without cost. (hard to have to pay for all our contributors at this stage). 

this is also an interesting project from i18next team that I'd like to look deeper into: https://github.com/i18next/i18nextify

Also see related issue started by @newsiberian in #804

**Comment by aaronjudd** [comment]
Here's another one worth looking at, but without obvious OSS info. https://localizejs.com/

I like what phraseApp and localize offer, I wonder if it's a good enough base functionality for sites to just be edited in one language and to rely on translations on the fly like this.  Are they good enough that you'd not ever need to maintain alternate copy locally? (for stuff like product descriptions,etc?)  That seems like it could be a stretch, but worth looking at more.  I'd think automated translation for your content would be more desirable than actually managing all that, but I'd still like the option to provide local customization.

**Comment by aaronjudd** [comment]
Closing in favor of #1111 -> in progress now, and we should have languages updated for our next release.

**Comment by jamuhl** [comment]
Just to add here for the future: http://locize.com is the new translation management provided by the i18next team - comes with incontext editing and more. Might be to late - but for the future it might be a good consideration.

**Comment by aaronjudd** [comment]
@jamuhl we actually use LingoHub now, but those are for core files, I'm continuing to research options for on-the-fly conversion for when we implement content conversion, so I'll take another look.

**Comment by jamuhl** [comment]
Great. If you got any questions about locize you can directly reach me by email jan.muehlemann@gmail.com
