### ISSUE TITLE
License (GPL)

### ISSUE THREAD

**Issue by aramk** [reactioncommerce/reaction#773]
Hi everyone,
Reaction is licensed under GPLv3, which is a copyleft license which differs from Apache2 or MIT primarily in the need to public all source code, even for commercial applications. Considering the library is for ecommerce, is it a reasonable expectation to require these sites to publish their source code publicly? I think some sites would opt to keep their code private, especially if they've heavily modified the framework with their own components and consider it their intellectual property. Has there been any discussion about this in the past? I'm just curious while looking at ecommerce frameworks. Keep up the awesome development!

**Comment by aaronjudd** [comment]
Nobody has really brought it up, but my understanding it that GPL it only requires you to publish your source if you are planning to commercially resell Reaction itself as a product, not if you are modifying for business/commercial use.

**Comment by aramk** [comment]
I found [this](http://www.gnu.org/licenses/gpl-faq.en.html#GPLCommercially) which mentions the condition of publishing the source code, but I'm not sure whether modifying the framework is different to reselling the framework itself.

**Comment by tdecaluwe** [comment]
@aaronjudd That is the correct interpretation, however this applies to any release. The GPL doesn't say anything about software you don't release and it surely doesn't require you to release code based on Reaction.

Compared to the LGPL, the GPL additionally requires that any software incorporating or based on Reaction should also be released under the GPL, think about themes, extensions or even PaaS solutions for example.

Lots of interesting info can be found in the Drupal (also an GPL project) FAQ about licensing: https://www.drupal.org/about/licensing.

**Comment by aramk** [comment]
Thanks for the Drupal link, @tdecaluwe. I'm a bit confused when you mention GPL doesn't require you to release code publicly when modifying Reaction. Is hosting a service built on a framework (including modifying and extending) considered distribution?

**Comment by tdecaluwe** [comment]
If the service is offering the clients the possibility to run GPL-covered software, I think the answer would be yes. However, if you'd offer clients the possibility to run a shop in a multi-tenant Reaction install, the answer becomes less clear. Is this the sort of thing you're talking about?

**Comment by aramk** [comment]
It'll be an online store which we add products to and customers browse, so I don't think there will be store owners. In any case, it's purely SaaS on a single host. I doubt there'd be any issues since it's the primary market for the framework? Repackaging the framework under a new name with modifications would require licensing under GPL, I think.

**Comment by lijiming** [comment]
I view MIT license is more favorable with peace of mind. will you add MIT or similar license?

**Comment by spencern** [comment]
I also view the MIT license as more favorable, but will continue to develop on ReactionCommerce either way. There was a lot of GPL related drama around Wordpress (perhaps still going on?) and it's contributors a few years back and I know a number of developers who won't touch GPL code for corporate projects.

**Comment by aaronjudd** [comment]
I'm aware that some licenses, such as MIT are more permissive. While those more permissive licenses are great for modules and many projects -  It think it's a little less useful for a project that is not meant as a dependency. 

We did quite a bit of research, and reviewed with our legal team before we added the **GPLv3** license to the project - just to be clear that it wasn't just a random choice from the dropdown on project creation.

Our goal in choosing GPL is to permit the activities of copying, modifying and distributing the software, which without a license would have otherwise been prohibited under copyright laws.

Where the more permissive licenses do not work for us, is that many allow for the **privatization** of Reaction for commercial gain.  

 As we want a healthy community, I can't see any reason we'd encourage privatization - which is where (we as a project) don't get contributions, patches, fixes, etc because their private code cannot be contributed back to the project.  It should be noted, this isn't project being built for free as a hobby - we have investors, a small team, and a vision that we'd like to nurture through open source, but not entirely through Open Source.  We intend to have private commercial packages that are not distributed as open source, and there is nothing that I see in the GPL that would prevent similar models for other companies.

And while we want to encourage distribution and re-use, we also want to promote a healthy focus on Reaction as a community project at the same time as protecting our rights as the intellectual developers of Reaction.

<u>The GPLv3 does not prevent the commercialization / privatization of packages for Reaction</u>, nor does it prevent you from commercializing Reaction (as a product, service, or otherwise). 

Look, at the end of the day, we're not lawyers.. we want you to use and distribute (and give the community some credit).

If you have specific cases you're curious about, shoot us an email at hello@reactioncommerce.com and let's discuss.

**Comment by aramk** [comment]
Thanks @aaronjudd, that's a clear explanation.

**Comment by aaronjudd** [comment]
@aramk @spencern worth noting as well that I think most of the Wordrpress communities issues with GPL was that they are/were requiring/enforcing packages to be GPL. We're double checking, and looking into that aspect of GPL,  because we've been approaching this as packages are independent source, but would be good to be sure.

**Comment by spencern** [comment]
Thanks @aaronjudd. Appreciate the clarity surrounding packages as well as that's the only place any concern of mine stemmed from.

**Comment by lijiming** [comment]
Thanks @aaronjudd for the clarity.
