### ISSUE TITLE
mup-deploy yields build error.

### ISSUE THREAD

**Issue by thekavish** [reactioncommerce/reaction#809]
I have successfully passed `mup-setup` command without any errors. Following is the error I am getting at my terminal window when I enter `mup-deploy`. 

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Building Started: .

Started TaskList: Deploy app 'reaction-app' (linux)
[XXX.XXX.XXX.XXX] - Uploading bundle
[XXX.XXX.XXX.XXX] ✔ Uploading bundle: SUCCESS
[XXX.XXX.XXX.XXX] - Setting up Environment Variables
[XXX.XXX.XXX.XXX] ✔ Setting up Environment Variables: SUCCESS
[XXX.XXX.XXX.XXX] - Invoking deployment process
[XXX.XXX.XXX.XXX] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added 'XXX.XXX.XXX.XXX' (ECDSA) to the list of known hosts.
    npm WARN excluding symbolic link browser -> dist/browser
    npm WARN deprecated github-flavored-markdown@1.0.1: This project is long out of date. Use 'marked' instead.
    npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
    npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
    npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
    npm WARN deprecated tap-assert@0.0.11: use the 'tap' module instead
    npm WARN deprecated tap-producer@0.0.1: This module is not supported. Please use 'tap' instead.
    npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.
    -----------------------------------STDOUT-----------------------------------
    -gyp rebuild 2> builderror.log) || (exit 0)

    make: Entering directory `/opt/reaction-app/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    make: Leaving directory `/opt/reaction-app/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'

    > bson@0.2.22 install /opt/reaction-app/tmp/bundle/programs/server/npm/cfs_gridfs/node_modules/mongodb/node_modules/bson
    > (node-gyp rebuild 2> builderror.log) || (exit 0)
```

**Comment by jshimko** [comment]
You didn't do any manual setup on the server, right?

Can you share your mup config?  (without the secret bits, of course)

**Comment by thekavish** [comment]
Following is my mup config file content:

```
{
    "servers": [{
        "host": "XXX.XXX.XXX.XXX",
        "username": "root",
        "password": "<Password>"
    }],

    "setupNode": true,
    "nodeVersion": "0.10.40",
    "setupPhantom": true,
    "setupMongo": true,

    "appName": "reaction-app",
    "app": ".",

    "env": {
        "ROOT_URL": "URL/to/my/server",
        "PORT": 3000
    },

    "deployCheckWaitTime": 30
}

```

**Comment by jshimko** [comment]
Hey @thekavish.  I did some testing and I'm having a few different issues with MUP.  I can't even get as far as you did.  It fails in the local build process before it even uploads the bundle.  Actually, it's this specific issue...

https://github.com/arunoda/meteor-up/issues/812

Unfortunately, MUP appears to be getting ignored these days.  There are 463 open issues and 45 pull requests.  The readme states:

>This version is no longer maintaining.
>Mupx is the stable version. 
>New development is moved to here: https://github.com/kadirahq/meteor-up.

But then when you go check out that mupx repo, its readme says:

>This version of Meteor Up is still in development. Please check arunoda/meteor-up for the stable version.

So yeah, needs some attention for sure.  That said, Reaction builds just fine outside of MUP and with other deployment options like Docker, so I'm not sure this issue is on our side.  I'd say you could file an issue over at the MUP repo, but it unfortunately looks like there's a decent chance you'd get ignored.

Sorry I don't have a better answer for you.  We're working on a Reaction-specific deployment tool that aims to accomplish the same things (simple, minimal configuration deployments), so keep an eye out for that.  In the meantime, have you given Docker a try yet?
