### ISSUE TITLE
Code splitting

### ISSUE THREAD

**Issue by tdecaluwe** [reactioncommerce/reaction#829]
I stumbled upon this repo recently, which talks about code splitting in meteor apps: https://github.com/thereactivestack/kickstart-hugeapp. Since the reaction client bundle is starting to reach a respectable size (nearly 3MB for js and css when I last checked) and because most users don't use a lot of the included code (the admin part, although I don't know what it's dependency footprint is) it might be a good idea to implement this technique to relieve initial page load time.

An implementation might, for example, include the following bundles:
- An anonymous or main bundle
- A registered user bundle
- An admin bundle (splitting out the whole admin panel)
- A proceed to checkout bundle (splitting out payment packages and checkout workflow)

**Comment by aaronjudd** [comment]
There's a lot of changes coming in Meteor 1.3, and I'm sure we'll be adopting all those changes (import / export modules).  This will make a difference.  I've also been keeping an eye on these webpack talks, and was hoping that 1.3 would get there, but sounds like that's not going to happen now, but there will be some kind of module loading.  In any case, very aware that we'll have to solve this issue and do some general performance / bundling optimization before we're fully endorse for production.  Just not moving to aggressive on it right now, because I'd like to see the dust settle just a bit more.  
We can leave this issue as a placeholder for this optimization work though, and see how the discussion progresses..

**Comment by aaronjudd** [comment]
Related to #848
