### ISSUE TITLE
Significant delay from "Checkout Complete Order" to "thank you" screen

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#845]
Noticed this after migration to flow router. Even in  fresh build did just now it is visible.  There is noticeable delay before thank you screen is loaded.  Logging it so that remain on radar.

**Comment by zenweasel** [comment]
I've been seeing this for a while as well but thought it might be an environmental issues since nobody else on the team was seeing it. It happens with all Payment methods and if you refresh the page it's there, and from what I have seen the order is always completed.

**Comment by zenweasel** [comment]
Retested with all payment methods and no longer seeing this issue/behavior. If someone else is still seeing it, please reopen with details about environment, etc.

**Comment by zenweasel** [comment]
Ok, after running through this close to 20 times and not seeing it I am now seeing it again. It seems to happen when I am logged in and it really looks like the delay is caused by it trying to send an email (which may be why I wan't seeing it as anonymous). Every time it happens the error `Error invoking Method 'cart/submitPayment': Unable to send shipment notification email. [403]` appears as well.

**Comment by zenweasel** [comment]
Confirmed that the issue is in sending email. I DO have an email host configured but I am getting
 `Error: connect ETIMEDOUT`. Sending email should probably not be blocking showing the completed screen.

**Comment by zenweasel** [comment]
Turns out that Email sending it a blocking function so that if you are up against a timeout this problem is unavoidable. If you have NO email configuration or one that fails quickly this would not be an issue.

We will probably come back to make sending email an asynchronous function but for now this can be fixable by just correcting the email configuration.
