### ISSUE TITLE
Meteor 1.3 Upgrade

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#848]
Including #772 and migrate core packages to import/export/module loading.  Move to npm package loading and remove bower libs.

Discuss...

**Comment by newsiberian** [comment]
I'm on 1.3. Need any help with it?

**Comment by aaronjudd** [comment]
That's the general direction for sure and the structure is quite similar to what we have, but we'll need to move some stuff up into the app (I like the app level structure on the todo as an example).  @mikemurray and I were just discussing how awesome and important this update is, so we'd like to get going on this asap. -We should be wrapping up v0.12 soon,  so we can make a branch for this, and happy to start taking PR's into that branch for v0.13 (which is also meant to be a stability release, so we'll see how this is going before deciding what version this really falls into).  Maybe we can outline the structure a little more if needed but for me, that'd require me to start moving stuff ;-)

**Comment by newsiberian** [comment]
Hello all. @tdecaluwe, Tom, looks like [this](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/server/import.js#L111) check is crushes reaction starting from `meteor-1.3-beta-11` with error `RangeError: Maximum call stack size exceeded`. Reason: [here](http://stackoverflow.com/a/18691480) Could we do something with it?

**Comment by tdecaluwe** [comment]
Since objects are passed by reference in JS, I don't understand how passing a collection could be a problem. Does the error go away if you replace the check by `check('', String)`? And what does the stack look like just before the error throws? For some reason when trying to upgrade to 1.3 I run into a lot of bower errors.

**Comment by newsiberian** [comment]
about bower: you need to add `dependencies: {}` to each of requested files. This is a bower wrapper bug.

**Comment by newsiberian** [comment]
stack:
```
W20160304-18:09:48.417(6)? (STDERR) 
W20160304-18:09:48.418(6)? (STDERR) /home/sohaam/.meteor/packages/meteor-tool/.1.1.13-beta.12.1weswws++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160304-18:09:48.419(6)? (STDERR) RangeError: Maximum call stack size exceeded
W20160304-18:09:48.419(6)? (STDERR) 						throw(ex);
W20160304-18:09:48.419(6)? (STDERR) 
```
With `check('', String)` it runs fine, but I ran it without checks and it is also fine. Forgot to say, this happens then `shops` collection passed. It's too big for check according to link logic I provide.

**Comment by tdecaluwe** [comment]
Yes, I read the link, I just get the feeling that this error shouldn't be happening here. If `check()` were to pass the objects from client to server or serializing the objects in any other way this kind of thing would make sense (for example, if you'd try to serialize a recursive JS object, a call stack size error would only be logical).

However this code runs completely server side and should only be passing around references. Additionally, I'd expect the call depth to be the same with the empty string replacement. That aside, since the `check()` isn't critical for the method we could just remove it, however I think it'd be better for it to stay. And I can't see a reason why it couldn't...

**Comment by newsiberian** [comment]
Hi, continue: the bad thing about meteor-1.3 for now -- WebStrorm server debugging doesn't work with it to me :disappointed:

**Comment by rorschach217** [comment]
i want to know that if i update meteor to 1.3 version, then what happens ? my project is in meteor 1.2.1, is update affect my project in any manner ?

**Comment by aaronjudd** [comment]
@rorschach217 didn't see this comment sorry... upgrading to Meteor 1.3 does require significant updates that are already in the development branch (reaction v0.13.0).  We are still in progress with the refactoring to a new modular app structure though, so the development branch will be in flux until we've got all the 0.13 updates made.

**Comment by aaronjudd** [comment]
closing this as we're working through stable releases of the current development branch until v0.15 or so, and hope to release a final stable version of the 1.3.x "compatible" Reaction.  Refactoring  is going on in the `module-structure` branch, and I'm expecting that we'll have this as major release after v0.15 is released.. #1008 is tracking that activity.
