### ISSUE TITLE
Clarification on variant/option naming convention

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#899]
Currently in the productVariant schema there exists a 'Title' and an 'Option Title' field. If we are setting up products that have multiple variants (e.g. Color and Size) is there an expectation on how to define those fields? 

E.g.
```
{
  _id: 'A1',
  optionTitle: 'Color',
  title: 'Green'
}, {
  _id: 'A2',
  optionTitle: 'Color',
  title: 'Blue'
}, {
  _id: 'B1'
  ancestors: ['A', 'A1']
  optionTitle: 'Size',
  title: 'Small'
}
```

**Comment by aaronjudd** [comment]
The recent updates with flattened products changed the pattern that we had been using.  Previously `title` was displayed on the PDP and optionTitle was used in the cart / checkout, and was meant to be used more like a "sku" ->  for clarity in checkout.  

I reviewed the updates, and where we are now using `optionTitle` for all the labels.  I'm personally not sure that there should be two labels,  and title should just be replaced with a  `sku` field, if this is how we're going to use `title`.  (and optionTitle could just be `title`).  

Otherwise, we could leave as is, in which case,  `title` should be unique descriptor, and `optionTitle` is for labels.

**Comment by spencern** [comment]
I think there is probably some value in defining the type of option or variant that is being labeled. I think this is what you are referring to as a 'label' for now (e.g. 'Size' or 'Color', not 'Green' or 'Small')  We are in the process of modifying the existing buttons on the PDP to use selects instead of buttons, we will need to have a label for these selects to inform the customer of what they are selecting.

I was thinking that the fields that would make sense to me might be `option` and `optionTitle` rather than `title` vs `optionTitle`

Regardless, I think there's value in having a convention for using one of them to define the category or type of the variant (e.g. `Size` and another to define the value of the variant (e.g. `Small`)

**Comment by aaronjudd** [comment]
Closing, but referenced here: https://github.com/reactioncommerce/reaction-docs/issues/24  we'll add docs, and maybe a new issue to refactor this if necessary.
