### ISSUE TITLE
Are ProductVariant price and qty fields should be mandatory?

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#947]
Hello, I propose to consider the following.

Why we have variant `price` and `inventoryQuantity` field as mandatory? For top variant `inventoryQuantity` could be dropped right after we add new child variants to it, so at this point mandatory is not necessary. Then shop owners could choose not to use inventory at all and at this point, again... And last - `reaction-schema` reuse client helpers within custom functions for checking `requirement` - `ReactionProduct.checkChildVariants()` which is pain for such guys like me who don't use default blaze UI :sob:

@aaronjudd, this question is worth discussing, or I missed something important?

**Comment by aaronjudd** [comment]
@newsiberian I see the PRs you submitted, these are related to this...

**Comment by newsiberian** [comment]
Hello, no they are not. If you agree with this idea, then we could remove "required" check from those fields in variant schema with their custom check to prevent `Autoform` display errors on these fields if we don't want to fill them.

**Comment by aaronjudd** [comment]
I think that price needs to remain a required field.  If anything the price range needs to be applied equally to product and variant. There is no real reason that the variant and product schema should be different, and the same range could probably be applied to both, but for now, let's leave as is. 

 The `inventoryQuantity` could be made optional though, because the real purpose of `inventoryQuantity` on the product is not to actually track inventory, but as a "denormalized" field for containing the summary of inventory as managed by an inventory package (ie, reaction-inventory).  

If there is any remaining logic around quantity that is directly updating the product collection as part of the cart flow, as the updating of this value, should be entirely moved to external processes. 

We have on the roadmap to rebuild the PDP page, and will be moving most of this functionality into the settings sidebar, where we can build some better inline views of inventory, but at this point having the ability to input the inventory on the variant is the easiest way to configure the initial inventory. If you don't have an inventory package installed though, then nothing should happen other than the value is stored.
